from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

LEDGER = TEST_RESULTS / "01_copy_source_ledger.json"
POLICY_GATE = TEST_RESULTS / "02_copy_source_policy_gate.json"
CONTEXT_GATE = TEST_RESULTS / "03_copy_source_context_gate.json"
OUT = REPORTS / "final_copy_source_generation_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    ledger = load_json(LEDGER)
    policy = load_json(POLICY_GATE)
    context = load_json(CONTEXT_GATE)
    assert_boundary("copy_source_ledger", ledger)
    assert_boundary("copy_source_policy_gate", policy)
    assert_boundary("copy_source_context_gate", context)
    ls = ledger["summary"]
    ps = policy["summary"]
    cs = context["summary"]
    promoted = (
        ps["promotes_copy_source_generator"] or cs["promotes_copy_source_generator"]
    )
    classification = (
        "COPY_SOURCE_GENERATOR_PROMOTED"
        if promoted
        else "COPY_SOURCE_GENERATOR_REJECTED"
    )
    lines = [
        "# Final Copy Source Generation Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "After granting the exact skeleton and literal payload, can the remaining",
        "`208` copy-source fields be generated by decoder-visible source rules or",
        "by source-context selectors that generalize?",
        "",
        "## Ledger",
        "",
        f"- Copy events: `{ls['copy_event_count']}`.",
        f"- Oracle target-chunk matching sources: `{ls['total_matching_sources']}` total.",
        f"- Matching sources min/median/max: `{ls['min_matching_sources']}` / `{ls['median_matching_sources']}` / `{ls['max_matching_sources']}`.",
        f"- Single-source events: `{ls['single_matching_source_events']}`.",
        f"- Multi-source events: `{ls['multi_matching_source_events']}`.",
        f"- Canonical source is earliest matching in `{ls['canonical_earliest_matching_events']}/208` events.",
        f"- Canonical source is latest matching in `{ls['canonical_latest_matching_events']}/208` events.",
        f"- Oracle rank bits among matching sources: `{ls['oracle_rank_bits_among_matching_sources']:.3f}`.",
        f"- Raw absolute source bits: `{ls['raw_absolute_source_bits']:.3f}`.",
        "",
        "The strong earliest-matching signal is not a generator by itself: it",
        "requires knowing which target chunk the copy must reproduce.",
        "",
        "## Policy Gate",
        "",
        f"- Decoder-visible policies tested: `{ps['decoder_visible_policy_count']}`.",
        f"- Target-aware oracle controls tested: `{ps['target_aware_control_count']}`.",
        f"- Best decoder-visible policy: `{ps['best_decoder_policy']}`.",
        f"- Best decoder-visible chunk hits: `{ps['best_decoder_chunk_hits']}/{ps['copy_events']}`.",
        f"- Best decoder-visible sequential exact books: `{ps['best_decoder_exact_books_sequential']}/{ps['best_decoder_book_total']}`.",
        f"- Best oracle control chunk hits: `{ps['best_oracle_chunk_hits']}/{ps['copy_events']}`.",
        "",
        "The oracle controls prove the candidate set can reproduce the books when",
        "the target chunk is already known. They do not remove source choice from",
        "the generation recipe.",
        "",
        "## Context Gate",
        "",
        f"- Context families tested: `{cs['context_family_count']}`.",
        f"- Best context: `{cs['best_context']}`.",
        f"- Best full-fit chunk hits: `{cs['best_chunk_hits']}/{cs['copy_events']}`.",
        f"- Best full-fit source-exact hits: `{cs['best_source_exact']}/{cs['copy_events']}`.",
        f"- Best net vs raw absolute source bits: `{cs['best_net_vs_raw_absolute_source_bits']:.3f}` bits.",
        f"- Prefix/holdout cover-all cells: `{cs['prequential_cover_all_chunk_cells']}/{cs['prequential_cells']}`.",
        "",
        "The best full-fit context is still source-bearing and does not cover all",
        "copies. Prefix/holdout does not produce a cover-all source selector.",
        "",
        "## Decision",
        "",
        "- No copy-source generator is promoted.",
        "- The `208` source fields remain external after granting skeleton and literal payload.",
        "- Target-aware earliest/matching-source controls are parser/oracle controls, not generation rules.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Copy source ledger](test_results/01_copy_source_ledger.md)",
        "- [Copy source policy gate](test_results/02_copy_source_policy_gate.md)",
        "- [Copy source context gate](test_results/03_copy_source_context_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
