#!/usr/bin/env python3
"""Compile E/diagonal/zero lore bridge evidence from existing probes."""

from __future__ import annotations

from post_review_common import HERE, write_json


OUT_JSON = HERE / "e_layer_lore_bridge_audit_results.json"
OUT_MD = HERE / "e_layer_lore_bridge_audit.md"


def main() -> None:
    rows = [
        {
            "front": "shared_i_ge_j_predicate",
            "evidence": "diagonal E 5/10, 33/66 anchors 2/2, zero holdout delta 0.120, joint p=0.00280",
            "source": "shared_e_zero_predicate_report.md",
            "status": "shared_predicate_signal_only",
        },
        {
            "front": "e_inventory_predicates",
            "evidence": "diag OR both_in_4578 and prod_eq_5 OR both_in_4578 show weak E-layer signal, but exact fit remains unavailable",
            "source": "e_layer_predicate_report.md",
            "status": "weak_e_layer_signal",
        },
        {
            "front": "priority_masked_e_layer",
            "evidence": "15/15 local claims hit, but model charges selected blockers/high-block/diagonal choices and is not global",
            "source": "priority_masked_e_layer_report.md",
            "status": "exact_local_e_priority_layer_not_global_formula",
        },
        {
            "front": "high_block_blockers",
            "evidence": "best blocker rule exactly selects 45/55/77/88, but conditional p=0.17409 and digit-set p=1.0 block promotion",
            "source": "high_block_blocker_origin_report.md",
            "status": "high_block_blocker_not_promoted",
        },
        {
            "front": "render_features_for_e_priority",
            "evidence": "render/orientation features are supporting context only and do not explain E-priority as a general origin rule",
            "source": "render_origin_e_priority_probe_report.md",
            "status": "supporting_context_not_formula",
        },
    ]
    result = {
        "schema": "e_layer_lore_bridge_audit.v1",
        "translation_delta": "NONE",
        "verdict": "E/diagonal/zero is a real local mechanism bridge but not a recovered matrix formula",
        "rows": rows,
    }
    write_json(OUT_JSON, result)

    lines = [
        "# E-Layer Lore Bridge Audit",
        "",
        "Generated by `e_layer_lore_bridge_audit.py`.",
        "",
        "This compiles the post-review E/diagonal/zero front into current",
        "controlled evidence. It is mechanism-only.",
        "",
        "| Front | Evidence | Status | Source |",
        "|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| `{row['front']}` | {row['evidence']} | `{row['status']}` | `{row['source']}` |")
    lines += [
        "",
        "## Verdict",
        "",
        "The E layer has real local structure, especially diagonal pressure and a",
        "shared `i>=j` signal with zero rendering. The blockers and off-diagonal",
        "fills remain too selected/local to become the original row0 formula.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
