#!/usr/bin/env python3
"""Classify known external numeric strings without promoting semantics."""

from __future__ import annotations

from post_review_common import GEN, HERE, LORE, load_json, write_json


OUT_JSON = HERE / "external_numeric_string_classifier_results.json"
OUT_MD = HERE / "external_numeric_string_classifier.md"


def main() -> None:
    scores = load_json(GEN / "external_holdout_scores.json")["rows"]
    deep = load_json(LORE / "deep_verification_results.json")

    rows = [
        {
            "name": "chayenne",
            "raw_digits": "1145145194856114519083045765122821776612527570584",
            "evidence": "minLen=8 coverage 45/49; minLen=3 coverage 49/49",
            "classification": "copy_holdout_like_secondary_validation",
            "semantic_value": "NONE",
        },
        {
            "name": "your_true_colour",
            "raw_digits": "785673433498913565142",
            "evidence": "minLen=8 coverage 0/21; minLen=3 coverage 19/21",
            "classification": "external_unknown_event_layer",
            "semantic_value": "NONE",
        },
        {
            "name": "secret_library_74032_45331",
            "raw_digits": "7403245331",
            "evidence": "confirmed external unglossed book; 0 exact hits for 74032, 45331, and 7403245331 in the 70-book corpus",
            "classification": "external_numeric_anchor",
            "semantic_value": "NONE",
        },
        {
            "name": "honeminas_primary_vectors",
            "raw_digits": "4315334784",
            "evidence": "primary vectors 43153 and 34784 have 0 exact hits; shorter 3478 is structural/common",
            "classification": "generator_selector_hypothesis_only",
            "semantic_value": "NONE",
        },
        {
            "name": "avar_tar",
            "raw_digits": "".join(load_json(GEN / "generator_holdout_manifest.json")["negative_controls"]["avar_tar"]),
            "evidence": "negative control; minLen=8 coverage 0/115 in external holdout report",
            "classification": "negative_control_not_true_469",
            "semantic_value": "NONE",
        },
    ]
    result = {
        "schema": "external_numeric_string_classifier.v1",
        "translation_delta": "NONE",
        "source_scores_available": sorted(scores.keys())[:20],
        "deep_verification_schema": deep.get("schema"),
        "rows": rows,
    }
    write_json(OUT_JSON, result)

    lines = [
        "# External Numeric String Classifier",
        "",
        "Generated by `external_numeric_string_classifier.py`.",
        "",
        "This classifies known external numeric strings for future triage. It does",
        "not promote a translation or create a number-to-word mapping.",
        "",
        "| String | Classification | Evidence | Semantic value |",
        "|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| `{row['name']}` | `{row['classification']}` | {row['evidence']} | `{row['semantic_value']}` |")
    lines += [
        "",
        "## Verdict",
        "",
        "Only Chayenne behaves like secondary copy/module compatibility. Secret",
        "Library is a confirmed numeric anchor, YTC remains unknown/event-like, and",
        "Avar Tar remains the negative control. None supplies plaintext.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
