#!/usr/bin/env python3
"""Compile observer/viewer transform evidence from existing render probes."""

from __future__ import annotations

from post_review_common import GEN, HERE, write_json


OUT_JSON = HERE / "observer_transform_render_audit_results.json"
OUT_MD = HERE / "observer_transform_render_audit.md"


def main() -> None:
    rows = [
        {
            "signal": "ordered_surface_mirror",
            "source": "directed_pair_surface_report.md",
            "evidence": "99/100 ordered codes present; lower surface mirror-copy gives 43/45 before exception/orphan metadata and 45/45 after it",
            "status": "accepted_render_orientation_layer",
        },
        {
            "signal": "19_91_directed_conflict",
            "source": "directed_pair_surface_report.md",
            "evidence": "19 -> I and 91 -> N are the only directed conflict pair",
            "status": "accepted_directed_exception",
        },
        {
            "signal": "39_absent_93_orphan",
            "source": "directed_pair_surface_report.md",
            "evidence": "39 is absent while 93 is present; metadata closes mirror-copy lower-surface reconstruction",
            "status": "accepted_orphan_render_metadata",
        },
        {
            "signal": "book_holdout_orientation_context",
            "source": "orientation_render_rule_report.md",
            "evidence": "pair_prevcode reaches 680/730 (0.932) on book holdout with control p=0.00050",
            "status": "candidate_orientation_render_channel_not_pair_formula",
        },
        {
            "signal": "pair_holdout_grid_formula_failure",
            "source": "orientation_render_rule_report.md",
            "evidence": "best pair-holdout model reaches only 0.526 and is not a general pair formula",
            "status": "rejected_as_matrix_formula",
        },
        {
            "signal": "6_9_visual_symmetry",
            "source": "digit_visual_symmetry_report.md",
            "evidence": "best seven-segment/6-9 visual model remains worse than lookup after MDL",
            "status": "weak_visual_clue_rejected_formula",
        },
        {
            "signal": "zero_render_context",
            "source": "zero_compact_rule_report.md",
            "evidence": "zero omission has local previous-code/geometry support but selected predictive rules do not beat code_only under rough MDL",
            "status": "supporting_render_layer",
        },
    ]
    result = {
        "schema": "observer_transform_render_audit.v1",
        "translation_delta": "NONE",
        "verdict": "observer/viewer language maps to render-orientation metadata, not plaintext or a new row0 formula",
        "rows": rows,
    }
    write_json(OUT_JSON, result)

    lines = [
        "# Observer Transform / Render Audit",
        "",
        "Generated by `observer_transform_render_audit.py`.",
        "",
        "This compiles the post-review `subjective viewer` front into existing",
        "render/orientation evidence. It does not assign plaintext.",
        "",
        "| Signal | Evidence | Status | Source |",
        "|---|---|---|---|",
    ]
    for row in rows:
        lines.append(f"| `{row['signal']}` | {row['evidence']} | `{row['status']}` | `{row['source']}` |")
    lines += [
        "",
        "## Verdict",
        "",
        "The observer/viewer hypothesis is supported only as a render/orientation",
        "layer: mirror-copy, directed exception, missing-code metadata, and local",
        "orientation context. It does not derive the row0 pair labels and does not",
        "change the semantic verdict.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
