#!/usr/bin/env python3
"""Classify external/speaker sources by eye-count and numeric-layer role."""

from __future__ import annotations

import json

from post_review_common import EYE, GEN, HERE, load_json, write_json


OUT_JSON = HERE / "speaker_eye_count_layer_classifier_results.json"
OUT_MD = HERE / "speaker_eye_count_layer_classifier.md"


def main() -> None:
    registry_text = (EYE / "eye_count_source_registry.yaml").read_text(encoding="utf-8")
    rows = [
        {
            "source": "A Wrinkled Bonelord",
            "speaker_or_class": "Bonelord",
            "visible_eye_count_proxy": 5,
            "layer_class": "lore_mechanism_viewer_arity",
            "evidence": "enough eyes / subjective viewer lore; current Bonelord first-frame sprite count is five peripheral eyes",
        },
        {
            "source": "Elder Bonelord",
            "speaker_or_class": "Elder Bonelord",
            "visible_eye_count_proxy": 5,
            "layer_class": "phrase_or_npc_context_only",
            "evidence": "Elder sprite first-frame count is five; no official glossed numeric pair",
        },
        {
            "source": "The Evil Eye",
            "speaker_or_class": "Evil Eye / boss",
            "visible_eye_count_proxy": 5,
            "layer_class": "phrase_or_npc_context_only",
            "evidence": "Evil Eye sprite first-frame count is five; no official glossed numeric pair",
        },
        {
            "source": "Gazer",
            "speaker_or_class": "one-eye creature",
            "visible_eye_count_proxy": 1,
            "layer_class": "negative_arity_contrast",
            "evidence": "Gazer first-frame count is one central eye",
        },
        {
            "source": "Eye of the Seven",
            "speaker_or_class": "one-eye trap/creature style",
            "visible_eye_count_proxy": 1,
            "layer_class": "negative_arity_contrast",
            "evidence": "Eye of the Seven first-frame count is one central eye",
        },
        {
            "source": "Chayenne",
            "speaker_or_class": "external employee/interview string",
            "visible_eye_count_proxy": None,
            "layer_class": "copy_holdout_like_secondary_validation",
            "evidence": "external holdout minLen=8 coverage 45/49; not a speaker anatomy source",
        },
        {
            "source": "Secret Library 74032 45331",
            "speaker_or_class": "external numeric book",
            "visible_eye_count_proxy": None,
            "layer_class": "external_numeric_anchor",
            "evidence": "confirmed unglossed numeric book, absent from 70-book corpus",
        },
        {
            "source": "Avar Tar",
            "speaker_or_class": "external poem/control",
            "visible_eye_count_proxy": None,
            "layer_class": "negative_control_not_true_469",
            "evidence": "negative control; minLen=8 coverage 0/115",
        },
    ]
    result = {
        "schema": "speaker_eye_count_layer_classifier.v1",
        "translation_delta": "NONE",
        "source_registry_loaded": "visible_eye_count" in registry_text,
        "rows": rows,
    }
    write_json(OUT_JSON, result)
    lines = [
        "# Speaker Eye-Count Layer Classifier",
        "",
        "Generated by `speaker_eye_count_layer_classifier.py`.",
        "",
        "This separates speaker/source anatomy cues from external numeric-string",
        "classes. It does not create a decoder.",
        "",
        "| Source | Eye-count proxy | Layer class | Evidence |",
        "|---|---:|---|---|",
    ]
    for row in rows:
        count = "n/a" if row["visible_eye_count_proxy"] is None else str(row["visible_eye_count_proxy"])
        lines.append(f"| `{row['source']}` | {count} | `{row['layer_class']}` | {row['evidence']} |")
    lines += [
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
