from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

GATE = TEST_RESULTS / "01_operation_cutpoint_lattice_gate.json"
OUT = REPORTS / "final_operation_cutpoint_lattice_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    gate = load_json(GATE)
    assert_boundary("operation_cutpoint_lattice_gate", gate)
    s = gate["summary"]
    classification = (
        "OPERATION_CUTPOINT_LATTICE_GENERATOR_PROMOTED"
        if s["promotes_cutpoint_lattice_generator"]
        else "OPERATION_CUTPOINT_LATTICE_GENERATOR_REJECTED"
    )
    lines = [
        "# Final Operation Cutpoint Lattice Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Can the operation cutpoints be generated by a small proportional",
        "lattice after granting book length and operation count?",
        "",
        "## Result",
        "",
        f"- Books/operations: `{s['book_count']}` / `{s['operation_count']}`.",
        f"- Internal cutpoints tested: `{s['internal_cutpoint_count']}`.",
        f"- Denominators tested: `{s['denominator_count']}`.",
        f"- Random controls per denominator: `{s['random_trials_per_denominator']}`.",
        f"- Best denominator: `{s['best_denominator']}`.",
        f"- Best exact books: `{s['best_exact_books']}/{s['book_count']}`.",
        f"- Best cutpoint hits: `{s['best_hits']}/{s['internal_cutpoint_count']}`.",
        f"- Best random mean/p95/max hits: `{s['best_random_mean_hits']:.3f}` / `{s['best_random_p95_hits']}` / `{s['best_random_max_hits']}`.",
        f"- Best hit lift vs random mean: `{s['best_hit_lift_vs_random_mean']:.3f}`.",
        f"- Prefix/holdout cover-all cells: `{s['prequential_cover_all_cells']}/{s['prequential_cells']}`.",
        f"- Prefix/holdout beats-random-p95 cells: `{s['prequential_beats_random_p95_cells']}/{s['prequential_cells']}`.",
        "",
        "The best denominator is not evidence of hidden lattice structure:",
        "its cutpoint hits are below the same-shape random-control mean,",
        "and no prefix-selected denominator covers held-out books or beats",
        "the held-out random p95.",
        "",
        "## Decision",
        "",
        "- No cutpoint-lattice generator is promoted.",
        "- Small proportional grids are rejected as an operation-skeleton source.",
        "- This closes a natural source-free boundary hypothesis without changing the formula.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Operation cutpoint lattice gate](test_results/01_operation_cutpoint_lattice_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
