#!/usr/bin/env python3
"""Algebraic digit-composition probe for the 469 pair table.

This pass asks whether the 55 unordered pair labels can be generated by:

    digit attributes -> simple pair operation -> bucket -> majority symbol

The bucket-to-symbol table is explicitly charged in MDL.  Large bucket
families such as natural min/max are kept in the search because they are useful
as lookup-disguise controls: they can reproduce the table, but only by making
one bucket per pair cell.

Mechanical only: no plaintext, no glossary, no semantic translation.
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"

OUT_JSON = HERE / "algebraic_digit_composition_results.json"
OUT_MD = HERE / "algebraic_digit_composition_report.md"

SIGMA = "*ABCEFILNORSTV"
SYMBOL_BITS = math.log2(len(SIGMA))
PAIR_COUNT = 55
RAW_LOOKUP_BITS = PAIR_COUNT * SYMBOL_BITS
INVENTORY_LOOKUP_NOTE = "multinomial primary-label inventory, reported only as secondary context"

RANDOM_SEED = 46920260619
CONTROL_TRIALS = 40
COMPACT_BUCKET_LIMIT = 28

LORE_SEEDS = ("469", "3478", "43153", "34784", "74032", "45331", "19", "39")
SIMPLE_MODULI = tuple(range(2, 15))
TUPLE_MODULI = tuple(range(2, 8))
AFFINE_MODULI = tuple(range(2, 15))
AFFINE_COEFS = (-2, -1, 1, 2)

LEARNED_SINGLE_K = (2, 3, 4, 5)
LEARNED_TWO_AXIS_K = (2, 3)
LEARNED_SINGLE_OPS = ("sum_mod", "diff_abs_mod", "product_mod", "xor_mod", "sumdiff_tuple", "minmax_raw")
LEARNED_TWO_AXIS_OPS = ("axis_sum_tuple", "axis_product_tuple", "axis_cross_sum_mod", "axis_minmax_tuple")
LEARNED_STARTS = 6
LEARNED_SWEEPS = 4
TOP_ROWS_OUT = 60


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def natural_pairs() -> list[tuple[int, int, str]]:
    return [(a, b, f"{a}{b}") for a in range(10) for b in range(a, 10)]


def symbol_sort_key(symbol: str) -> int:
    return SIGMA.index(symbol)


def majority_symbol(counter: Counter[str]) -> str:
    return min(counter, key=lambda symbol: (-counter[symbol], symbol_sort_key(symbol)))


def primary_pair_symbol(cell: dict[str, Any]) -> str:
    if cell["status"] == "pure":
        return cell["symbol_if_pure"]
    return min(cell["symbols"], key=symbol_sort_key)


def build_targets(formula: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for a, b, pair in natural_pairs():
        cell = formula["pair_table"][pair]
        rows.append(
            {
                "pair": pair,
                "a": a,
                "b": b,
                "status": cell["status"],
                "primary_symbol": primary_pair_symbol(cell),
                "acceptable_symbols": sorted(cell["symbols"], key=symbol_sort_key),
            }
        )
    return rows


def inventory_bits(labels: list[str]) -> float:
    counts = Counter(labels)
    total = math.lgamma(len(labels) + 1) / math.log(2)
    for count in counts.values():
        total -= math.lgamma(count + 1) / math.log(2)
    return total


def lore_rank_values(seed: str) -> list[int]:
    order: list[int] = []
    for char in seed:
        digit = int(char)
        if digit not in order:
            order.append(digit)
    for digit in range(10):
        if digit not in order:
            order.append(digit)
    rank = {digit: index for index, digit in enumerate(order)}
    return [rank[digit] for digit in range(10)]


def fixed_embeddings() -> list[dict[str, Any]]:
    embeddings: list[dict[str, Any]] = [
        {"id": "natural", "values": list(range(10)), "source": "digit_value", "model_bits": 1.0},
        {"id": "natural_rev", "values": list(reversed(range(10))), "source": "digit_value", "model_bits": 1.0},
        {
            "id": "collapse_6_9",
            "values": [6 if digit == 9 else digit for digit in range(10)],
            "source": "6_9_quotient",
            "model_bits": 2.0,
        },
        {"id": "parity", "values": [digit % 2 for digit in range(10)], "source": "mod_class", "model_bits": 2.0},
    ]
    for modulus in (3, 4, 5, 7):
        embeddings.append(
            {
                "id": f"digit_mod_{modulus}",
                "values": [digit % modulus for digit in range(10)],
                "source": "mod_class",
                "model_bits": 2.5,
            }
        )
    for seed in LORE_SEEDS:
        embeddings.append(
            {
                "id": f"lore_rank_{seed}",
                "values": lore_rank_values(seed),
                "source": "lore_digit_order",
                "uses_lore": True,
                "lore_seed": seed,
                "model_bits": 3.5 + math.log2(len(LORE_SEEDS)),
            }
        )
        seed_digits = {int(char) for char in seed}
        embeddings.append(
            {
                "id": f"lore_membership_{seed}",
                "values": [1 if digit in seed_digits else 0 for digit in range(10)],
                "source": "lore_digit_membership",
                "uses_lore": True,
                "lore_seed": seed,
                "model_bits": 3.0 + math.log2(len(LORE_SEEDS)),
            }
        )
    return embeddings


def bucket_single(values: list[int], a: int, b: int, operation: str, modulus: int | None = None):
    x, y = values[a], values[b]
    lo, hi = (x, y) if x <= y else (y, x)
    if operation == "sum_mod":
        return (lo + hi) % int(modulus)
    if operation == "diff_abs_mod":
        return abs(hi - lo) % int(modulus)
    if operation == "cyclic_diff_mod":
        raw = abs(hi - lo) % int(modulus)
        return min(raw, (-raw) % int(modulus))
    if operation == "product_mod":
        return (lo * hi) % int(modulus)
    if operation == "xor_mod":
        return (lo ^ hi) % int(modulus)
    if operation == "sumdiff_tuple":
        return ((lo + hi) % int(modulus), abs(hi - lo) % int(modulus))
    if operation == "sumprod_tuple":
        return ((lo + hi) % int(modulus), (lo * hi) % int(modulus))
    if operation == "min_raw":
        return lo
    if operation == "max_raw":
        return hi
    if operation == "minmax_raw":
        return (lo, hi)
    raise ValueError(operation)


def bucket_affine(values: list[int], a: int, b: int, modulus: int, c0: int, c1: int, c2: int):
    x, y = values[a], values[b]
    lo, hi = (x, y) if x <= y else (y, x)
    return (c0 + c1 * lo + c2 * hi) % modulus


def bucket_two_axis(row_values: list[int], col_values: list[int], a: int, b: int, operation: str, k: int):
    ra, rb = row_values[a], row_values[b]
    ca, cb = col_values[a], col_values[b]
    if operation == "axis_sum_tuple":
        return ((ra + rb) % k, (ca + cb) % k)
    if operation == "axis_product_tuple":
        return ((ra * rb) % k, (ca * cb) % k)
    if operation == "axis_cross_sum_mod":
        return (ra + cb + rb + ca) % k
    if operation == "axis_minmax_tuple":
        rlo, rhi = (ra, rb) if ra <= rb else (rb, ra)
        clo, chi = (ca, cb) if ca <= cb else (cb, ca)
        return (rlo, rhi, clo, chi)
    raise ValueError(operation)


def bucket_signature(buckets: list[Any]) -> tuple[str, ...]:
    return tuple(repr(bucket) for bucket in buckets)


def build_fixed_candidates(targets: list[dict[str, Any]]) -> list[dict[str, Any]]:
    seen: dict[tuple[str, ...], dict[str, Any]] = {}

    def add_candidate(meta: dict[str, Any], buckets: list[Any]) -> None:
        key = bucket_signature(buckets)
        candidate = {**meta, "buckets": buckets}
        previous = seen.get(key)
        if previous is None or candidate["model_bits"] < previous["model_bits"]:
            seen[key] = candidate

    for embedding in fixed_embeddings():
        values = embedding["values"]
        base = {
            "family": "fixed_digit_embedding",
            "embedding_id": embedding["id"],
            "embedding_values": values,
            "embedding_source": embedding["source"],
            "uses_lore": bool(embedding.get("uses_lore", False)),
            "lore_seed": embedding.get("lore_seed"),
            "learned": False,
        }
        for operation in ("sum_mod", "diff_abs_mod", "cyclic_diff_mod", "product_mod", "xor_mod"):
            for modulus in SIMPLE_MODULI:
                buckets = [bucket_single(values, row["a"], row["b"], operation, modulus) for row in targets]
                add_candidate(
                    {
                        **base,
                        "operation": operation,
                        "modulus": modulus,
                        "model_bits": embedding["model_bits"] + math.log2(len(SIMPLE_MODULI)) + 3.0,
                    },
                    buckets,
                )
        for operation in ("sumdiff_tuple", "sumprod_tuple"):
            for modulus in TUPLE_MODULI:
                buckets = [bucket_single(values, row["a"], row["b"], operation, modulus) for row in targets]
                add_candidate(
                    {
                        **base,
                        "operation": operation,
                        "modulus": modulus,
                        "model_bits": embedding["model_bits"] + math.log2(len(TUPLE_MODULI)) + 4.0,
                    },
                    buckets,
                )
        for operation in ("min_raw", "max_raw", "minmax_raw"):
            buckets = [bucket_single(values, row["a"], row["b"], operation) for row in targets]
            add_candidate(
                {
                    **base,
                    "operation": operation,
                    "modulus": None,
                    "model_bits": embedding["model_bits"] + 4.0,
                },
                buckets,
            )
        for modulus in AFFINE_MODULI:
            for c1 in AFFINE_COEFS:
                for c2 in AFFINE_COEFS:
                    for c0 in range(modulus):
                        buckets = [
                            bucket_affine(values, row["a"], row["b"], modulus, c0, c1, c2)
                            for row in targets
                        ]
                        add_candidate(
                            {
                                **base,
                                "operation": "affine_uv_mod",
                                "modulus": modulus,
                                "affine": {"c0": c0, "c1": c1, "c2": c2},
                                "model_bits": embedding["model_bits"]
                                + math.log2(len(AFFINE_MODULI))
                                + math.log2(len(AFFINE_COEFS) ** 2)
                                + math.log2(modulus)
                                + 4.0,
                            },
                            buckets,
                        )

    candidates = list(seen.values())
    candidates.sort(key=lambda item: (item["family"], item["embedding_id"], item["operation"], str(item.get("modulus"))))
    for index, candidate in enumerate(candidates):
        candidate["candidate_id"] = f"fixed_{index:05d}"
    return candidates


def score_candidate(
    candidate: dict[str, Any],
    labels: list[str],
    acceptable_symbols: list[set[str]],
    search_space_bits: float = 0.0,
) -> dict[str, Any]:
    groups: dict[Any, Counter[str]] = defaultdict(Counter)
    for bucket, label in zip(candidate["buckets"], labels):
        groups[bucket][label] += 1
    bucket_to_symbol = {bucket: majority_symbol(counter) for bucket, counter in groups.items()}
    predictions = [bucket_to_symbol[bucket] for bucket in candidate["buckets"]]
    primary_hits = sum(predicted == label for predicted, label in zip(predictions, labels))
    acceptable_hits = sum(predicted in acceptable for predicted, acceptable in zip(predictions, acceptable_symbols))
    errors = len(labels) - primary_hits
    bucket_count = len(groups)
    bucket_bits = bucket_count * SYMBOL_BITS
    exception_bits = errors * (math.log2(len(labels)) + SYMBOL_BITS)
    mdl_cost_bits = search_space_bits + candidate.get("model_bits", 0.0) + bucket_bits + exception_bits
    return {
        "candidate_id": candidate.get("candidate_id"),
        "family": candidate["family"],
        "embedding_id": candidate.get("embedding_id"),
        "embedding_source": candidate.get("embedding_source"),
        "operation": candidate["operation"],
        "modulus": candidate.get("modulus"),
        "affine": candidate.get("affine"),
        "uses_lore": bool(candidate.get("uses_lore", False)),
        "lore_seed": candidate.get("lore_seed"),
        "learned": bool(candidate.get("learned", False)),
        "k": candidate.get("k"),
        "primary_hits": primary_hits,
        "acceptable_hits": acceptable_hits,
        "accuracy": primary_hits / len(labels),
        "acceptable_accuracy": acceptable_hits / len(labels),
        "bucket_count": bucket_count,
        "compact_bucket_limit": COMPACT_BUCKET_LIMIT,
        "lookup_like": bucket_count > COMPACT_BUCKET_LIMIT,
        "model_bits": candidate.get("model_bits", 0.0),
        "bucket_table_bits": bucket_bits,
        "exception_bits": exception_bits,
        "search_space_bits": search_space_bits,
        "mdl_cost_bits": mdl_cost_bits,
        "raw_lookup_bits": RAW_LOOKUP_BITS,
        "mdl_gain_vs_raw_lookup_bits": RAW_LOOKUP_BITS - mdl_cost_bits,
        "lookup_cost_ratio": mdl_cost_bits / RAW_LOOKUP_BITS,
        "embedding_values": candidate.get("embedding_values"),
        "row_values": candidate.get("row_values"),
        "col_values": candidate.get("col_values"),
        "bucket_preview": [repr(bucket) for bucket in candidate["buckets"][:12]],
        "predicted_inventory": dict(sorted(Counter(predictions).items())),
    }


def row_sort_key(row: dict[str, Any]):
    return (
        -row["primary_hits"],
        -row["acceptable_hits"],
        row["lookup_cost_ratio"],
        row["bucket_count"],
        row["model_bits"],
        str(row["candidate_id"]),
    )


def mdl_sort_key(row: dict[str, Any]):
    return (
        row["lookup_cost_ratio"],
        -row["primary_hits"],
        row["bucket_count"],
        str(row["candidate_id"]),
    )


def compact_rows(rows: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    return [row for row in rows if row["bucket_count"] <= COMPACT_BUCKET_LIMIT]


def learned_single_starts(k: int, rng: random.Random) -> list[list[int]]:
    starts = [
        [digit % k for digit in range(10)],
        [(9 - digit) % k for digit in range(10)],
        [((6 if digit == 9 else digit) % k) for digit in range(10)],
    ]
    for seed in LORE_SEEDS:
        starts.append([value % k for value in lore_rank_values(seed)])
    while len(starts) < LEARNED_STARTS:
        starts.append([rng.randrange(k) for _ in range(10)])
    return starts[:LEARNED_STARTS]


def learned_two_axis_starts(k: int, rng: random.Random) -> list[tuple[list[int], list[int]]]:
    starts: list[tuple[list[int], list[int]]] = [
        ([digit % k for digit in range(10)], [(9 - digit) % k for digit in range(10)]),
        ([((6 if digit == 9 else digit) % k) for digit in range(10)], [digit % k for digit in range(10)]),
    ]
    for seed in LORE_SEEDS[:2]:
        ranks = [value % k for value in lore_rank_values(seed)]
        starts.append((ranks, list(reversed(ranks))))
    while len(starts) < LEARNED_STARTS:
        starts.append(([rng.randrange(k) for _ in range(10)], [rng.randrange(k) for _ in range(10)]))
    return starts[:LEARNED_STARTS]


def make_learned_single_candidate(values: list[int], operation: str, k: int, targets: list[dict[str, Any]]) -> dict[str, Any]:
    buckets = [bucket_single(values, row["a"], row["b"], operation, k if operation not in {"minmax_raw"} else None) for row in targets]
    return {
        "family": "learned_single_digit_class",
        "embedding_id": f"learned_single_k{k}",
        "embedding_source": "learned_small_k_digit_class",
        "embedding_values": values[:],
        "operation": operation,
        "modulus": k if operation != "minmax_raw" else None,
        "uses_lore": False,
        "learned": True,
        "k": k,
        "model_bits": 10 * math.log2(k) + math.log2(len(LEARNED_SINGLE_OPS)) + 5.0,
        "buckets": buckets,
    }


def make_learned_two_axis_candidate(
    row_values: list[int],
    col_values: list[int],
    operation: str,
    k: int,
    targets: list[dict[str, Any]],
) -> dict[str, Any]:
    buckets = [bucket_two_axis(row_values, col_values, row["a"], row["b"], operation, k) for row in targets]
    return {
        "family": "learned_row_column_digit_class",
        "embedding_id": f"learned_row_column_k{k}",
        "embedding_source": "learned_small_k_row_column_classes",
        "row_values": row_values[:],
        "col_values": col_values[:],
        "operation": operation,
        "modulus": k,
        "uses_lore": False,
        "learned": True,
        "k": k,
        "model_bits": 20 * math.log2(k) + math.log2(len(LEARNED_TWO_AXIS_OPS)) + 6.0,
        "buckets": buckets,
    }


def better_base(row: dict[str, Any], best: dict[str, Any] | None) -> bool:
    if best is None:
        return True
    return (
        row["primary_hits"],
        row["acceptable_hits"],
        -row["mdl_cost_bits"],
        -row["bucket_count"],
    ) > (
        best["primary_hits"],
        best["acceptable_hits"],
        -best["mdl_cost_bits"],
        -best["bucket_count"],
    )


def hillclimb_single(
    start: list[int],
    operation: str,
    k: int,
    targets: list[dict[str, Any]],
    labels: list[str],
    acceptable_symbols: list[set[str]],
) -> dict[str, Any]:
    values = start[:]
    candidate = make_learned_single_candidate(values, operation, k, targets)
    best = score_candidate(candidate, labels, acceptable_symbols)
    for _sweep in range(LEARNED_SWEEPS):
        improved = False
        for digit in range(10):
            current = values[digit]
            local_best = best
            local_value = current
            for value in range(k):
                if value == current:
                    continue
                trial = values[:]
                trial[digit] = value
                row = score_candidate(make_learned_single_candidate(trial, operation, k, targets), labels, acceptable_symbols)
                if better_base(row, local_best):
                    local_best = row
                    local_value = value
            if local_value != current:
                values[digit] = local_value
                best = local_best
                improved = True
        if not improved:
            break
    final_candidate = make_learned_single_candidate(values, operation, k, targets)
    return score_candidate(final_candidate, labels, acceptable_symbols)


def hillclimb_two_axis(
    start: tuple[list[int], list[int]],
    operation: str,
    k: int,
    targets: list[dict[str, Any]],
    labels: list[str],
    acceptable_symbols: list[set[str]],
) -> dict[str, Any]:
    row_values, col_values = [start[0][:], start[1][:]]
    candidate = make_learned_two_axis_candidate(row_values, col_values, operation, k, targets)
    best = score_candidate(candidate, labels, acceptable_symbols)
    for _sweep in range(LEARNED_SWEEPS):
        improved = False
        for axis in ("row", "col"):
            values = row_values if axis == "row" else col_values
            for digit in range(10):
                current = values[digit]
                local_best = best
                local_value = current
                for value in range(k):
                    if value == current:
                        continue
                    trial_row = row_values[:]
                    trial_col = col_values[:]
                    if axis == "row":
                        trial_row[digit] = value
                    else:
                        trial_col[digit] = value
                    row = score_candidate(
                        make_learned_two_axis_candidate(trial_row, trial_col, operation, k, targets),
                        labels,
                        acceptable_symbols,
                    )
                    if better_base(row, local_best):
                        local_best = row
                        local_value = value
                if local_value != current:
                    values[digit] = local_value
                    best = local_best
                    improved = True
        if not improved:
            break
    final_candidate = make_learned_two_axis_candidate(row_values, col_values, operation, k, targets)
    return score_candidate(final_candidate, labels, acceptable_symbols)


def learned_search(
    targets: list[dict[str, Any]],
    labels: list[str],
    acceptable_symbols: list[set[str]],
    seed: int,
) -> tuple[list[dict[str, Any]], int]:
    rng = random.Random(seed)
    rows: list[dict[str, Any]] = []
    evaluations = 0
    for k in LEARNED_SINGLE_K:
        starts = learned_single_starts(k, rng)
        for operation in LEARNED_SINGLE_OPS:
            best_for_config: dict[str, Any] | None = None
            for start in starts:
                evaluations += 1
                row = hillclimb_single(start, operation, k, targets, labels, acceptable_symbols)
                if better_base(row, best_for_config):
                    best_for_config = row
            assert best_for_config is not None
            best_for_config["candidate_id"] = f"learned_single_k{k}_{operation}"
            rows.append(best_for_config)
    for k in LEARNED_TWO_AXIS_K:
        starts = learned_two_axis_starts(k, rng)
        for operation in LEARNED_TWO_AXIS_OPS:
            best_for_config = None
            for start in starts:
                evaluations += 1
                row = hillclimb_two_axis(start, operation, k, targets, labels, acceptable_symbols)
                if better_base(row, best_for_config):
                    best_for_config = row
            assert best_for_config is not None
            best_for_config["candidate_id"] = f"learned_two_axis_k{k}_{operation}"
            rows.append(best_for_config)
    return rows, evaluations


def finalize_rows(rows: list[dict[str, Any]], search_space_bits: float) -> list[dict[str, Any]]:
    finalized = []
    for row in rows:
        clone = dict(row)
        added = search_space_bits - clone.get("search_space_bits", 0.0)
        clone["search_space_bits"] = search_space_bits
        clone["mdl_cost_bits"] = clone["mdl_cost_bits"] + added
        clone["mdl_gain_vs_raw_lookup_bits"] = RAW_LOOKUP_BITS - clone["mdl_cost_bits"]
        clone["lookup_cost_ratio"] = clone["mdl_cost_bits"] / RAW_LOOKUP_BITS
        finalized.append(clone)
    return finalized


def search_for_labels(
    fixed_candidates: list[dict[str, Any]],
    targets: list[dict[str, Any]],
    labels: list[str],
    acceptable_symbols: list[set[str]],
    seed: int,
    keep_top: bool = True,
) -> dict[str, Any]:
    fixed_rows = [score_candidate(candidate, labels, acceptable_symbols) for candidate in fixed_candidates]
    learned_rows, learned_evaluations = learned_search(targets, labels, acceptable_symbols, seed)
    search_space_size = len(fixed_candidates) + learned_evaluations
    search_space_bits = math.log2(search_space_size)
    all_rows = finalize_rows(fixed_rows + learned_rows, search_space_bits)
    all_rows.sort(key=row_sort_key)
    compact = compact_rows(all_rows)
    compact.sort(key=row_sort_key)
    compressive = sorted(all_rows, key=mdl_sort_key)
    compact_compressive = sorted(compact, key=mdl_sort_key)
    result = {
        "search_space_size": search_space_size,
        "search_space_bits": search_space_bits,
        "learned_evaluations": learned_evaluations,
        "best_all": all_rows[0],
        "best_compact": compact[0] if compact else None,
        "best_compressive": compressive[0],
        "best_compact_compressive": compact_compressive[0] if compact_compressive else None,
    }
    if keep_top:
        result["top_rows"] = all_rows[:TOP_ROWS_OUT]
        result["top_compact_rows"] = compact[:TOP_ROWS_OUT]
    return result


def summarize(values: list[float], observed: float, high_is_good: bool = True) -> dict[str, Any]:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5 if len(values) > 1 else 0.0
    if high_is_good:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {
        "observed": observed,
        "control_mean": mean,
        "control_sd": sd,
        "control_min": min(values),
        "control_max": max(values),
        "z_good_direction": z,
        "p_good_direction": p,
    }


def run_controls(
    fixed_candidates: list[dict[str, Any]],
    targets: list[dict[str, Any]],
    labels: list[str],
    acceptable_symbols: list[set[str]],
    observed: dict[str, Any],
) -> dict[str, Any]:
    rng = random.Random(RANDOM_SEED + 1)
    all_hits: list[int] = []
    compact_hits: list[int] = []
    all_gain: list[float] = []
    compact_gain: list[float] = []
    all_bucket_count: list[int] = []
    compact_bucket_count: list[int] = []
    for trial in range(CONTROL_TRIALS):
        shuffled = labels[:]
        rng.shuffle(shuffled)
        row = search_for_labels(
            fixed_candidates,
            targets,
            shuffled,
            acceptable_symbols,
            RANDOM_SEED + 1000 + trial,
            keep_top=False,
        )
        all_hits.append(row["best_all"]["primary_hits"])
        all_gain.append(row["best_all"]["mdl_gain_vs_raw_lookup_bits"])
        all_bucket_count.append(row["best_all"]["bucket_count"])
        if row["best_compact"] is not None:
            compact_hits.append(row["best_compact"]["primary_hits"])
            compact_gain.append(row["best_compact"]["mdl_gain_vs_raw_lookup_bits"])
            compact_bucket_count.append(row["best_compact"]["bucket_count"])

    return {
        "trials": CONTROL_TRIALS,
        "all_best_primary_hits": summarize(all_hits, observed["best_all"]["primary_hits"], True),
        "all_best_mdl_gain": summarize(all_gain, observed["best_all"]["mdl_gain_vs_raw_lookup_bits"], True),
        "all_best_bucket_count": summarize(all_bucket_count, observed["best_all"]["bucket_count"], False),
        "compact_best_primary_hits": summarize(compact_hits, observed["best_compact"]["primary_hits"], True),
        "compact_best_mdl_gain": summarize(
            compact_gain,
            observed["best_compact"]["mdl_gain_vs_raw_lookup_bits"],
            True,
        ),
        "compact_best_bucket_count": summarize(compact_bucket_count, observed["best_compact"]["bucket_count"], False),
    }


def verdict(observed: dict[str, Any], control: dict[str, Any]) -> str:
    compact = observed["best_compact"]
    best = observed["best_all"]
    compact_hit_p = control["compact_best_primary_hits"]["p_good_direction"]
    compact_mdl_p = control["compact_best_mdl_gain"]["p_good_direction"]
    if (
        compact["primary_hits"] >= 45
        and compact["lookup_cost_ratio"] < 1.0
        and compact_hit_p <= 0.01
        and compact_mdl_p <= 0.01
    ):
        return "candidate_algebraic_generator"
    if compact["lookup_cost_ratio"] < 1.0 and (compact_hit_p <= 0.05 or compact_mdl_p <= 0.05):
        return "weak_algebraic_signal"
    if best["primary_hits"] == PAIR_COUNT and best["bucket_count"] > COMPACT_BUCKET_LIMIT:
        return "lookup_disguise"
    return "rejected_control"


def compact_row_for_json(row: dict[str, Any]) -> dict[str, Any]:
    keys = [
        "candidate_id",
        "family",
        "embedding_id",
        "embedding_source",
        "operation",
        "modulus",
        "affine",
        "uses_lore",
        "lore_seed",
        "learned",
        "k",
        "primary_hits",
        "acceptable_hits",
        "accuracy",
        "acceptable_accuracy",
        "bucket_count",
        "lookup_like",
        "model_bits",
        "bucket_table_bits",
        "exception_bits",
        "search_space_bits",
        "mdl_cost_bits",
        "mdl_gain_vs_raw_lookup_bits",
        "lookup_cost_ratio",
        "embedding_values",
        "row_values",
        "col_values",
        "predicted_inventory",
    ]
    return {key: row.get(key) for key in keys if key in row and row.get(key) is not None}


def report_lines(result: dict[str, Any]) -> list[str]:
    best = result["observed"]["best_all"]
    compact = result["observed"]["best_compact"]
    compressive = result["observed"]["best_compressive"]
    compact_compressive = result["observed"]["best_compact_compressive"]
    control = result["control"]
    lines = [
        "# Algebraic Digit-Composition Search",
        "",
        "Generated by `algebraic_digit_composition_search.py`.",
        "",
        "This pass tests whether the 55 unordered pair cells can be generated",
        "from small digit attributes and simple algebraic operations, followed",
        "by an explicitly charged bucket-to-symbol majority table. It assigns",
        "no plaintext and creates no glossary.",
        "",
        "## Verdict",
        "",
        f"- Verdict: `{result['verdict']}`.",
        f"- Translation delta: `{result['translation_delta']}`.",
        f"- Generator hypothesis delta: `{result['generator_hypothesis_delta']}`.",
        "",
        "## Search Limits",
        "",
        f"- Fixed bucket candidates after dedupe: `{result['search_limits']['fixed_candidate_count']}`.",
        f"- Learned evaluations per observed/control search: `{result['observed']['learned_evaluations']}` starts/configs.",
        f"- Control trials: `{result['control']['trials']}` inventory-preserving label shuffles.",
        f"- Compact diagnostic bucket limit: `{COMPACT_BUCKET_LIMIT}` buckets. This is not a promotion gate; it separates low-table candidates from lookup-like ones.",
        "- Learned models are intentionally small: single digit class k=2..5 and row/column classes k=2..3.",
        "",
        "## Main Numbers",
        "",
        "| Lens | Hits | Acceptable | Buckets | MDL/raw lookup | MDL gain bits | Candidate | Control p(hit) | Control p(MDL) |",
        "|---|---:|---:|---:|---:|---:|---|---:|---:|",
        (
            f"| best all | {best['primary_hits']}/55 | {best['acceptable_hits']}/55 | {best['bucket_count']} | "
            f"{best['lookup_cost_ratio']:.3f} | {best['mdl_gain_vs_raw_lookup_bits']:.2f} | "
            f"`{best['candidate_id']}` | {control['all_best_primary_hits']['p_good_direction']:.4f} | "
            f"{control['all_best_mdl_gain']['p_good_direction']:.4f} |"
        ),
        (
            f"| best compact | {compact['primary_hits']}/55 | {compact['acceptable_hits']}/55 | {compact['bucket_count']} | "
            f"{compact['lookup_cost_ratio']:.3f} | {compact['mdl_gain_vs_raw_lookup_bits']:.2f} | "
            f"`{compact['candidate_id']}` | {control['compact_best_primary_hits']['p_good_direction']:.4f} | "
            f"{control['compact_best_mdl_gain']['p_good_direction']:.4f} |"
        ),
        (
            f"| best MDL | {compressive['primary_hits']}/55 | {compressive['acceptable_hits']}/55 | {compressive['bucket_count']} | "
            f"{compressive['lookup_cost_ratio']:.3f} | {compressive['mdl_gain_vs_raw_lookup_bits']:.2f} | "
            f"`{compressive['candidate_id']}` | n/a | n/a |"
        ),
        (
            f"| best compact MDL | {compact_compressive['primary_hits']}/55 | {compact_compressive['acceptable_hits']}/55 | {compact_compressive['bucket_count']} | "
            f"{compact_compressive['lookup_cost_ratio']:.3f} | {compact_compressive['mdl_gain_vs_raw_lookup_bits']:.2f} | "
            f"`{compact_compressive['candidate_id']}` | n/a | n/a |"
        ),
        "",
        "Raw 55-cell lookup cost is "
        f"`{result['baselines']['raw_55_cell_lookup_bits']:.2f}` bits. "
        "The primary-label inventory lookup is "
        f"`{result['baselines']['primary_inventory_lookup_bits']:.2f}` bits "
        f"({INVENTORY_LOOKUP_NOTE}).",
        "",
        "## Best Candidate Details",
        "",
        "| Candidate | Family | Embedding | Operation | k/mod | Buckets | Hits | MDL/raw | Values |",
        "|---|---|---|---|---:|---:|---:|---:|---|",
    ]
    for row in (best, compact, compressive, compact_compressive):
        values = row.get("embedding_values") or row.get("row_values") or []
        suffix = ""
        if row.get("row_values") is not None:
            suffix = f" / col={row.get('col_values')}"
        lines.append(
            f"| `{row['candidate_id']}` | `{row['family']}` | `{row.get('embedding_id')}` | "
            f"`{row['operation']}` | `{row.get('k') or row.get('modulus')}` | {row['bucket_count']} | "
            f"{row['primary_hits']}/55 | {row['lookup_cost_ratio']:.3f} | `{values}{suffix}` |"
        )
    lines.extend(
        [
            "",
            "## Top Compact Rows",
            "",
            "| Hits | Buckets | MDL/raw | Family | Embedding | Operation | k/mod | Lore | Candidate |",
            "|---:|---:|---:|---|---|---|---:|---|---|",
        ]
    )
    for row in result["observed"]["top_compact_rows"][:20]:
        lines.append(
            f"| {row['primary_hits']}/55 | {row['bucket_count']} | {row['lookup_cost_ratio']:.3f} | "
            f"`{row['family']}` | `{row.get('embedding_id')}` | `{row['operation']}` | "
            f"`{row.get('k') or row.get('modulus')}` | `{row.get('lore_seed') or ''}` | `{row['candidate_id']}` |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
        ]
    )
    if result["verdict"] == "lookup_disguise":
        lines.extend(
            [
                "The search can reproduce the pair table exactly only through a",
                "lookup-like bucketization. The best all-row candidate uses more",
                "than the compact bucket limit and does not beat shuffled-label",
                "controls as a meaningful generator.",
                "",
                "The compact candidates are the relevant formula test. Their best",
                "hit count and MDL gain do not promote an algebraic generator.",
            ]
        )
    elif result["verdict"] == "weak_algebraic_signal":
        lines.extend(
            [
                "A compact algebraic bucketization produced a non-random signal,",
                "but it is still below the bar for an original generator. Treat it",
                "as a weak mechanical clue only.",
            ]
        )
    elif result["verdict"] == "candidate_algebraic_generator":
        lines.extend(
            [
                "A compact algebraic bucketization beat controls and raw lookup.",
                "This would be promotable only as a mechanical generator candidate,",
                "not as translation.",
            ]
        )
    else:
        lines.extend(
            [
                "The algebraic composition families do not beat the shuffled-label",
                "controls in a compact, MDL-positive way. This is a negative result",
                "for the formula-origin search, not evidence of plaintext.",
            ]
        )
    lines.extend(
        [
            "",
            "## Verification Commands",
            "",
            "Executed for this artifact:",
            "",
            "```bash",
            "python analysis/generator_search_20260618/algebraic_digit_composition_search.py",
            "python -c \"import ast, pathlib; p=pathlib.Path('analysis/generator_search_20260618/algebraic_digit_composition_search.py'); compile(p.read_text(), str(p), 'exec', ast.PyCF_ONLY_AST); print('syntax ok')\"",
            "python -c \"import json, pathlib; json.load(open('analysis/generator_search_20260618/algebraic_digit_composition_results.json')); print('json ok')\"",
            "git diff --check -- analysis/generator_search_20260618/algebraic_digit_composition_search.py analysis/generator_search_20260618/algebraic_digit_composition_results.json analysis/generator_search_20260618/algebraic_digit_composition_report.md",
            "```",
            "",
        ]
    )
    return lines


def main() -> int:
    formula = load_json(FORMULA_JSON)
    targets = build_targets(formula)
    labels = [row["primary_symbol"] for row in targets]
    acceptable_symbols = [set(row["acceptable_symbols"]) for row in targets]
    fixed_candidates = build_fixed_candidates(targets)
    observed = search_for_labels(
        fixed_candidates,
        targets,
        labels,
        acceptable_symbols,
        RANDOM_SEED,
        keep_top=True,
    )
    control = run_controls(fixed_candidates, targets, labels, acceptable_symbols, observed)
    result_verdict = verdict(observed, control)
    result = {
        "schema": "algebraic_digit_composition_results.v1",
        "translation_delta": "NONE",
        "generator_hypothesis_delta": "NONE",
        "verdict": result_verdict,
        "conflict_policy": "For conflict cell {19,91}, primary label is the earliest symbol in SIGMA; acceptable hits also count either attested internal symbol.",
        "baselines": {
            "raw_55_cell_lookup_bits": RAW_LOOKUP_BITS,
            "primary_inventory_lookup_bits": inventory_bits(labels),
            "symbol_inventory": dict(sorted(Counter(labels).items())),
        },
        "search_limits": {
            "fixed_candidate_count": len(fixed_candidates),
            "control_trials": CONTROL_TRIALS,
            "compact_bucket_limit": COMPACT_BUCKET_LIMIT,
            "simple_moduli": list(SIMPLE_MODULI),
            "tuple_moduli": list(TUPLE_MODULI),
            "affine_moduli": list(AFFINE_MODULI),
            "affine_coefs": list(AFFINE_COEFS),
            "learned_single_k": list(LEARNED_SINGLE_K),
            "learned_two_axis_k": list(LEARNED_TWO_AXIS_K),
            "learned_starts": LEARNED_STARTS,
            "learned_sweeps": LEARNED_SWEEPS,
            "learned_single_ops": list(LEARNED_SINGLE_OPS),
            "learned_two_axis_ops": list(LEARNED_TWO_AXIS_OPS),
            "lore_seeds": list(LORE_SEEDS),
        },
        "observed": {
            "search_space_size": observed["search_space_size"],
            "search_space_bits": observed["search_space_bits"],
            "learned_evaluations": observed["learned_evaluations"],
            "best_all": compact_row_for_json(observed["best_all"]),
            "best_compact": compact_row_for_json(observed["best_compact"]),
            "best_compressive": compact_row_for_json(observed["best_compressive"]),
            "best_compact_compressive": compact_row_for_json(observed["best_compact_compressive"]),
            "top_rows": [compact_row_for_json(row) for row in observed["top_rows"]],
            "top_compact_rows": [compact_row_for_json(row) for row in observed["top_compact_rows"]],
        },
        "control": control,
    }
    write_json(OUT_JSON, result)
    OUT_MD.write_text("\n".join(report_lines(result)), encoding="utf-8")
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"wrote {OUT_MD.relative_to(ROOT)}")
    print(
        "best_all={}/55 buckets={} compact={}/55 buckets={} p_compact_hit={:.4f} verdict={}".format(
            observed["best_all"]["primary_hits"],
            observed["best_all"]["bucket_count"],
            observed["best_compact"]["primary_hits"],
            observed["best_compact"]["bucket_count"],
            control["compact_best_primary_hits"]["p_good_direction"],
            result_verdict,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
