#!/usr/bin/env python3
"""Bilinear/low-rank pair-table factorization probe.

This closes a technical gap left by the matrix saturation audit: perhaps the
55 unordered pair labels are not generated by discrete digit classes, but by a
continuous low-rank surface over the 10x10 digit grid.

For each symbol, this script builds a binary 10x10 incidence matrix and asks
whether a rank-r SVD approximation predicts held-out pair cells. It assigns no
plaintext and does not promote an opaque model as a formula.
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"

OUT_JSON = HERE / "bilinear_low_rank_pair_factor_results.json"
OUT_MD = HERE / "bilinear_low_rank_pair_factor_report.md"

RANDOM_SEED = 46920260621
CONTROL_TRIALS = 1000
RANKS = (1, 2, 3, 4, 5)
FILL_MODES = ("prior", "zero")
CENTERED = (False, True)


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def natural_pairs() -> list[str]:
    return [f"{a}{b}" for a in range(10) for b in range(a, 10)]


def primary_pair_symbol(pair_table: dict[str, Any], pair: str) -> str:
    row = pair_table[pair]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def pair_digits(pair: str) -> tuple[int, int]:
    return int(pair[0]), int(pair[1])


def rank_approx(matrix: np.ndarray, rank: int) -> np.ndarray:
    u, s, vh = np.linalg.svd(matrix, full_matrices=False)
    return (u[:, :rank] * s[:rank]) @ vh[:rank, :]


def train_symbol_surface(
    pairs: list[str],
    labels: list[str],
    symbols: list[str],
    symbol: str,
    rank: int,
    fill_mode: str,
    centered: bool,
    exclude_index: int | None,
) -> np.ndarray:
    train_indexes = [idx for idx in range(len(pairs)) if idx != exclude_index]
    train_count = len(train_indexes)
    prior = sum(labels[idx] == symbol for idx in train_indexes) / train_count if train_count else 0.0
    fill = prior if fill_mode == "prior" else 0.0
    matrix = np.full((10, 10), fill, dtype=float)
    for idx in train_indexes:
        a, b = pair_digits(pairs[idx])
        value = 1.0 if labels[idx] == symbol else 0.0
        matrix[a, b] = value
        matrix[b, a] = value
    if centered:
        return rank_approx(matrix - prior, rank) + prior
    return rank_approx(matrix, rank)


def predict_scores(
    pairs: list[str],
    labels: list[str],
    symbols: list[str],
    rank: int,
    fill_mode: str,
    centered: bool,
    exclude_index: int | None,
) -> dict[str, list[float]]:
    surfaces = {
        symbol: train_symbol_surface(pairs, labels, symbols, symbol, rank, fill_mode, centered, exclude_index)
        for symbol in symbols
    }
    scores: dict[str, list[float]] = {}
    target_pairs = [pairs[exclude_index]] if exclude_index is not None else pairs
    for pair in target_pairs:
        a, b = pair_digits(pair)
        row = []
        for symbol in symbols:
            surface = surfaces[symbol]
            if a == b:
                row.append(float(surface[a, b]))
            else:
                row.append(float((surface[a, b] + surface[b, a]) / 2.0))
        scores[pair] = row
    return scores


def predict_one(scores: list[float], symbols: list[str]) -> str:
    best = max(range(len(symbols)), key=lambda idx: (scores[idx], -idx))
    return symbols[best]


def macro_recall(labels: list[str], predictions: list[str], symbols: list[str]) -> float:
    recalls = []
    for symbol in symbols:
        total = sum(label == symbol for label in labels)
        if total:
            correct = sum(label == symbol and pred == symbol for label, pred in zip(labels, predictions))
            recalls.append(correct / total)
    return sum(recalls) / len(recalls) if recalls else 0.0


def evaluate_config(
    pairs: list[str],
    labels: list[str],
    symbols: list[str],
    rank: int,
    fill_mode: str,
    centered: bool,
) -> dict[str, Any]:
    full_scores = predict_scores(pairs, labels, symbols, rank, fill_mode, centered, None)
    in_sample_predictions = {pair: predict_one(full_scores[pair], symbols) for pair in pairs}
    in_sample_correct = sum(in_sample_predictions[pair] == labels[idx] for idx, pair in enumerate(pairs))

    loo_predictions = {}
    loo_prediction_list = []
    loo_correct = 0
    for idx, pair in enumerate(pairs):
        scores = predict_scores(pairs, labels, symbols, rank, fill_mode, centered, idx)[pair]
        predicted = predict_one(scores, symbols)
        loo_prediction_list.append(predicted)
        loo_predictions[pair] = {"true": labels[idx], "predicted": predicted, "scores": scores}
        loo_correct += predicted == labels[idx]

    return {
        "rank": rank,
        "fill_mode": fill_mode,
        "centered": centered,
        "in_sample_correct": in_sample_correct,
        "in_sample_accuracy": in_sample_correct / len(pairs),
        "in_sample_macro_recall": macro_recall(labels, [in_sample_predictions[pair] for pair in pairs], symbols),
        "loo_correct": loo_correct,
        "loo_accuracy": loo_correct / len(pairs),
        "loo_macro_recall": macro_recall(labels, loo_prediction_list, symbols),
        "parameter_count": len(symbols) * (2 * 10 * rank + 1),
        "special_predictions": {
            pair: {key: value for key, value in loo_predictions[pair].items() if key != "scores"}
            for pair in ("19", "39", "33", "66", "06", "09", "16", "36", "68", "89")
            if pair in loo_predictions
        },
    }


def prior_baseline(pairs: list[str], labels: list[str]) -> dict[str, Any]:
    symbols = sorted(set(labels))
    correct = 0
    predictions = {}
    prediction_list = []
    for idx, pair in enumerate(pairs):
        train = [label for j, label in enumerate(labels) if j != idx]
        counts = Counter(train)
        predicted = counts.most_common(1)[0][0]
        prediction_list.append(predicted)
        predictions[pair] = {"true": labels[idx], "predicted": predicted}
        correct += predicted == labels[idx]
    return {
        "correct": correct,
        "accuracy": correct / len(pairs),
        "macro_recall": macro_recall(labels, prediction_list, symbols),
        "predictions": predictions,
    }


def endpoint_marginal_baseline(pairs: list[str], labels: list[str], symbols: list[str]) -> dict[str, Any]:
    correct = 0
    predictions = {}
    prediction_list = []
    alpha = 0.75
    for holdout, pair in enumerate(pairs):
        symbol_counts = Counter()
        endpoint_counts = {symbol: Counter() for symbol in symbols}
        for idx, train_pair in enumerate(pairs):
            if idx == holdout:
                continue
            label = labels[idx]
            a, b = train_pair
            symbol_counts[label] += 1
            endpoint_counts[label][a] += 1
            endpoint_counts[label][b] += 1
        a, b = pair
        scores = []
        for symbol in symbols:
            prior = math.log((symbol_counts[symbol] + alpha) / (len(pairs) - 1 + alpha * len(symbols)))
            total = 2 * symbol_counts[symbol]
            score = prior
            score += math.log((endpoint_counts[symbol][a] + alpha) / (total + alpha * 10))
            score += math.log((endpoint_counts[symbol][b] + alpha) / (total + alpha * 10))
            scores.append(score)
        predicted = predict_one(scores, symbols)
        prediction_list.append(predicted)
        predictions[pair] = {"true": labels[holdout], "predicted": predicted}
        correct += predicted == labels[holdout]
    return {
        "correct": correct,
        "accuracy": correct / len(pairs),
        "macro_recall": macro_recall(labels, prediction_list, symbols),
        "predictions": predictions,
    }


def neighbor_label_baseline(pairs: list[str], labels: list[str], symbols: list[str]) -> dict[str, Any]:
    correct = 0
    predictions = {}
    prediction_list = []
    for holdout, pair in enumerate(pairs):
        pair_digit_set = set(pair)
        counts = Counter()
        for idx, train_pair in enumerate(pairs):
            if idx == holdout:
                continue
            if pair_digit_set.intersection(train_pair):
                counts[labels[idx]] += 1
        if not counts:
            counts = Counter(label for idx, label in enumerate(labels) if idx != holdout)
        predicted = counts.most_common(1)[0][0]
        prediction_list.append(predicted)
        predictions[pair] = {"true": labels[holdout], "predicted": predicted}
        correct += predicted == labels[holdout]
    return {
        "correct": correct,
        "accuracy": correct / len(pairs),
        "macro_recall": macro_recall(labels, prediction_list, symbols),
        "predictions": predictions,
    }


def evaluate_all(pairs: list[str], labels: list[str], symbols: list[str]) -> list[dict[str, Any]]:
    rows = []
    for rank in RANKS:
        for fill_mode in FILL_MODES:
            for centered in CENTERED:
                rows.append(evaluate_config(pairs, labels, symbols, rank, fill_mode, centered))
    rows.sort(key=lambda row: (-row["loo_accuracy"], row["parameter_count"], -row["in_sample_accuracy"]))
    return rows


def control_sample(pairs: list[str], labels: list[str], symbols: list[str], observed_best: dict[str, Any]) -> dict[str, Any]:
    rng = random.Random(RANDOM_SEED)
    loo_values = []
    in_sample_values = []
    for _ in range(CONTROL_TRIALS):
        shuffled = labels[:]
        rng.shuffle(shuffled)
        rows = evaluate_all(pairs, shuffled, symbols)
        best = rows[0]
        loo_values.append(best["loo_accuracy"])
        in_sample_values.append(best["in_sample_accuracy"])
    loo_mean = sum(loo_values) / len(loo_values)
    loo_sd = (sum((value - loo_mean) ** 2 for value in loo_values) / (len(loo_values) - 1)) ** 0.5
    in_mean = sum(in_sample_values) / len(in_sample_values)
    in_sd = (sum((value - in_mean) ** 2 for value in in_sample_values) / (len(in_sample_values) - 1)) ** 0.5
    return {
        "trials": CONTROL_TRIALS,
        "best_config_selection": "best loo accuracy over all ranks/fill/centering per trial",
        "loo_accuracy": {
            "observed": observed_best["loo_accuracy"],
            "mean": loo_mean,
            "sd": loo_sd,
            "min": min(loo_values),
            "max": max(loo_values),
            "p_ge_observed": (sum(value >= observed_best["loo_accuracy"] for value in loo_values) + 1) / (len(loo_values) + 1),
        },
        "in_sample_accuracy": {
            "observed": observed_best["in_sample_accuracy"],
            "mean": in_mean,
            "sd": in_sd,
            "min": min(in_sample_values),
            "max": max(in_sample_values),
            "p_ge_observed": (sum(value >= observed_best["in_sample_accuracy"] for value in in_sample_values) + 1)
            / (len(in_sample_values) + 1),
        },
    }


def mdl_context(best: dict[str, Any], symbols: list[str]) -> dict[str, Any]:
    raw_lookup_bits = 55 * math.log2(len(symbols))
    # Lookup with the observed inventory charged as a multinomial index.
    counts = Counter()
    for symbol, count in best["label_inventory"].items():
        counts[symbol] = count
    inventory_lookup_bits = math.lgamma(56) / math.log(2) - sum(math.lgamma(count + 1) / math.log(2) for count in counts.values())
    # Continuous parameters are not a deployable code without quantization. This
    # rough lower-bound charge still shows whether the model is lookup-like.
    lower_bound_parameter_bits = best["parameter_count"] * 8
    return {
        "raw_lookup_bits": raw_lookup_bits,
        "inventory_lookup_bits": inventory_lookup_bits,
        "parameter_count": best["parameter_count"],
        "lower_bound_parameter_bits": lower_bound_parameter_bits,
        "lower_bound_parameter_ratio_to_raw_lookup": lower_bound_parameter_bits / raw_lookup_bits,
        "lower_bound_parameter_ratio_to_inventory_lookup": lower_bound_parameter_bits / inventory_lookup_bits,
        "note": "8 bits/parameter is a deliberately favorable lower bound for continuous factors",
    }


def classify(best: dict[str, Any], control: dict[str, Any], mdl: dict[str, Any]) -> str:
    if best["loo_accuracy"] >= 0.45 and control["loo_accuracy"]["p_ge_observed"] <= 0.01 and mdl[
        "lower_bound_parameter_ratio_to_inventory_lookup"
    ] < 1.0:
        return "candidate_low_rank_pair_formula"
    if control["loo_accuracy"]["p_ge_observed"] <= 0.05 and best["loo_accuracy"] > 0.30:
        return "weak_low_rank_signal_not_formula"
    if best["in_sample_accuracy"] > 0.70 and best["loo_accuracy"] < 0.30:
        return "lookup_disguise_in_sample_only"
    return "rejected_control"


def write_report(result: dict[str, Any]) -> None:
    best = result["best_by_loo"]
    ctrl = result["control"]
    mdl = result["mdl_context"]
    lines = [
        "# Bilinear Low-Rank Pair Factor Search",
        "",
        "Generated by `bilinear_low_rank_pair_factor_search.py`.",
        "",
        "This pass tests whether the 55 pair labels are recoverable from a",
        "continuous low-rank surface over the 10x10 digit grid. It assigns no",
        "plaintext and creates no glossary.",
        "",
        "## Summary",
        "",
        "| Best rank | Fill | Centered | In-sample | LOO | Control mean | Control max | p | MDL lower bound | Verdict |",
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---|",
        f"| {best['rank']} | `{best['fill_mode']}` | `{best['centered']}` | "
        f"{best['in_sample_correct']}/55 ({best['in_sample_accuracy']:.3f}) | "
        f"{best['loo_correct']}/55 ({best['loo_accuracy']:.3f}) | "
        f"{ctrl['loo_accuracy']['mean']:.3f} | {ctrl['loo_accuracy']['max']:.3f} | "
        f"{ctrl['loo_accuracy']['p_ge_observed']:.5f} | "
        f"{mdl['lower_bound_parameter_ratio_to_inventory_lookup']:.3f}x inventory lookup | `{result['verdict']}` |",
        "",
        "## Baselines",
        "",
        "| Baseline | LOO accuracy | Macro recall |",
        "|---|---:|---:|",
    ]
    for name, row in result["baselines"].items():
        lines.append(f"| `{name}` | {row['accuracy']:.3f} | {row['macro_recall']:.3f} |")
    lines.extend(
        [
            "",
        "## Top Configurations",
        "",
        "| Rank | Fill | Centered | In-sample | LOO | Parameters |",
        "|---:|---|---:|---:|---:|---:|",
        ]
    )
    for row in result["rows"][:10]:
        lines.append(
            f"| {row['rank']} | `{row['fill_mode']}` | `{row['centered']}` | "
            f"{row['in_sample_accuracy']:.3f} | {row['loo_accuracy']:.3f} | {row['parameter_count']} |"
        )
    lines.extend(
        [
            "",
            "## Special Pair Leave-One-Out Predictions",
            "",
            "| Pair | True | Predicted |",
            "|---|---|---|",
        ]
    )
    for pair, row in best["special_predictions"].items():
        lines.append(f"| `{pair}` | `{row['true']}` | `{row['predicted']}` |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The relevant evidence is leave-one-pair-out plus inventory-preserving",
            "controls. In-sample reconstruction is not promotable because continuous",
            "factors can become a smooth lookup over a 55-cell table.",
            "",
            "No exact-inventory assignment mode is used by this probe; that path is",
            "diagnostic-only and already covered by endpoint/assignment reports.",
            "",
            f"Translation delta: `{result['translation_delta']}`.",
            "",
        ]
    )
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    pairs = natural_pairs()
    labels = [primary_pair_symbol(formula["pair_table"], pair) for pair in pairs]
    symbols = sorted(set(labels))
    rows = evaluate_all(pairs, labels, symbols)
    inventory = dict(Counter(labels))
    for row in rows:
        row["label_inventory"] = inventory
    best = rows[0]
    control = control_sample(pairs, labels, symbols, best)
    mdl = mdl_context(best, symbols)
    baselines = {
        "symbol_frequency_top": prior_baseline(pairs, labels),
        "endpoint_marginal": endpoint_marginal_baseline(pairs, labels, symbols),
        "neighbor_label": neighbor_label_baseline(pairs, labels, symbols),
    }
    result = {
        "schema": "bilinear_low_rank_pair_factor_results.v1",
        "source": str(FORMULA_JSON.relative_to(ROOT)),
        "random_seed": RANDOM_SEED,
        "control_trials": CONTROL_TRIALS,
        "ranks": list(RANKS),
        "fill_modes": list(FILL_MODES),
        "centered_variants": list(CENTERED),
        "baselines": baselines,
        "best_by_loo": best,
        "rows": rows,
        "control": control,
        "mdl_context": mdl,
        "verdict": classify(best, control, mdl),
        "translation_delta": "NONE",
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(f"verdict={result['verdict']} best_loo={best['loo_accuracy']:.3f} p={control['loo_accuracy']['p_ge_observed']:.5f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
