#!/usr/bin/env python3
"""Secondary rule search for mixed `6 <-> 9` quotient orbits.

The quotient pass found that swapping digits 6 and 9 gives a small lossless
compression of the pair table: 46 orbits and four mixed two-cell orbits.
This follow-up asks whether those mixed orbits and their 6-vs-9 orientation
can be generated by a compact secondary rule instead of being stored as a
mini lookup.

Mechanical only. No plaintext or translation is promoted.
"""

from __future__ import annotations

import itertools
import json
import math
import random
from collections import Counter
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"
ORBIT_JSON = HERE / "digit_orbit_quotient_results.json"

OUT_JSON = HERE / "digit_orbit_exception_rule_results.json"
OUT_MD = HERE / "digit_orbit_exception_rule_report.md"

SIGMA = list("*ABCEFILNORSTV")
RANDOM_SEED = 46920260619
CONTROL_TRIALS = 2000


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def primary_pair_symbol(pair_table: dict, pair: str) -> str:
    row = pair_table[pair]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def log2_comb(n: int, k: int) -> float:
    if k < 0 or k > n:
        return float("inf")
    return math.log2(math.comb(n, k)) if 0 < k < n else 0.0


def build_orbit_rows(pair_table: dict) -> list[dict]:
    rows = []
    for other in range(9):
        if other < 6:
            pair6 = f"{other}6"
            pair9 = f"{other}9"
        elif other == 6:
            pair6 = "66"
            pair9 = "99"
        else:
            pair6 = f"6{other}"
            pair9 = f"{other}9"
        label6 = primary_pair_symbol(pair_table, pair6)
        label9 = primary_pair_symbol(pair_table, pair9)
        ordered = sorted([label6, label9], key=SIGMA.index)
        rows.append(
            {
                "other_digit": other,
                "pair6": pair6,
                "pair9": pair9,
                "label6": label6,
                "label9": label9,
                "mixed": label6 != label9,
                "label_pair_sorted": ordered,
                "side6_is_low_symbol": label6 == ordered[0],
                "sum_with_6": other + 6,
                "sum_with_9": other + 9,
                "abs_from_469_digits": min(abs(other - d) for d in [4, 6, 9]),
                "in_469": other in {4, 6, 9},
                "in_39": other in {3, 9},
                "in_19": other in {1, 9},
                "in_33_66": other in {3, 6},
            }
        )
    return rows


def digit_pair_labels(pair_table: dict) -> dict[int, dict]:
    labels = {}
    for digit in range(10):
        diag = f"{digit}{digit}"
        incident = []
        for other in range(10):
            a, b = sorted([digit, other])
            incident.append(primary_pair_symbol(pair_table, f"{a}{b}"))
        counts = Counter(incident)
        top_label, top_count = sorted(counts.items(), key=lambda item: (-item[1], SIGMA.index(item[0])))[0]
        labels[digit] = {
            "diag_label": primary_pair_symbol(pair_table, diag),
            "top_label": top_label,
            "top_count": top_count,
            "distinct_count": len(counts),
            "e_count": counts["E"],
            "i_count": counts["I"],
            "n_count": counts["N"],
            "a_count": counts["A"],
        }
    return labels


def enrich_rows(rows: list[dict], pair_table: dict) -> list[dict]:
    labels = digit_pair_labels(pair_table)
    out = []
    for row in rows:
        sig = labels[row["other_digit"]]
        out.append(
            {
                **row,
                **sig,
                "parity": row["other_digit"] % 2,
                "mod3": row["other_digit"] % 3,
                "mod4": row["other_digit"] % 4,
                "low_0_3": row["other_digit"] <= 3,
                "high_6_8": row["other_digit"] >= 6,
                "edge_digit": row["other_digit"] in {0, 8},
                "square_digit": row["other_digit"] in {0, 1, 4},
                "prime_digit": row["other_digit"] in {2, 3, 5, 7},
            }
        )
    return out


def predicate_library(rows: list[dict]) -> list[dict]:
    predicates = []

    def add(name: str, family: str, cost: float, fn):
        mask = [bool(fn(row)) for row in rows]
        if any(mask) and not all(mask):
            predicates.append({"name": name, "family": family, "cost": cost, "mask": mask})

    for digit in range(9):
        add(f"x_eq_{digit}", "exact_digit", 2.8, lambda row, d=digit: row["other_digit"] == d)
        add(f"x_le_{digit}", "range", 1.7, lambda row, d=digit: row["other_digit"] <= d)
        add(f"x_ge_{digit}", "range", 1.7, lambda row, d=digit: row["other_digit"] >= d)
    for modulus in range(2, 6):
        for residue in range(modulus):
            add(f"x_mod_{modulus}_{residue}", "modular", 2.0, lambda row, m=modulus, r=residue: row["other_digit"] % m == r)
    for field in ["diag_label", "top_label"]:
        values = sorted({row[field] for row in rows}, key=SIGMA.index)
        for value in values:
            add(f"{field}_eq_{value}", "digit_signature", 2.3, lambda row, f=field, v=value: row[f] == v)
        for size in range(2, min(4, len(values)) + 1):
            for subset in itertools.combinations(values, size):
                joined = "".join(subset)
                add(f"{field}_in_{joined}", "digit_signature_set", 2.8 + 0.3 * size, lambda row, f=field, s=set(subset): row[f] in s)
    for field in ["top_count", "distinct_count", "e_count", "i_count", "n_count", "a_count", "sum_with_6", "sum_with_9", "abs_from_469_digits"]:
        values = sorted({row[field] for row in rows})
        for value in values:
            add(f"{field}_eq_{value}", "numeric_signature", 2.6, lambda row, f=field, v=value: row[f] == v)
            add(f"{field}_le_{value}", "numeric_signature", 2.4, lambda row, f=field, v=value: row[f] <= v)
            add(f"{field}_ge_{value}", "numeric_signature", 2.4, lambda row, f=field, v=value: row[f] >= v)
    for field in ["in_469", "in_39", "in_19", "in_33_66", "low_0_3", "high_6_8", "edge_digit", "square_digit", "prime_digit"]:
        add(field, "lore_or_shape_set", 1.8, lambda row, f=field: row[f])
    # Pairwise combinations among cheap predicates.
    base = [p for p in predicates if p["cost"] <= 2.4]
    for left_idx, left in enumerate(base):
        for right in base[left_idx + 1 :]:
            and_mask = [a and b for a, b in zip(left["mask"], right["mask"])]
            or_mask = [a or b for a, b in zip(left["mask"], right["mask"])]
            if any(and_mask) and not all(and_mask):
                predicates.append(
                    {
                        "name": f"and({left['name']},{right['name']})",
                        "family": "compound_and",
                        "cost": left["cost"] + right["cost"] + 0.8,
                        "mask": and_mask,
                    }
                )
            if any(or_mask) and not all(or_mask):
                predicates.append(
                    {
                        "name": f"or({left['name']},{right['name']})",
                        "family": "compound_or",
                        "cost": left["cost"] + right["cost"] + 0.8,
                        "mask": or_mask,
                    }
                )
    dedup = {}
    for predicate in predicates:
        key = tuple(predicate["mask"])
        old = dedup.get(key)
        if old is None or predicate["cost"] < old["cost"]:
            dedup[key] = predicate
    return sorted(dedup.values(), key=lambda item: (item["cost"], item["name"]))


def score_predicate(predicate: dict, target: list[bool]) -> dict:
    mask = predicate["mask"]
    tp = sum(m and t for m, t in zip(mask, target))
    fp = sum(m and not t for m, t in zip(mask, target))
    fn = sum((not m) and t for m, t in zip(mask, target))
    tn = sum((not m) and (not t) for m, t in zip(mask, target))
    return {
        **predicate,
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
        "correct": tp + tn,
        "exact": fp == 0 and fn == 0,
        "predicted_true_count": sum(mask),
    }


def orientation_rules(rows: list[dict]) -> list[dict]:
    mixed_rows = [row for row in rows if row["mixed"]]
    rules = []

    def add(name: str, family: str, cost: float, fn):
        predictions = [bool(fn(row)) for row in mixed_rows]
        correct = sum(pred == row["side6_is_low_symbol"] for pred, row in zip(predictions, mixed_rows))
        rules.append({"name": name, "family": family, "cost": cost, "correct": correct, "total": len(mixed_rows), "predictions": predictions})

    add("side6_low_if_x_even", "parity", 1.0, lambda row: row["other_digit"] % 2 == 0)
    add("side6_low_if_x_odd", "parity", 1.0, lambda row: row["other_digit"] % 2 == 1)
    add("side6_low_if_x_lt_2", "range", 1.5, lambda row: row["other_digit"] < 2)
    add("side6_low_if_x_gt_3", "range", 1.5, lambda row: row["other_digit"] > 3)
    add("side6_low_if_in_469", "lore", 1.8, lambda row: row["in_469"])
    add("side6_low_if_diag_a", "signature", 2.0, lambda row: row["diag_label"] == "A")
    add("side6_low_if_top_e", "signature", 2.0, lambda row: row["top_label"] == "E")
    rules.sort(key=lambda item: (-item["correct"], item["cost"], item["name"]))
    return rules


def summarize_control(values: list[float], observed: float) -> dict:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5
    return {
        "observed": observed,
        "mean": mean,
        "sd": sd,
        "min": min(values),
        "max": max(values),
        "p_good_direction": (sum(value >= observed for value in values) + 1) / (len(values) + 1),
    }


def controls(predicates: list[dict], observed_mixed_score: dict, observed_orientation: dict, mixed_count: int, orientation_true_count: int) -> dict:
    rng = random.Random(RANDOM_SEED + 1)
    best_correct = []
    best_exact_cost = []
    orientation_correct = []
    for _ in range(CONTROL_TRIALS):
        true_indices = set(rng.sample(range(9), mixed_count))
        target = [idx in true_indices for idx in range(9)]
        rows = [score_predicate(predicate, target) for predicate in predicates]
        best_correct.append(max(row["correct"] for row in rows))
        exact_costs = [row["cost"] for row in rows if row["exact"]]
        best_exact_cost.append(min(exact_costs) if exact_costs else 99.0)
        orientation_bits = [idx < orientation_true_count for idx in range(mixed_count)]
        rng.shuffle(orientation_bits)
        # Same fixed parity-like rule family over a random ordering has this
        # upper-bound chance to fit the shuffled side bits.
        candidates = [
            [idx % 2 == 0 for idx in range(mixed_count)],
            [idx % 2 == 1 for idx in range(mixed_count)],
            [idx < 2 for idx in range(mixed_count)],
            [idx >= 2 for idx in range(mixed_count)],
        ]
        orientation_correct.append(max(sum(a == b for a, b in zip(candidate, orientation_bits)) for candidate in candidates))
    return {
        "trials": CONTROL_TRIALS,
        "mixed_rule_correct": summarize_control(best_correct, observed_mixed_score["correct"]),
        "mixed_rule_exact_cost": {
            **summarize_control([-value for value in best_exact_cost], -observed_mixed_score["cost"]),
            "observed_cost": observed_mixed_score["cost"],
            "control_min_cost": min(best_exact_cost),
            "control_mean_cost": sum(best_exact_cost) / len(best_exact_cost),
        },
        "orientation_rule_correct": summarize_control(orientation_correct, observed_orientation["correct"]),
    }


def mdl_estimate(orbit_result: dict, mixed_rule: dict, orientation_rule: dict) -> dict:
    raw_lookup_bits = orbit_result["lookup_cost_bits"]
    group_bits = math.log2(45) + math.log2(8)
    uniform_orbit_count = orbit_result["orbit_count"] - orbit_result["mixed_orbit_count"]
    mixed_count = orbit_result["mixed_orbit_count"]
    uniform_bits = uniform_orbit_count * math.log2(len(SIGMA))
    unordered_pair_bits = mixed_count * math.log2(math.comb(len(SIGMA), 2))
    model_bits = group_bits + uniform_bits + unordered_pair_bits + mixed_rule["cost"] + orientation_rule["cost"]
    return {
        "raw_lookup_bits": raw_lookup_bits,
        "model_bits": model_bits,
        "gain_vs_raw_lookup_bits": raw_lookup_bits - model_bits,
        "lookup_cost_ratio": model_bits / raw_lookup_bits,
        "components": {
            "group_bits": group_bits,
            "uniform_orbit_label_bits": uniform_bits,
            "mixed_unordered_label_pair_bits": unordered_pair_bits,
            "mixed_rule_cost_bits": mixed_rule["cost"],
            "orientation_rule_cost_bits": orientation_rule["cost"],
        },
    }


def verdict(best_mixed: dict, best_orientation: dict, mdl: dict, ctrl: dict) -> str:
    if (
        best_mixed["exact"]
        and best_orientation["correct"] == best_orientation["total"]
        and mdl["gain_vs_raw_lookup_bits"] > 0
        and ctrl["mixed_rule_exact_cost"]["p_good_direction"] <= 0.01
        and ctrl["orientation_rule_correct"]["p_good_direction"] <= 0.05
    ):
        return "candidate_secondary_orbit_exception_rule"
    if best_mixed["exact"] and best_orientation["correct"] == best_orientation["total"] and mdl["gain_vs_raw_lookup_bits"] > 0:
        if (
            ctrl["mixed_rule_exact_cost"]["p_good_direction"] <= 0.20
            and ctrl["orientation_rule_correct"]["p_good_direction"] <= 0.20
        ):
            return "weak_secondary_orbit_exception_rule"
        return "not_promoted_exception_microfit_control_failed"
    return "not_promoted_exception_microfit"


def write_report(result: dict) -> None:
    mixed = result["best_mixed_rule"]
    orient = result["best_orientation_rule"]
    mdl = result["mdl"]
    ctrl = result["controls"]
    lines = [
        "# Digit Orbit Exception Rule Search",
        "",
        "Generated by `digit_orbit_exception_rule_search.py`.",
        "",
        "This pass tests whether the four mixed `6 <-> 9` quotient orbits can",
        "be generated by a compact secondary rule. It is mechanical only and",
        "assigns no plaintext.",
        "",
        "## Summary",
        "",
        "| Mixed selector | Exact | Cost | Orientation rule | Orientation hits | MDL/lookup | Gain bits | Control p(selector cost) | Control p(orientation) | Verdict |",
        "|---|---:|---:|---|---:|---:|---:|---:|---:|---|",
        f"| `{mixed['name']}` | {mixed['exact']} | {mixed['cost']:.1f} | `{orient['name']}` | {orient['correct']}/{orient['total']} | {mdl['lookup_cost_ratio']:.3f} | {mdl['gain_vs_raw_lookup_bits']:.1f} | {ctrl['mixed_rule_exact_cost']['p_good_direction']:.4f} | {ctrl['orientation_rule_correct']['p_good_direction']:.4f} | `{result['verdict']}` |",
        "",
        "## Orbit Rows",
        "",
        "| x | pair6 | label6 | pair9 | label9 | Mixed | side6 low? |",
        "|---:|---|---|---|---|---|---|",
    ]
    for row in result["orbit_rows"]:
        lines.append(
            f"| {row['other_digit']} | `{row['pair6']}` | `{row['label6']}` | `{row['pair9']}` | `{row['label9']}` | `{row['mixed']}` | `{row['side6_is_low_symbol']}` |"
        )
    lines.extend(
        [
            "",
            "## Top Mixed-Selector Rules",
            "",
            "| Rule | Family | Cost | Correct | TP | FP | FN | Exact |",
            "|---|---|---:|---:|---:|---:|---:|---|",
        ]
    )
    for row in result["top_mixed_rules"][:20]:
        lines.append(
            f"| `{row['name']}` | `{row['family']}` | {row['cost']:.1f} | {row['correct']}/9 | {row['tp']} | {row['fp']} | {row['fn']} | `{row['exact']}` |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The side orientation is simple: among mixed orbits, even `x` puts the",
            "lower symbol on the `x6` cell and odd `x` puts it on `x9`. The hard",
            "part is selecting exactly which four `x` values are mixed. The best",
            "selector is exact only because it is effectively a compound signature",
            "over nine cases. Controls find exact low-cost selectors and perfect",
            "orientation rules often enough that this remains a descriptive",
            "microfit, not the original matrix formula.",
            "",
        ]
    )
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    orbit = load_json(ORBIT_JSON)
    rows = enrich_rows(build_orbit_rows(formula["pair_table"]), formula["pair_table"])
    predicates = predicate_library(rows)
    mixed_target = [row["mixed"] for row in rows]
    mixed_scores = [score_predicate(predicate, mixed_target) for predicate in predicates]
    mixed_scores.sort(key=lambda item: (-int(item["exact"]), -item["correct"], item["cost"], item["name"]))
    orientation = orientation_rules(rows)
    best_mixed = mixed_scores[0]
    best_orientation = orientation[0]
    mdl = mdl_estimate(orbit["swap_6_9"], best_mixed, best_orientation)
    ctrl = controls(predicates, best_mixed, best_orientation, sum(mixed_target), sum(row["side6_is_low_symbol"] for row in rows if row["mixed"]))
    result = {
        "schema": "digit_orbit_exception_rule_results.v1",
        "translation_delta": "NONE",
        "new_plaintext": False,
        "orbit_source": str(ORBIT_JSON.relative_to(ROOT)),
        "orbit_rows": rows,
        "best_mixed_rule": best_mixed,
        "best_orientation_rule": best_orientation,
        "top_mixed_rules": mixed_scores[:80],
        "top_orientation_rules": orientation,
        "mdl": mdl,
        "controls": ctrl,
        "verdict": verdict(best_mixed, best_orientation, mdl, ctrl),
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(HERE)}")
    print(f"wrote {OUT_MD.relative_to(HERE)}")
    print(
        "mixed_rule={rule} orientation={orient} gain={gain:.1f} verdict={verdict}".format(
            rule=best_mixed["name"],
            orient=best_orientation["name"],
            gain=mdl["gain_vs_raw_lookup_bits"],
            verdict=result["verdict"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
