#!/usr/bin/env python3
"""High-block blocker origin search for the priority E layer.

The E predicate search found that the high digit set {4,5,7,8} is almost an
E-fill: six of ten cells are E. The priority-mask follow-up then hand-claimed
four blockers: 45=F, 55=V, 77=N, 88=A.

This pass asks a narrower question: are those blockers generated by a compact
mini-block drawing/order rule, or are they still post-hoc exceptions?

Mechanical only. No plaintext is inferred.
"""

from __future__ import annotations

import itertools
import json
import math
import random
from collections import Counter
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"
OUT_JSON = HERE / "high_block_blocker_origin_results.json"
OUT_MD = HERE / "high_block_blocker_origin_report.md"

RANDOM_SEED = 46920260619
CONTROL_TRIALS = 20000
HIGH_DIGITS = (4, 5, 7, 8)


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def pair(a: int, b: int) -> str:
    x, y = sorted((a, b))
    return f"{x}{y}"


def primary_pair_symbol(pair_table: dict[str, Any], cell: str) -> str:
    row = pair_table[cell]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def cells_for_digits(digits: tuple[int, ...]) -> list[str]:
    return [pair(a, b) for index, a in enumerate(digits) for b in digits[index:]]


def score_set(predicted: set[str], target: set[str]) -> dict[str, float | int]:
    tp = len(predicted & target)
    fp = len(predicted - target)
    fn = len(target - predicted)
    precision = tp / (tp + fp) if tp + fp else 0.0
    recall = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * precision * recall / (precision + recall) if precision + recall else 0.0
    return {"tp": tp, "fp": fp, "fn": fn, "precision": precision, "recall": recall, "f1": f1}


def suffix_diagonal_edge_rule(order: tuple[int, ...], prefix_len: int = 2) -> set[str]:
    """First ordered edge plus diagonals of all later/sink digits.

    For order 4,5,7,8 this gives 45 plus 55/77/88: exactly the observed
    priority blockers. This is intentionally charged and controlled as a
    searched mini-block rule, not accepted by construction.
    """

    first_edge = {pair(order[0], order[1])}
    suffix_diags = {pair(digit, digit) for digit in order[prefix_len - 1 :]}
    return first_edge | suffix_diags


def rule_candidates(digits: tuple[int, ...]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    digit_set = tuple(sorted(digits))

    def add(rule_id: str, selected: set[str], cost_bits: float, detail: dict[str, Any]) -> None:
        rows.append(
            {
                "rule_id": rule_id,
                "selected": sorted(selected),
                "selected_count": len(selected),
                "cost_bits": cost_bits,
                "detail": detail,
            }
        )

    cells = set(cells_for_digits(digit_set))
    all_diags = {pair(digit, digit) for digit in digit_set}
    all_edges = cells - all_diags
    ordered = list(itertools.permutations(digit_set))

    add("all_diagonals", all_diags, 2.0, {"family": "diagonal"})
    add("all_edges", all_edges, 2.0, {"family": "edge"})
    for keep in range(1, len(digit_set)):
        add(
            f"diagonal_suffix_natural_{keep}",
            {pair(digit, digit) for digit in digit_set[keep:]},
            2.0 + math.log2(len(digit_set)),
            {"family": "diagonal_suffix", "order": list(digit_set), "start": keep},
        )
        add(
            f"diagonal_prefix_natural_{keep}",
            {pair(digit, digit) for digit in digit_set[:keep]},
            2.0 + math.log2(len(digit_set)),
            {"family": "diagonal_prefix", "order": list(digit_set), "end": keep},
        )

    for order in ordered:
        order_id = "".join(str(digit) for digit in order)
        path_edges = {pair(order[idx], order[idx + 1]) for idx in range(len(order) - 1)}
        add(
            f"path_edges_{order_id}",
            path_edges,
            2.0 + math.log2(len(ordered)),
            {"family": "path_edges", "order": list(order)},
        )
        add(
            f"first_edge_plus_suffix_diags_{order_id}",
            suffix_diagonal_edge_rule(order),
            2.0 + math.log2(len(ordered)),
            {"family": "first_edge_plus_suffix_diags", "order": list(order)},
        )
        add(
            f"last_edge_plus_prefix_diags_{order_id}",
            {pair(order[-2], order[-1])} | {pair(digit, digit) for digit in order[:-1]},
            2.0 + math.log2(len(ordered)),
            {"family": "last_edge_plus_prefix_diags", "order": list(order)},
        )
        add(
            f"path_edges_plus_sink_diag_{order_id}",
            path_edges | {pair(order[-1], order[-1])},
            2.0 + math.log2(len(ordered)),
            {"family": "path_edges_plus_sink_diag", "order": list(order)},
        )
        add(
            f"path_edges_plus_source_diag_{order_id}",
            path_edges | {pair(order[0], order[0])},
            2.0 + math.log2(len(ordered)),
            {"family": "path_edges_plus_source_diag", "order": list(order)},
        )

    unique = {}
    for row in rows:
        key = tuple(row["selected"])
        if key not in unique or row["cost_bits"] < unique[key]["cost_bits"]:
            unique[key] = row
    return sorted(unique.values(), key=lambda row: (row["cost_bits"], row["rule_id"]))


def best_rule_for_target(digits: tuple[int, ...], target: set[str]) -> dict[str, Any]:
    rows = []
    for row in rule_candidates(digits):
        score = score_set(set(row["selected"]), target)
        exception_bits = (score["fp"] + score["fn"]) * math.log2(len(cells_for_digits(digits)))
        model_bits = row["cost_bits"] + exception_bits
        rows.append({**row, **score, "exception_bits": exception_bits, "model_bits": model_bits})
    rows.sort(key=lambda row: (-row["f1"], row["model_bits"], row["cost_bits"], row["rule_id"]))
    return rows[0]


def observed_targets(pair_table: dict[str, Any], digits: tuple[int, ...]) -> dict[str, Any]:
    cells = cells_for_digits(tuple(sorted(digits)))
    labels = {cell: primary_pair_symbol(pair_table, cell) for cell in cells}
    blockers = {cell for cell, label in labels.items() if label != "E"}
    return {
        "digits": list(sorted(digits)),
        "cells": cells,
        "labels": labels,
        "blockers": sorted(blockers),
        "e_cells": sorted(cell for cell, label in labels.items() if label == "E"),
    }


def conditional_controls(digits: tuple[int, ...], target_size: int, observed_best: dict[str, Any]) -> dict[str, Any]:
    rng = random.Random(RANDOM_SEED)
    cells = cells_for_digits(tuple(sorted(digits)))
    f1_values = []
    exact_count = 0
    model_bits = []
    for _trial in range(CONTROL_TRIALS):
        target = set(rng.sample(cells, target_size))
        best = best_rule_for_target(digits, target)
        f1_values.append(best["f1"])
        model_bits.append(best["model_bits"])
        exact_count += int(best["f1"] >= 1.0)
    return {
        "trials": CONTROL_TRIALS,
        "target_size": target_size,
        "mean_best_f1": sum(f1_values) / len(f1_values),
        "p_best_f1_ge": (sum(value >= observed_best["f1"] for value in f1_values) + 1) / (len(f1_values) + 1),
        "p_exact": (exact_count + 1) / (len(f1_values) + 1),
        "mean_model_bits": sum(model_bits) / len(model_bits),
        "p_model_bits_le": (sum(value <= observed_best["model_bits"] for value in model_bits) + 1) / (len(model_bits) + 1),
    }


def cell_coords(digits: tuple[int, ...]) -> dict[str, tuple[int, int]]:
    ordered = tuple(sorted(digits))
    return {
        pair(a, b): (row, col)
        for row, a in enumerate(ordered)
        for col, b in enumerate(ordered[row:], start=row)
    }


def adjacent_cells(cell_a: str, cell_b: str, coords: dict[str, tuple[int, int]]) -> bool:
    ra, ca = coords[cell_a]
    rb, cb = coords[cell_b]
    return max(abs(ra - rb), abs(ca - cb)) == 1


def connected_paths(digits: tuple[int, ...], length: int = 4) -> list[list[str]]:
    cells = cells_for_digits(tuple(sorted(digits)))
    coords = cell_coords(digits)
    paths: list[list[str]] = []

    def walk(path: list[str]) -> None:
        if len(path) == length:
            paths.append(path[:])
            return
        for candidate in cells:
            if candidate in path:
                continue
            if adjacent_cells(path[-1], candidate, coords):
                path.append(candidate)
                walk(path)
                path.pop()

    for start in cells:
        walk([start])
    return paths


def stroke_path_analysis(target: dict[str, Any]) -> dict[str, Any]:
    digits = tuple(target["digits"])
    blockers = set(target["blockers"])
    paths = connected_paths(digits, len(blockers))
    path_sets = {tuple(sorted(path)) for path in paths}
    exact_paths = [path for path in paths if set(path) == blockers]
    all_same_size = list(itertools.combinations(target["cells"], len(blockers)))
    connected_subset_count = sum(1 for subset in all_same_size if tuple(sorted(subset)) in path_sets)
    label_sequences = [
        "".join(target["labels"][cell] for cell in path)
        for path in exact_paths
    ]
    return {
        "path_count": len(paths),
        "unique_path_set_count": len(path_sets),
        "same_size_subset_count": len(all_same_size),
        "connected_subset_count": connected_subset_count,
        "connected_subset_fraction": connected_subset_count / len(all_same_size),
        "p_connected_subset": (connected_subset_count + 1) / (len(all_same_size) + 1),
        "exact_path_count": len(exact_paths),
        "exact_paths": exact_paths[:20],
        "label_sequences": sorted(set(label_sequences)),
        "label_sequence_cost_bits_if_literal": math.log2(math.factorial(len(blockers))) if blockers else 0.0,
    }


def all_digit_set_scan(pair_table: dict[str, Any], observed_best: dict[str, Any]) -> dict[str, Any]:
    rows = []
    for digits in itertools.combinations(range(10), 4):
        target = observed_targets(pair_table, digits)
        best = best_rule_for_target(digits, set(target["blockers"]))
        rows.append(
            {
                "digits": list(digits),
                "blocker_count": len(target["blockers"]),
                "blockers": target["blockers"],
                "e_count": len(target["e_cells"]),
                "best_rule_id": best["rule_id"],
                "best_f1": best["f1"],
                "best_model_bits": best["model_bits"],
                "exact": best["f1"] >= 1.0,
            }
        )
    same_size = [row for row in rows if row["blocker_count"] == len(observed_best["target_blockers"])]
    exact_same_size = sum(1 for row in same_size if row["exact"])
    exact_all = sum(1 for row in rows if row["exact"])
    return {
        "rows": sorted(rows, key=lambda row: (-row["best_f1"], row["best_model_bits"], row["digits"])),
        "all_set_count": len(rows),
        "all_exact_count": exact_all,
        "all_exact_fraction": exact_all / len(rows),
        "all_p_exact": (exact_all + 1) / (len(rows) + 1),
        "same_size_count": len(same_size),
        "same_size_exact_count": exact_same_size,
        "same_size_exact_fraction": exact_same_size / len(same_size) if same_size else 0.0,
        "same_size_p_exact": (exact_same_size + 1) / (len(same_size) + 1) if same_size else 1.0,
    }


def classify(observed_best: dict[str, Any], conditional: dict[str, Any], digit_scan: dict[str, Any]) -> str:
    if observed_best["f1"] >= 1.0 and conditional["p_exact"] <= 0.05 and digit_scan["same_size_p_exact"] <= 0.05:
        return "weak_high_block_blocker_signal"
    return "high_block_blocker_not_promoted"


def write_report(result: dict[str, Any]) -> None:
    best = result["observed_best"]
    lines = [
        "# High-Block Blocker Origin Search",
        "",
        "Generated by `high_block_blocker_origin_search.py`.",
        "",
        "This asks whether the priority E-layer blockers inside the high block",
        "`{4,5,7,8}` have a compact mini-block drawing/order rule.",
        "",
        "## Summary",
        "",
        "| High digits | Target blockers | Best rule | F1 | Model bits | Conditional p exact | Digit-set p exact | Verdict |",
        "|---|---|---|---:|---:|---:|---:|---|",
        f"| `{''.join(map(str, result['target']['digits']))}` | `{','.join(result['target']['blockers'])}` | `{best['rule_id']}` | {best['f1']:.3f} | {best['model_bits']:.2f} | {result['conditional_controls']['p_exact']:.5f} | {result['digit_set_scan']['same_size_p_exact']:.5f} | `{result['verdict']}` |",
        "",
        "## Observed Mini-Block",
        "",
        "| Cell | Symbol | Class |",
        "|---|---|---|",
    ]
    for cell in result["target"]["cells"]:
        label = result["target"]["labels"][cell]
        klass = "blocker" if cell in result["target"]["blockers"] else "E"
        lines.append(f"| `{cell}` | `{label}` | `{klass}` |")
    lines += [
        "",
        "## Best Rule",
        "",
        f"- Rule: `{best['rule_id']}`.",
        f"- Selected cells: `{','.join(best['selected'])}`.",
        f"- Cost bits before exceptions: `{best['cost_bits']:.2f}`.",
        f"- Exception bits: `{best['exception_bits']:.2f}`.",
        "",
        "## Controls",
        "",
        f"- Conditional random same-size blockers in the same high block: p exact `{result['conditional_controls']['p_exact']:.5f}`.",
        f"- Conditional p best F1 >= observed: `{result['conditional_controls']['p_best_f1_ge']:.5f}`.",
        f"- All 4-digit-set same-blocker-size exact fraction: `{result['digit_set_scan']['same_size_exact_fraction']:.3f}`.",
        f"- All 4-digit-set same-blocker-size p exact: `{result['digit_set_scan']['same_size_p_exact']:.5f}`.",
        f"- All 4-digit-set exact fraction regardless of blocker count: `{result['digit_set_scan']['all_exact_fraction']:.3f}`.",
        f"- All 4-digit-set p exact regardless of blocker count: `{result['digit_set_scan']['all_p_exact']:.5f}`.",
        "",
        "## Stroke Path Check",
        "",
        f"- Connected 4-cell path subsets in the high block: `{result['stroke_path']['connected_subset_count']}/{result['stroke_path']['same_size_subset_count']}`.",
        f"- Connected-subset p: `{result['stroke_path']['p_connected_subset']:.5f}`.",
        f"- Exact connected paths for the observed blockers: `{result['stroke_path']['exact_path_count']}`.",
        f"- Label sequences on exact paths: `{', '.join(f'`{seq}`' for seq in result['stroke_path']['label_sequences'])}`.",
        f"- Literal label-order cost if accepted as written: `{result['stroke_path']['label_sequence_cost_bits_if_literal']:.2f}` bits.",
        "",
        "## Interpretation",
        "",
        "An exact mini-block rule is not sufficient by itself: the high block was",
        "already discovered from the E predicate, and the rule family is searched.",
        "Promotion requires the exact blocker pattern to remain unusual under both",
        "same-block random blocker controls and all 4-digit-set scans.",
        "",
        f"Translation delta: `{result['translation_delta']}`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    pair_table = formula["pair_table"]
    target = observed_targets(pair_table, HIGH_DIGITS)
    best = best_rule_for_target(HIGH_DIGITS, set(target["blockers"]))
    best["target_blockers"] = target["blockers"]
    conditional = conditional_controls(HIGH_DIGITS, len(target["blockers"]), best)
    digit_scan = all_digit_set_scan(pair_table, best)
    stroke_path = stroke_path_analysis(target)
    result = {
        "schema": "high_block_blocker_origin_results.v1",
        "random_seed": RANDOM_SEED,
        "control_trials": CONTROL_TRIALS,
        "target": target,
        "observed_best": best,
        "conditional_controls": conditional,
        "digit_set_scan": {
            "same_size_count": digit_scan["same_size_count"],
            "same_size_exact_count": digit_scan["same_size_exact_count"],
            "same_size_exact_fraction": digit_scan["same_size_exact_fraction"],
            "same_size_p_exact": digit_scan["same_size_p_exact"],
            "all_set_count": digit_scan["all_set_count"],
            "all_exact_count": digit_scan["all_exact_count"],
            "all_exact_fraction": digit_scan["all_exact_fraction"],
            "all_p_exact": digit_scan["all_p_exact"],
            "top_rows": digit_scan["rows"][:20],
        },
        "stroke_path": stroke_path,
        "verdict": classify(best, conditional, digit_scan),
        "translation_delta": "NONE",
        "new_plaintext": False,
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(
        "best={rule} f1={f1:.3f} p_exact={p1:.5f} p_digit={p2:.5f} verdict={verdict}".format(
            rule=best["rule_id"],
            f1=best["f1"],
            p1=conditional["p_exact"],
            p2=digit_scan["same_size_p_exact"],
            verdict=result["verdict"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
