#!/usr/bin/env python3
"""Seed/permutation search for the exact 469 pair-table placement.

The strongest generator clue so far explains the homophone inventory sizes:
one unordered pair per symbol plus frequency-weighted extras. The remaining
question is whether the exact placement of that multiset over the 55 unordered
pair cells can be generated by a simple seed/shuffle/permutation rule.

This script freezes the observed multiset and searches only placement:

- human-readable cell orders over the upper 10x10 triangle;
- symbol orders from alphabet/frequency/first-use families;
- Python MT, LCG, xorshift, and modular-affine seeded permutations;
- known lore seeds plus a small brute-force seed range.

The same candidate family is then scored against shuffled target labels. A
best-looking row is rejected if this broad search can fit shuffled labels just
as well.

Mechanical only. No plaintext or glossary is promoted.
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"
OCC_STREAMS = ROOT / "analysis" / "audit_20260609" / "homophone_channel" / "occ_streams.json"

OUT_JSON = HERE / "inventory_shuffle_seed_results.json"
OUT_MD = HERE / "inventory_shuffle_seed_report.md"

SIGMA = "*ABCEFILNORSTV"
RANDOM_SEED = 46920260621
CONTROL_TRIALS = 500
BRUTE_SEED_LIMIT = 256
KNOWN_SEEDS = [1, 469, 3478, 43153, 34784, 74032, 45331, 486486, 20260618, 19991223, 20011223]
SIGMA_INDEX = {symbol: idx for idx, symbol in enumerate(SIGMA)}


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def all_pairs() -> list[str]:
    return [f"{i}{j}" for i in range(10) for j in range(i, 10)]


def primary_pair_symbol(pair_table: dict, pair: str) -> str:
    row = pair_table[pair]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def pair_orders() -> dict[str, list[str]]:
    pairs = all_pairs()
    orders = {
        "upper_row": pairs,
        "upper_row_rev": list(reversed(pairs)),
        "upper_row_snake": [
            pair
            for i in range(10)
            for pair in ([f"{i}{j}" for j in range(i, 10)] if i % 2 == 0 else [f"{i}{j}" for j in range(9, i - 1, -1)])
        ],
        "upper_column": [f"{i}{j}" for j in range(10) for i in range(j + 1)],
        "upper_column_rev": list(reversed([f"{i}{j}" for j in range(10) for i in range(j + 1)])),
        "upper_column_snake": [
            pair
            for j in range(10)
            for pair in ([f"{i}{j}" for i in range(j + 1)] if j % 2 == 0 else [f"{i}{j}" for i in range(j, -1, -1)])
        ],
        "by_sum": sorted(pairs, key=lambda p: (int(p[0]) + int(p[1]), int(p[0]), int(p[1]))),
        "by_sum_rev": sorted(pairs, key=lambda p: (int(p[0]) + int(p[1]), int(p[0]), int(p[1])), reverse=True),
        "by_diff": sorted(pairs, key=lambda p: (int(p[1]) - int(p[0]), int(p[0]), int(p[1]))),
        "by_diff_rev": sorted(pairs, key=lambda p: (int(p[1]) - int(p[0]), int(p[0]), int(p[1])), reverse=True),
        "by_product": sorted(pairs, key=lambda p: (int(p[0]) * int(p[1]), int(p[0]), int(p[1]))),
        "by_product_rev": sorted(pairs, key=lambda p: (int(p[0]) * int(p[1]), int(p[0]), int(p[1])), reverse=True),
        "by_center_distance": sorted(pairs, key=lambda p: (abs(int(p[0]) - 4.5) + abs(int(p[1]) - 4.5), int(p[0]), int(p[1]))),
        "by_border_first": sorted(
            pairs,
            key=lambda p: (
                not (int(p[0]) in {0, 9} or int(p[1]) in {0, 9}),
                int(p[0]) + int(p[1]),
                int(p[0]),
                int(p[1]),
            ),
        ),
    }

    coords = []
    top, left, bottom, right = 0, 0, 9, 9
    while top <= bottom and left <= right:
        for y in range(left, right + 1):
            coords.append((top, y))
        top += 1
        for x in range(top, bottom + 1):
            coords.append((x, right))
        right -= 1
        if top <= bottom:
            for y in range(right, left - 1, -1):
                coords.append((bottom, y))
            bottom -= 1
        if left <= right:
            for x in range(bottom, top - 1, -1):
                coords.append((x, left))
            left += 1
    seen = []
    seen_set = set()
    for a, b in coords:
        pair = f"{min(a, b)}{max(a, b)}"
        if pair not in seen_set:
            seen.append(pair)
            seen_set.add(pair)
    orders["spiral_first_unordered"] = seen
    orders["spiral_first_unordered_rev"] = list(reversed(seen))
    return orders


def symbol_orders(formula: dict) -> dict[str, list[str]]:
    occ = load_json(OCC_STREAMS)["occ"]
    corpus_counts = Counter({symbol: len(rows) for symbol, rows in occ.items()})
    first_use = {}
    for symbol, rows in occ.items():
        first_use[symbol] = min((int(row["book"]), int(row["pos"])) for row in rows)
    ordered_counts = Counter(formula["code_to_symbol"].values())
    return {
        "sigma": list(SIGMA),
        "sigma_rev": list(reversed(SIGMA)),
        "corpus_freq_desc": sorted(SIGMA, key=lambda s: (-corpus_counts[s], s)),
        "corpus_freq_asc": sorted(SIGMA, key=lambda s: (corpus_counts[s], s)),
        "code_count_desc": sorted(SIGMA, key=lambda s: (-ordered_counts[s], s)),
        "code_count_asc": sorted(SIGMA, key=lambda s: (ordered_counts[s], s)),
        "first_use": sorted(SIGMA, key=lambda s: (first_use.get(s, (999, 999)), s)),
        "first_use_rev": list(reversed(sorted(SIGMA, key=lambda s: (first_use.get(s, (999, 999)), s)))),
    }


def label_list(counts: Counter[str], order: list[str]) -> list[str]:
    out = []
    for symbol in order:
        out.extend([symbol] * counts[symbol])
    return out


def lcg_permutation(n: int, seed: int, a: int, c: int, m: int = 2**31 - 1) -> list[int]:
    x = seed % m
    keys = []
    for idx in range(n):
        x = (a * x + c) % m
        keys.append((x, idx))
    return [idx for _key, idx in sorted(keys)]


def xorshift32(value: int) -> int:
    value &= 0xFFFFFFFF
    value ^= (value << 13) & 0xFFFFFFFF
    value ^= (value >> 17) & 0xFFFFFFFF
    value ^= (value << 5) & 0xFFFFFFFF
    return value & 0xFFFFFFFF


def xorshift_permutation(n: int, seed: int) -> list[int]:
    x = seed or 2463534242
    keys = []
    for idx in range(n):
        x = xorshift32(x + idx + 1)
        keys.append((x, idx))
    return [idx for _key, idx in sorted(keys)]


def affine_permutation(n: int, seed: int, stride: int, offset: int) -> list[int]:
    start = (seed + offset) % n
    return [(start + stride * idx) % n for idx in range(n)]


def permuted_labels(labels: list[str], perm: list[int], mode: str) -> list[str]:
    n = len(labels)
    out = [None] * n
    if mode == "shuffle_labels":
        return [labels[idx] for idx in perm]
    if mode == "shuffle_cells":
        for label, pos in zip(labels, perm):
            out[pos] = label
        return out
    raise ValueError(mode)


def encode(labels: list[str]) -> bytes:
    return bytes(SIGMA_INDEX[label] for label in labels)


def score(predicted: bytes, observed: bytes) -> int:
    return sum(left == right for left, right in zip(predicted, observed))


def build_candidates(formula: dict) -> tuple[list[dict], list[str], dict[str, int]]:
    pair_table = formula["pair_table"]
    observed_by_pair = {pair: primary_pair_symbol(pair_table, pair) for pair in all_pairs()}
    counts = Counter(observed_by_pair.values())
    cell_orders = pair_orders()
    sym_orders = symbol_orders(formula)
    seed_set = set(range(BRUTE_SEED_LIMIT))
    for seed in KNOWN_SEEDS:
        seed_set.update({seed, int(str(seed)[::-1]), seed + 469, abs(seed - 469), seed * 10 + 1})
    seeds = sorted(seed for seed in seed_set if seed >= 0)

    candidates = []
    seen_predictions = {}
    lcg_params = [
        ("lcg_21_1", 21, 1),
        ("lcg_37_17", 37, 17),
        ("lcg_41_19", 41, 19),
    ]
    n = 55
    for cell_order_id, ordered_pairs in cell_orders.items():
        observed = [observed_by_pair[pair] for pair in ordered_pairs]
        for symbol_order_id, symbol_order in sym_orders.items():
            labels = label_list(counts, symbol_order)
            base_specs = [
                ("identity", 0, list(range(n))),
                ("reverse", 0, list(reversed(range(n)))),
            ]
            for algorithm, seed, perm in base_specs:
                for mode in ["shuffle_labels", "shuffle_cells"]:
                    pred = permuted_labels(labels, perm, mode)
                    key = (cell_order_id, encode(pred))
                    if key not in seen_predictions:
                        seen_predictions[key] = len(candidates)
                        candidates.append(
                            {
                                "prediction": key[1],
                                "algorithm": algorithm,
                                "seed": seed,
                                "mode": mode,
                                "cell_order": cell_order_id,
                                "symbol_order": symbol_order_id,
                            }
                        )
            for seed in seeds:
                rng = random.Random(seed)
                perm = list(range(n))
                rng.shuffle(perm)
                for mode in ["shuffle_labels", "shuffle_cells"]:
                    pred = permuted_labels(labels, perm, mode)
                    key = (cell_order_id, encode(pred))
                    if key not in seen_predictions:
                        seen_predictions[key] = len(candidates)
                        candidates.append(
                            {
                                "prediction": key[1],
                                "algorithm": "python_mt_shuffle",
                                "seed": seed,
                                "mode": mode,
                                "cell_order": cell_order_id,
                                "symbol_order": symbol_order_id,
                            }
                        )
                perm = xorshift_permutation(n, seed)
                for mode in ["shuffle_labels", "shuffle_cells"]:
                    pred = permuted_labels(labels, perm, mode)
                    key = (cell_order_id, encode(pred))
                    if key not in seen_predictions:
                        seen_predictions[key] = len(candidates)
                        candidates.append(
                            {
                                "prediction": key[1],
                                "algorithm": "xorshift32_sort",
                                "seed": seed,
                                "mode": mode,
                                "cell_order": cell_order_id,
                                "symbol_order": symbol_order_id,
                            }
                        )
                for lcg_name, a, c in lcg_params:
                    perm = lcg_permutation(n, seed, a, c)
                    for mode in ["shuffle_labels", "shuffle_cells"]:
                        pred = permuted_labels(labels, perm, mode)
                        key = (cell_order_id, encode(pred))
                        if key not in seen_predictions:
                            seen_predictions[key] = len(candidates)
                            candidates.append(
                                {
                                    "prediction": key[1],
                                    "algorithm": lcg_name,
                                    "seed": seed,
                                    "mode": mode,
                                    "cell_order": cell_order_id,
                                    "symbol_order": symbol_order_id,
                                }
                            )
            for stride in [1, 2, 3, 4, 6, 7, 8, 9, 13, 16, 17, 18, 19, 21, 23, 24]:
                if math.gcd(stride, n) != 1:
                    continue
                for offset in range(n):
                    perm = affine_permutation(n, 0, stride, offset)
                    for mode in ["shuffle_labels", "shuffle_cells"]:
                        pred = permuted_labels(labels, perm, mode)
                        key = (cell_order_id, encode(pred))
                        if key not in seen_predictions:
                            seen_predictions[key] = len(candidates)
                            candidates.append(
                                {
                                    "prediction": key[1],
                                    "algorithm": "affine_mod55",
                                    "seed": 0,
                                    "mode": mode,
                                    "cell_order": cell_order_id,
                                    "symbol_order": symbol_order_id,
                                    "stride": stride,
                                    "offset": offset,
                                }
                            )
    canonical_scores = {}
    for idx, candidate in enumerate(candidates):
        observed = encode([observed_by_pair[pair] for pair in cell_orders[candidate["cell_order"]]])
        canonical_scores[idx] = score(candidate["prediction"], observed)
    return candidates, encode([observed_by_pair[pair] for pair in all_pairs()]), canonical_scores


def summarize(values: list[float], observed: float, high_is_good: bool = True) -> dict:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5
    if high_is_good:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {
        "observed": observed,
        "control_mean": mean,
        "control_sd": sd,
        "z_good_direction": z,
        "p_good_direction": p,
        "control_min": min(values),
        "control_max": max(values),
    }


def control_scores(candidates: list[dict], formula: dict) -> list[int]:
    rng = random.Random(RANDOM_SEED)
    cell_orders = pair_orders()
    pair_table = formula["pair_table"]
    target_by_order = {
        order_id: [primary_pair_symbol(pair_table, pair) for pair in ordered_pairs]
        for order_id, ordered_pairs in cell_orders.items()
    }
    matrices = {}
    for order_id in cell_orders:
        preds = [candidate["prediction"] for candidate in candidates if candidate["cell_order"] == order_id]
        if preds:
            matrices[order_id] = np.frombuffer(b"".join(preds), dtype=np.uint8).reshape(len(preds), 55)
    shuffled_by_order = {}
    scores = []
    for _trial in range(CONTROL_TRIALS):
        shuffled_by_order.clear()
        for order_id, labels in target_by_order.items():
            current = labels[:]
            rng.shuffle(current)
            shuffled_by_order[order_id] = np.frombuffer(encode(current), dtype=np.uint8)
        best = 0
        for order_id, matrix in matrices.items():
            current = int((matrix == shuffled_by_order[order_id]).sum(axis=1).max())
            if current > best:
                best = current
        scores.append(best)
    return scores


def write_report(result: dict) -> None:
    best = result["best"]
    lines = [
        "# Inventory Shuffle / Seed Search",
        "",
        "Generated by `inventory_shuffle_seed_search.py`.",
        "",
        "This pass tests whether the exact 55-cell placement of the observed",
        "homophone multiset can be reproduced by simple seeded shuffles or",
        "human-readable permutations.",
        "",
        "## Best Row",
        "",
        "| Algorithm | Seed | Mode | Cell order | Symbol order | Accuracy | Control p | Verdict |",
        "|---|---:|---|---|---|---:|---:|---|",
        (
            f"| `{best['algorithm']}` | {best.get('seed', 0)} | `{best['mode']}` | "
            f"`{best['cell_order']}` | `{best['symbol_order']}` | "
            f"{best['correct']}/55 ({best['accuracy']:.3f}) | "
            f"{result['control_summary']['p_good_direction']:.5f} | `{result['verdict']}` |"
        ),
        "",
        "Top rows:",
        "",
        "| Algorithm | Seed | Mode | Cell order | Symbol order | Correct |",
        "|---|---:|---|---|---|---:|",
    ]
    for row in result["top_rows"][:12]:
        lines.append(
            f"| `{row['algorithm']}` | {row.get('seed', 0)} | `{row['mode']}` | "
            f"`{row['cell_order']}` | `{row['symbol_order']}` | {row['correct']} |"
        )
    lines += [
        "",
        "## Interpretation",
        "",
    ]
    if result["verdict"] == "rejected_control":
        lines += [
            "No seed/permutation rule is promoted. The best row is low-accuracy or",
            "matched by the same broad search against shuffled target labels.",
            "",
        ]
    else:
        lines += [
            "A seed/permutation row survived controls. Treat it as a mechanical",
            "generator candidate only, not as plaintext.",
            "",
        ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    candidates, _observed, canonical_scores = build_candidates(formula)
    rows = []
    for idx, candidate in enumerate(candidates):
        correct = canonical_scores[idx]
        row = {key: value for key, value in candidate.items() if key != "prediction"}
        row.update({"correct": correct, "accuracy": correct / 55})
        rows.append(row)
    rows.sort(key=lambda row: (-row["correct"], row["algorithm"], row["seed"], row["mode"], row["cell_order"], row["symbol_order"]))
    best = rows[0]
    ctrl_scores = control_scores(candidates, formula)
    control_summary = summarize(ctrl_scores, best["correct"], high_is_good=True)
    verdict = "candidate_generator_seeded_placement" if best["correct"] >= 40 and control_summary["p_good_direction"] <= 0.01 else "rejected_control"
    result = {
        "schema": "inventory_shuffle_seed_results.v1",
        "random_seed": RANDOM_SEED,
        "control_trials": CONTROL_TRIALS,
        "brute_seed_limit": BRUTE_SEED_LIMIT,
        "known_seeds": KNOWN_SEEDS,
        "candidate_count": len(candidates),
        "unique_prediction_count": len(candidates),
        "best": best,
        "top_rows": rows[:50],
        "control_summary": control_summary,
        "verdict": verdict,
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(
        f"verdict={verdict} best={best['correct']}/55 "
        f"p={control_summary['p_good_direction']:.5f} candidates={len(candidates)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
