#!/usr/bin/env python3
"""Orientation render-rule search for ordered 469 codes.

The unordered-pair table explains most code->symbol geometry, but the raw books
still choose an ordered code (`ab` or `ba`) for most non-diagonal homophones.
This pass asks whether that orientation is generated by a compact rule.

Two questions are kept separate:

1. book holdout: can local context predict orientation in unseen books?
2. pair holdout: can grid/context features generalize to unseen unordered
   pairs without memorizing a pair-specific lookup?

Mechanical only. No plaintext or glossary is promoted.
"""

from __future__ import annotations

import json
import random
from collections import Counter, defaultdict
from pathlib import Path

from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeClassifier


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"
OCC_STREAMS = ROOT / "analysis" / "audit_20260609" / "homophone_channel" / "occ_streams.json"
HOLDOUT_MANIFEST = HERE / "generator_holdout_manifest.json"

OUT_JSON = HERE / "orientation_render_rule_results.json"
OUT_MD = HERE / "orientation_render_rule_report.md"

RANDOM_SEED = 46920260621
SKLEARN_RANDOM_SEED = RANDOM_SEED % (2**32 - 1)
CONTROL_TRIALS = 2000


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def numeric_key(value: str) -> tuple[int, int | str]:
    try:
        return (0, int(value))
    except ValueError:
        return (1, value)


def reconstruct_books(formula: dict) -> dict[str, str]:
    modules = {module["id"]: module["text"] for module in formula["modules"]}
    return {
        str(book): "".join(modules[item["id"]] if item["type"] == "module" else item["text"] for item in recipe)
        for book, recipe in formula["book_recipes"].items()
    }


def build_tokens(formula: dict) -> list[dict]:
    books = reconstruct_books(formula)
    occ = load_json(OCC_STREAMS)["occ"]
    by_book: dict[str, list[dict]] = defaultdict(list)
    for symbol, rows in occ.items():
        for row in rows:
            by_book[str(row["book"])].append(
                {"book": str(row["book"]), "code_pos": int(row["pos"]), "code": row["code"], "symbol": symbol}
            )

    tokens = []
    for book in sorted(by_book, key=numeric_key):
        rows = sorted(by_book[book], key=lambda item: item["code_pos"])
        raw = books[book]
        offset = 0
        aligned = []
        for index, item in enumerate(rows):
            code = item["code"]
            if raw.startswith(code, offset):
                raw_text, raw_start, omitted = code, offset, False
                offset += 2
            elif code.startswith("0") and offset < len(raw) and raw[offset] == code[1]:
                raw_text, raw_start, omitted = code[1], offset, True
                offset += 1
            else:
                raise ValueError(f"cannot align book={book} offset={offset} code={code}")
            aligned.append({**item, "token_index": index, "raw_text": raw_text, "raw_start": raw_start, "omitted_zero": omitted})
        if offset != len(raw):
            raise ValueError(f"book={book} consumed {offset}, expected {len(raw)}")
        for index, item in enumerate(aligned):
            prev_item = aligned[index - 1] if index else None
            next_item = aligned[index + 1] if index + 1 < len(aligned) else None
            tokens.append(
                {
                    **item,
                    "prev_code": prev_item["code"] if prev_item else "<s>",
                    "prev_symbol": prev_item["symbol"] if prev_item else "<s>",
                    "next_code": next_item["code"] if next_item else "</s>",
                    "next_symbol": next_item["symbol"] if next_item else "</s>",
                }
            )
    return tokens


def orientation_rows(formula: dict) -> tuple[list[dict], dict]:
    rows = []
    excluded = Counter()
    for token in build_tokens(formula):
        code = token["code"]
        if code[0] == code[1]:
            excluded["diagonal"] += 1
            continue
        pair = "".join(sorted(code))
        reverse = code[::-1]
        if reverse not in formula["code_to_symbol"]:
            excluded["single_orientation_pair"] += 1
            continue
        if formula["code_to_symbol"][reverse] != token["symbol"]:
            excluded["orientation_is_symbol_conflict"] += 1
            continue
        prev_last = token["prev_code"][-1] if token["prev_code"] != "<s>" else "<s>"
        next_first = token["next_code"][0] if token["next_code"] != "</s>" else "</s>"
        rows.append(
            {
                **token,
                "pair": pair,
                "lo": int(pair[0]),
                "hi": int(pair[1]),
                "label_sorted": int(code == pair),
                "prev_last": prev_last,
                "next_first": next_first,
                "pair_sum": int(pair[0]) + int(pair[1]),
                "pair_diff": int(pair[1]) - int(pair[0]),
                "pair_product": int(pair[0]) * int(pair[1]),
            }
        )
    return rows, dict(excluded)


def majority_model(train: list[dict], key_fn, default: int):
    groups = defaultdict(Counter)
    for row in train:
        groups[key_fn(row)][row["label_sorted"]] += 1
    lookup = {key: counter.most_common(1)[0][0] for key, counter in groups.items()}
    return lambda row: lookup.get(key_fn(row), default), len(lookup)


def accuracy(rows: list[dict], predict) -> dict:
    labels = [row["label_sorted"] for row in rows]
    preds = [predict(row) for row in rows]
    ok = sum(left == right for left, right in zip(labels, preds))
    return {"accuracy": ok / len(rows) if rows else 0.0, "correct": ok, "total": len(rows)}


def summarize(values: list[float], observed: float, high_is_good: bool = True) -> dict:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5
    if high_is_good:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {
        "observed": observed,
        "control_mean": mean,
        "control_sd": sd,
        "z_good_direction": z,
        "p_good_direction": p,
        "control_min": min(values),
        "control_max": max(values),
    }


def book_holdout(rows: list[dict], holdout_books: set[str]) -> dict:
    train = [row for row in rows if row["book"] not in holdout_books]
    test = [row for row in rows if row["book"] in holdout_books]
    default = Counter(row["label_sorted"] for row in train).most_common(1)[0][0]
    models = {
        "global_majority": lambda row: (),
        "symbol_majority": lambda row: row["symbol"],
        "pair_majority": lambda row: row["pair"],
        "symbol_prevlast": lambda row: (row["symbol"], row["prev_last"]),
        "pair_prevlast": lambda row: (row["pair"], row["prev_last"]),
        "pair_prevcode": lambda row: (row["pair"], row["prev_code"]),
    }
    out = []
    for name, key_fn in models.items():
        if name == "global_majority":
            predict = lambda _row, default=default: default
            group_count = 1
        else:
            predict, group_count = majority_model(train, key_fn, default)
        out.append({"model": name, "groups": group_count, **accuracy(test, predict)})

    def prev_continuity(row):
        if row["prev_last"] == row["pair"][0]:
            return 1
        if row["prev_last"] == row["pair"][1]:
            return 0
        return default

    def next_continuity(row):
        if row["next_first"] == row["pair"][1]:
            return 1
        if row["next_first"] == row["pair"][0]:
            return 0
        return default

    out.append({"model": "prev_digit_continuity", "groups": 0, **accuracy(test, prev_continuity)})
    out.append({"model": "next_digit_continuity_upper_bound", "groups": 0, **accuracy(test, next_continuity)})
    out.sort(key=lambda item: (-item["accuracy"], item["groups"], item["model"]))

    selected = out[0]
    rng = random.Random(RANDOM_SEED)
    control_scores = []
    for _trial in range(CONTROL_TRIALS):
        shuffled = [dict(row) for row in train]
        by_pair = defaultdict(list)
        for index, row in enumerate(train):
            by_pair[row["pair"]].append(index)
        for indices in by_pair.values():
            labels = [train[index]["label_sorted"] for index in indices]
            rng.shuffle(labels)
            for index, label in zip(indices, labels):
                shuffled[index]["label_sorted"] = label
        if selected["model"] == "global_majority":
            ctrl_default = Counter(row["label_sorted"] for row in shuffled).most_common(1)[0][0]
            predict = lambda _row, ctrl_default=ctrl_default: ctrl_default
        else:
            key_fn = models[selected["model"]]
            ctrl_default = Counter(row["label_sorted"] for row in shuffled).most_common(1)[0][0]
            predict, _group_count = majority_model(shuffled, key_fn, ctrl_default)
        control_scores.append(accuracy(test, predict)["accuracy"])

    pair_row = next(row for row in out if row["model"] == "pair_majority")
    return {
        "train_rows": len(train),
        "test_rows": len(test),
        "rows": out,
        "selected": selected,
        "pair_majority": pair_row,
        "gain_vs_pair_majority": selected["accuracy"] - pair_row["accuracy"],
        "selected_vs_pair_preserving_train_shuffle": summarize(control_scores, selected["accuracy"]),
    }


def grid_features(row: dict, include_prev: bool) -> dict:
    features = {
        "lo": row["lo"],
        "hi": row["hi"],
        "sum": row["pair_sum"],
        "diff": row["pair_diff"],
        "product": row["pair_product"],
        "sum_mod3": row["pair_sum"] % 3,
        "product_mod7": row["pair_product"] % 7,
        "has0": row["lo"] == 0,
        "has1": row["lo"] == 1 or row["hi"] == 1,
        "symbol": row["symbol"],
    }
    if include_prev:
        features.update({"prev_last": row["prev_last"], "prev_symbol": row["prev_symbol"]})
    return features


def pair_holdout(rows: list[dict]) -> dict:
    groups = [row["pair"] for row in rows]
    configs = [
        ("grid_ridge", False, make_pipeline(DictVectorizer(sparse=True), RidgeClassifier(alpha=1.0))),
        (
            "grid_tree_depth4",
            False,
            make_pipeline(DictVectorizer(sparse=False), DecisionTreeClassifier(max_depth=4, min_samples_leaf=20, random_state=SKLEARN_RANDOM_SEED)),
        ),
        ("grid_prev_ridge", True, make_pipeline(DictVectorizer(sparse=True), RidgeClassifier(alpha=1.0))),
        (
            "grid_prev_tree_depth4",
            True,
            make_pipeline(DictVectorizer(sparse=False), DecisionTreeClassifier(max_depth=4, min_samples_leaf=20, random_state=SKLEARN_RANDOM_SEED)),
        ),
    ]
    out = []
    logo = LeaveOneGroupOut()
    for name, include_prev, model in configs:
        y_true = []
        y_pred = []
        for train_idx, test_idx in logo.split(rows, groups=groups):
            train_x = [grid_features(rows[index], include_prev) for index in train_idx]
            train_y = [rows[index]["label_sorted"] for index in train_idx]
            test_x = [grid_features(rows[index], include_prev) for index in test_idx]
            test_y = [rows[index]["label_sorted"] for index in test_idx]
            model.fit(train_x, train_y)
            y_true.extend(test_y)
            y_pred.extend(model.predict(test_x))
        out.append({"model": name, "accuracy": accuracy_score(y_true, y_pred), "total": len(y_true)})
    out.sort(key=lambda item: -item["accuracy"])
    return {"rows": out, "selected": out[0], "pair_groups": len(set(groups))}


def write_report(result: dict) -> None:
    book = result["book_holdout"]
    pair = result["pair_holdout"]
    lines = [
        "# Orientation Render Rule Search",
        "",
        "Generated by `orientation_render_rule_search.py`.",
        "",
        "This pass tests how ordered code orientation (`ab` vs `ba`) is rendered",
        "after the unordered-pair table has chosen a homophone pair.",
        "",
        "## Summary",
        "",
        "| Test | Best model | Accuracy | Control p | Verdict |",
        "|---|---|---:|---:|---|",
        (
            f"| Book holdout | `{book['selected']['model']}` | "
            f"{book['selected']['correct']}/{book['selected']['total']} ({book['selected']['accuracy']:.3f}) | "
            f"{book['selected_vs_pair_preserving_train_shuffle']['p_good_direction']:.5f} | "
            f"`{result['verdict']}` |"
        ),
        (
            f"| Pair holdout | `{pair['selected']['model']}` | "
            f"{pair['selected']['accuracy']:.3f} | n/a | `not_general_pair_formula` |"
        ),
        "",
        "## Book Holdout Rows",
        "",
        "| Model | Groups | Accuracy | Correct |",
        "|---|---:|---:|---:|",
    ]
    for row in book["rows"]:
        lines.append(f"| `{row['model']}` | {row['groups']} | {row['accuracy']:.3f} | {row['correct']}/{row['total']} |")
    lines += [
        "",
        "## Pair Holdout Rows",
        "",
        "| Model | Accuracy |",
        "|---|---:|",
    ]
    for row in pair["rows"]:
        lines.append(f"| `{row['model']}` | {row['accuracy']:.3f} |")
    lines += [
        "",
        "## Interpretation",
        "",
        "The orientation layer has a strong book-holdout Markov/context signal,",
        "especially `pair + previous code` and `pair + previous last digit`.",
        "It does not generalize to",
        "unseen unordered pairs as a compact grid formula. This supports a",
        "mechanical render/channel rule, not a recovered original pair-table",
        "formula.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    manifest = load_json(HOLDOUT_MANIFEST)
    holdout_books = {str(book) for book in manifest["book_holdouts"]}
    rows, excluded = orientation_rows(formula)
    book = book_holdout(rows, holdout_books)
    pair = pair_holdout(rows)
    selected = book["selected"]
    control_p = book["selected_vs_pair_preserving_train_shuffle"]["p_good_direction"]
    if selected["accuracy"] >= 0.8 and control_p <= 0.01 and pair["selected"]["accuracy"] < 0.6:
        verdict = "candidate_orientation_render_channel_not_pair_formula"
    elif selected["accuracy"] >= 0.7 and control_p <= 0.05:
        verdict = "weak_orientation_render_signal"
    else:
        verdict = "not_promoted"
    result = {
        "schema": "orientation_render_rule_results.v1",
        "random_seed": RANDOM_SEED,
        "control_trials": CONTROL_TRIALS,
        "choice_rows": len(rows),
        "choice_pairs": len({row["pair"] for row in rows}),
        "excluded": excluded,
        "book_holdout": book,
        "pair_holdout": pair,
        "verdict": verdict,
        "translation_delta": "NONE",
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(
        f"verdict={verdict} book_acc={selected['accuracy']:.3f} "
        f"pair_holdout={pair['selected']['accuracy']:.3f} p={control_p:.5f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
