#!/usr/bin/env python3
"""Local optimization test for the pair->symbol stream objective.

`pair_symbol_stream_compression_search.py` found a suggestive but not promoted
signal: the observed table induces slightly elevated symbol 6-gram repetition.
This follow-up asks whether that signal can be the actual generator objective.

If the original formula were "choose the pair->symbol assignment that maximizes
symbol-stream repetition", the observed table should at least be a local
optimum under pair-label swaps. It is not: simple swaps can increase the same
objective while preserving the exact homophone inventory.

No plaintext or glossary is produced.
"""

from __future__ import annotations

import itertools
import json
import sys
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import pair_symbol_stream_compression_search as stream_search  # noqa: E402


OUT_JSON = HERE / "pair_symbol_stream_optimization_results.json"
OUT_MD = HERE / "pair_symbol_stream_optimization_report.md"

MAX_GREEDY_SWAPS = 50


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def repeat6_score(labels: list[str], pairs: list[str], pair_sequences: dict[str, list[str]]) -> int:
    mapping = dict(zip(pairs, labels))
    strings = stream_search.symbol_strings(mapping, pair_sequences)
    return stream_search.ngram_repetition(strings, 6)["repeat_excess"]


def best_swap(labels: list[str], pairs: list[str], pair_sequences: dict[str, list[str]], current_score: int) -> dict | None:
    best = None
    for left, right in itertools.combinations(range(len(labels)), 2):
        if labels[left] == labels[right]:
            continue
        trial = labels[:]
        trial[left], trial[right] = trial[right], trial[left]
        score = repeat6_score(trial, pairs, pair_sequences)
        if score <= current_score:
            continue
        row = {
            "score_before": current_score,
            "score_after": score,
            "gain": score - current_score,
            "left_index": left,
            "right_index": right,
            "left_pair": pairs[left],
            "right_pair": pairs[right],
            "left_label_before": labels[left],
            "right_label_before": labels[right],
        }
        key = (row["gain"], row["score_after"], row["left_pair"], row["right_pair"])
        if best is None or key > best[0]:
            best = (key, row, trial)
    if best is None:
        return None
    return {"row": best[1], "labels": best[2]}


def greedy_optimize(labels: list[str], pairs: list[str], pair_sequences: dict[str, list[str]]) -> dict:
    current = labels[:]
    current_score = repeat6_score(current, pairs, pair_sequences)
    swaps = []
    while len(swaps) < MAX_GREEDY_SWAPS:
        step = best_swap(current, pairs, pair_sequences, current_score)
        if step is None:
            break
        swaps.append(step["row"])
        current = step["labels"]
        current_score = step["row"]["score_after"]
    return {"final_labels": current, "final_score": current_score, "swaps": swaps}


def mapping_changes(observed_labels: list[str], optimized_labels: list[str], pairs: list[str]) -> list[dict]:
    rows = []
    for pair, observed, optimized in zip(pairs, observed_labels, optimized_labels):
        if observed != optimized:
            rows.append({"pair": pair, "observed": observed, "optimized": optimized})
    return rows


def write_report(result: dict) -> None:
    lines = [
        "# Pair Symbol Stream Optimization Search",
        "",
        "Generated by `pair_symbol_stream_optimization_search.py`.",
        "",
        "This pass tests whether the observed pair table is a local optimum for",
        "the symbol-stream `repeat6_excess` objective. It preserves the exact",
        "homophone inventory and swaps only pair labels. It does not translate 469.",
        "",
        "## Summary",
        "",
        "| Model | repeat6_excess | Gain vs observed | Changed pair labels | Verdict |",
        "|---|---:|---:|---:|---|",
        (
            f"| observed table | {result['observed_score']} | 0 | 0 | "
            "`baseline` |"
        ),
        (
            f"| best one-swap table | {result['best_one_swap']['score_after']} | "
            f"{result['best_one_swap']['gain']} | 2 | `counterexample` |"
        ),
        (
            f"| greedy local optimum | {result['local_optimum']['final_score']} | "
            f"{result['local_optimum']['gain_vs_observed']} | "
            f"{result['local_optimum']['changed_pair_labels']} | `{result['verdict']}` |"
        ),
        "",
        "## Greedy Swaps",
        "",
        "| # | Pair A | Label A | Pair B | Label B | Score before | Score after | Gain |",
        "|---:|---|---|---|---|---:|---:|---:|",
    ]
    for index, row in enumerate(result["local_optimum"]["swaps"], start=1):
        lines.append(
            f"| {index} | `{row['left_pair']}` | `{row['left_label_before']}` | "
            f"`{row['right_pair']}` | `{row['right_label_before']}` | "
            f"{row['score_before']} | {row['score_after']} | {row['gain']} |"
        )
    lines += [
        "",
        "## Interpretation",
        "",
        "The observed table is not a local optimum for the stream-repetition",
        "objective. Therefore `maximize repeat6_excess` cannot be the original",
        "formula for the exact pair-cell placement. The earlier stream-compression",
        "signal remains a weak manufacturing hint, not a generator rule.",
        "",
        f"Translation delta: `{result['translation_delta']}`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = stream_search.load_json(stream_search.FORMULA_JSON)
    pairs = stream_search.all_pairs()
    labels = [stream_search.primary_pair_symbol(formula["pair_table"], pair) for pair in pairs]
    pair_sequences = stream_search.pair_sequences_by_book()
    observed_score = repeat6_score(labels, pairs, pair_sequences)
    first_step = best_swap(labels, pairs, pair_sequences, observed_score)
    if first_step is None:
        raise RuntimeError("observed table is already a local optimum")
    greedy = greedy_optimize(labels, pairs, pair_sequences)
    changes = mapping_changes(labels, greedy["final_labels"], pairs)
    local_strings = stream_search.symbol_strings(dict(zip(pairs, greedy["final_labels"])), pair_sequences)
    local_metrics = stream_search.stream_metrics(local_strings, include_longest=True)
    result = {
        "schema": "pair_symbol_stream_optimization_results.v1",
        "objective": "maximize_repeat6_excess",
        "max_greedy_swaps": MAX_GREEDY_SWAPS,
        "observed_score": observed_score,
        "best_one_swap": first_step["row"],
        "local_optimum": {
            "final_score": greedy["final_score"],
            "gain_vs_observed": greedy["final_score"] - observed_score,
            "swap_count": len(greedy["swaps"]),
            "changed_pair_labels": len(changes),
            "swaps": greedy["swaps"],
            "changed_pairs": changes,
            "stream_metrics": local_metrics,
        },
        "verdict": "rejected_as_original_repeat6_maximization_formula",
        "translation_delta": "NONE",
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(
        f"verdict={result['verdict']} observed={observed_score} "
        f"one_swap={first_step['row']['score_after']} local={greedy['final_score']} "
        f"swaps={len(greedy['swaps'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
