#!/usr/bin/env python3
"""Symbol-stream compression search for the 469 pair table.

If the original pair->symbol table was made to manufacture the 70 book
strings, the induced internal symbol stream should be more compressible or
more repeat-rich than streams generated by random pair-label assignments with
the same homophone inventory.

This script keeps the raw code stream fixed, shuffles only the 55 unordered
pair labels, and measures the resulting symbol streams. It tests the whole
table as a generator component, not individual plaintext meanings.
"""

from __future__ import annotations

import json
import math
import random
import zlib
from collections import Counter, defaultdict
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = HERE / "tape_based_formula_469.json"
OCC_STREAMS = ROOT / "analysis" / "audit_20260609" / "homophone_channel" / "occ_streams.json"

OUT_JSON = HERE / "pair_symbol_stream_compression_results.json"
OUT_MD = HERE / "pair_symbol_stream_compression_report.md"

RANDOM_SEED = 46920260625
CONTROL_TRIALS = 2000
ALPHABET = list("*ABCEFILNORSTV")


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def numeric_key(value: str) -> tuple[int, int | str]:
    try:
        return (0, int(value))
    except ValueError:
        return (1, value)


def all_pairs() -> list[str]:
    return [f"{i}{j}" for i in range(10) for j in range(i, 10)]


def primary_pair_symbol(pair_table: dict, pair: str) -> str:
    row = pair_table[pair]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def pair_sequences_by_book() -> dict[str, list[str]]:
    occ = load_json(OCC_STREAMS)["occ"]
    by_book: dict[str, list[tuple[int, str]]] = defaultdict(list)
    for _symbol, rows in occ.items():
        for row in rows:
            code = row["code"]
            pair = "".join(sorted(code))
            by_book[str(row["book"])].append((int(row["pos"]), pair))
    return {
        book: [pair for _pos, pair in sorted(rows)]
        for book, rows in sorted(by_book.items(), key=lambda item: numeric_key(item[0]))
    }


def symbol_strings(pair_to_symbol: dict[str, str], pair_sequences: dict[str, list[str]]) -> dict[str, str]:
    return {
        book: "".join(pair_to_symbol[pair] for pair in pairs)
        for book, pairs in pair_sequences.items()
    }


def kt_bits_for_sequence(seq: str, order: int) -> float:
    contexts: dict[tuple[str, ...], Counter[str]] = defaultdict(Counter)
    bits = 0.0
    for index, symbol in enumerate(seq):
        context = tuple(seq[max(0, index - order) : index]) if order else ()
        counter = contexts[context]
        total = sum(counter.values())
        probability = (counter[symbol] + 0.5) / (total + 0.5 * len(ALPHABET))
        bits -= math.log2(probability)
        counter[symbol] += 1
    model_bits = len(contexts) * math.log2(len(ALPHABET) + 1)
    return bits + model_bits


def kt_bits(strings: dict[str, str], order: int) -> float:
    return sum(kt_bits_for_sequence(text, order) for text in strings.values())


def zlib_bytes(strings: dict[str, str]) -> int:
    joined = "\n".join(strings[book] for book in sorted(strings, key=numeric_key))
    return len(zlib.compress(joined.encode("ascii"), level=9))


def ngram_repetition(strings: dict[str, str], n: int) -> dict:
    counts = Counter()
    total = 0
    for text in strings.values():
        for index in range(0, len(text) - n + 1):
            counts[text[index : index + n]] += 1
            total += 1
    repeated = sum(count for count in counts.values() if count > 1)
    repeat_excess = sum(count - 1 for count in counts.values() if count > 1)
    return {
        "n": n,
        "total_ngrams": total,
        "distinct_ngrams": len(counts),
        "repeated_ngram_tokens": repeated,
        "repeat_excess": repeat_excess,
        "repeat_fraction": repeated / total if total else 0.0,
    }


def longest_repeat(strings: dict[str, str], max_len: int = 80) -> dict:
    best = {"length": 0, "text": "", "occurrences": 0}
    for length in range(2, max_len + 1):
        counts = Counter()
        for text in strings.values():
            for index in range(0, len(text) - length + 1):
                counts[text[index : index + length]] += 1
        repeated = [(text, count) for text, count in counts.items() if count > 1]
        if not repeated:
            continue
        text, count = max(repeated, key=lambda item: (len(item[0]), item[1], item[0]))
        best = {"length": length, "text": text, "occurrences": count}
    return best


def stream_metrics(strings: dict[str, str], include_longest: bool = False) -> dict:
    kt0 = kt_bits(strings, 0)
    kt1 = kt_bits(strings, 1)
    kt2 = kt_bits(strings, 2)
    ngrams = {n: ngram_repetition(strings, n) for n in [6, 10]}
    out = {
        "kt0_bits": kt0,
        "kt1_bits": kt1,
        "kt2_bits": kt2,
        "kt1_gain_vs_kt0": kt0 - kt1,
        "kt2_gain_vs_kt0": kt0 - kt2,
        "zlib_bytes": zlib_bytes(strings),
        "repeat6_excess": ngrams[6]["repeat_excess"],
        "repeat10_excess": ngrams[10]["repeat_excess"],
    }
    if include_longest:
        longest = longest_repeat(strings)
        out["longest_repeat_length"] = longest["length"]
        out["longest_repeat_occurrences"] = longest["occurrences"]
    return out


def summarize(values: list[float], observed: float, high_is_good: bool) -> dict:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5
    if high_is_good:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {
        "observed": observed,
        "control_mean": mean,
        "control_sd": sd,
        "z_good_direction": z,
        "p_good_direction": p,
        "control_min": min(values),
        "control_max": max(values),
    }


def controls(pair_sequences: dict[str, list[str]], observed: dict, labels: list[str], pairs: list[str]) -> dict:
    rng = random.Random(RANDOM_SEED)
    sampled = {key: [] for key in observed}
    current = labels[:]
    for _trial in range(CONTROL_TRIALS):
        rng.shuffle(current)
        mapping = dict(zip(pairs, current))
        row = stream_metrics(symbol_strings(mapping, pair_sequences), include_longest=False)
        for key, value in row.items():
            sampled[key].append(value)

    directions = {
        "kt0_bits": False,
        "kt1_bits": False,
        "kt2_bits": False,
        "kt1_gain_vs_kt0": True,
        "kt2_gain_vs_kt0": True,
        "zlib_bytes": False,
        "repeat6_excess": True,
        "repeat10_excess": True,
    }
    rows = []
    for key, values in sampled.items():
        summary = summarize(values, observed[key], high_is_good=directions[key])
        rows.append(
            {
                "metric": key,
                "direction": "high" if directions[key] else "low",
                **summary,
            }
        )
    for row in rows:
        row["bonferroni_p"] = min(1.0, row["p_good_direction"] * len(rows))
        if row["bonferroni_p"] <= 0.01:
            row["verdict"] = "candidate"
        elif row["bonferroni_p"] <= 0.05:
            row["verdict"] = "not_promoted_hint"
        else:
            row["verdict"] = "rejected_control"
    rows.sort(key=lambda row: row["bonferroni_p"])
    return {"metric_rows": rows, "best": rows[0]}


def write_report(result: dict) -> None:
    lines = [
        "# Pair Symbol Stream Compression Search",
        "",
        "Generated by `pair_symbol_stream_compression_search.py`.",
        "",
        "This pass tests whether the observed pair->symbol table makes the",
        "resulting internal symbol stream more compressible or repeat-rich than",
        "inventory-preserving shuffled tables. It does not translate 469.",
        "",
        "## Controlled Metrics",
        "",
        "| Metric | Observed | Control mean | z | p | Bonferroni p | Verdict |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for row in result["control"]["metric_rows"]:
        lines.append(
            f"| `{row['metric']}` | {row['observed']:.3f} | {row['control_mean']:.3f} | "
            f"{row['z_good_direction']:.2f} | {row['p_good_direction']:.5f} | "
            f"{row['bonferroni_p']:.5f} | `{row['verdict']}` |"
        )
    lines += [
        "",
        "## Observed Repetition",
        "",
        f"- Longest repeated symbol chunk length: {result['observed']['longest_repeat_length']}.",
        f"- Longest repeated symbol chunk occurrences: {result['observed']['longest_repeat_occurrences']}.",
        f"- `repeat10_excess`: {result['observed']['repeat10_excess']}.",
        "",
        "## Verdict",
        "",
    ]
    if result["verdict"] == "candidate_symbol_stream_compression":
        lines.append(
            "The observed pair table makes the induced symbol stream compressible "
            "beyond inventory-preserving controls. Treat as a mechanical generator "
            "clue only, not as plaintext."
        )
    elif result["verdict"] == "not_promoted_symbol_stream_hint":
        lines.append(
            "The observed pair table has a suggestive stream-compression signal, "
            "but misses the strict promotion gate after metric correction."
        )
    else:
        lines.append(
            "The observed pair table does not make the induced symbol stream more "
            "compressible or repeat-rich than inventory-preserving shuffled tables."
        )
    lines += ["", f"Translation delta: `{result['translation_delta']}`.", ""]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    formula = load_json(FORMULA_JSON)
    pairs = all_pairs()
    labels = [primary_pair_symbol(formula["pair_table"], pair) for pair in pairs]
    pair_to_symbol = dict(zip(pairs, labels))
    pair_sequences = pair_sequences_by_book()
    observed_strings = symbol_strings(pair_to_symbol, pair_sequences)
    observed = stream_metrics(observed_strings, include_longest=True)
    controlled_observed = {
        key: value
        for key, value in observed.items()
        if key not in {"longest_repeat_length", "longest_repeat_occurrences"}
    }
    control = controls(pair_sequences, controlled_observed, labels, pairs)
    if control["best"]["bonferroni_p"] <= 0.01:
        verdict = "candidate_symbol_stream_compression"
    elif control["best"]["bonferroni_p"] <= 0.05:
        verdict = "not_promoted_symbol_stream_hint"
    else:
        verdict = "rejected_control"
    result = {
        "schema": "pair_symbol_stream_compression_results.v1",
        "random_seed": RANDOM_SEED,
        "control_trials": CONTROL_TRIALS,
        "book_count": len(pair_sequences),
        "token_count": sum(len(seq) for seq in pair_sequences.values()),
        "observed": observed,
        "control": control,
        "verdict": verdict,
        "translation_delta": "NONE",
    }
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(ROOT)}")
    print(
        f"verdict={verdict} best={control['best']['metric']} "
        f"p={control['best']['p_good_direction']:.5f} "
        f"bonferroni={control['best']['bonferroni_p']:.5f}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
