#!/usr/bin/env python3
"""Sequential/automaton search for the 55-cell 469 pair table.

The remaining unknown is exact placement of symbols across unordered pair
cells. This pass treats a traversal of those 55 cells as a sequence and asks
whether any natural traversal is generated by a short sequential process:

- low order Markov structure;
- repeated transitions / small transition graph;
- zlib-compressible sequence;
- small position-mod-k automata.

Controls preserve the exact symbol multiset and repeat the same search over
shuffled sequences. No semantic translation is produced.
"""

from __future__ import annotations

import json
import math
import random
import zlib
from collections import Counter, defaultdict
from pathlib import Path


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FORMULA_JSON = ROOT / "analysis" / "mechanism_model_20260618" / "mechanical_formula_469.json"

OUT_JSON = HERE / "pair_sequence_automaton_results.json"
OUT_MD = HERE / "pair_sequence_automaton_report.md"

RANDOM_SEED = 46920260619
TRIALS = 5000


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: Path, data) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def pair_orders() -> dict[str, list[str]]:
    pairs = [f"{i}{j}" for i in range(10) for j in range(i, 10)]
    orders = {
        "upper_row": pairs,
        "upper_row_rev": list(reversed(pairs)),
        "upper_row_snake": [
            pair
            for i in range(10)
            for pair in ([f"{i}{j}" for j in range(i, 10)] if i % 2 == 0 else [f"{i}{j}" for j in range(9, i - 1, -1)])
        ],
        "upper_column": [f"{i}{j}" for j in range(10) for i in range(j + 1)],
        "upper_column_snake": [
            pair
            for j in range(10)
            for pair in ([f"{i}{j}" for i in range(j + 1)] if j % 2 == 0 else [f"{i}{j}" for i in range(j, -1, -1)])
        ],
        "by_sum": sorted(pairs, key=lambda p: (int(p[0]) + int(p[1]), int(p[0]), int(p[1]))),
        "by_sum_rev": sorted(pairs, key=lambda p: (int(p[0]) + int(p[1]), int(p[0]), int(p[1])), reverse=True),
        "by_diff": sorted(pairs, key=lambda p: (int(p[1]) - int(p[0]), int(p[0]), int(p[1]))),
        "by_diff_rev": sorted(pairs, key=lambda p: (int(p[1]) - int(p[0]), int(p[0]), int(p[1])), reverse=True),
        "by_product": sorted(pairs, key=lambda p: (int(p[0]) * int(p[1]), int(p[0]), int(p[1]))),
        "by_triangular_index": sorted(pairs, key=lambda p: int(p[1]) * (int(p[1]) + 1) // 2 + int(p[0])),
    }
    coords = []
    top, left, bottom, right = 0, 0, 9, 9
    while top <= bottom and left <= right:
        for y in range(left, right + 1):
            coords.append((top, y))
        top += 1
        for x in range(top, bottom + 1):
            coords.append((x, right))
        right -= 1
        if top <= bottom:
            for y in range(right, left - 1, -1):
                coords.append((bottom, y))
            bottom -= 1
        if left <= right:
            for x in range(bottom, top - 1, -1):
                coords.append((x, left))
            left += 1
    seen = []
    seen_set = set()
    for a, b in coords:
        pair = f"{min(a, b)}{max(a, b)}"
        if pair not in seen_set:
            seen.append(pair)
            seen_set.add(pair)
    orders["spiral_first_unordered"] = seen
    return orders


def primary_pair_symbol(pair_table: dict, pair: str) -> str:
    row = pair_table[pair]
    if row["status"] == "pure":
        return row["symbol_if_pure"]
    return sorted(row["symbols"])[0]


def kt_bits_for_order(seq: list[str], order: int, alphabet: list[str]) -> float:
    contexts: dict[tuple[str, ...], Counter[str]] = defaultdict(Counter)
    bits = 0.0
    for idx, symbol in enumerate(seq):
        context = tuple(seq[max(0, idx - order) : idx]) if order else ()
        counter = contexts[context]
        total = sum(counter.values())
        prob = (counter[symbol] + 0.5) / (total + 0.5 * len(alphabet))
        bits -= math.log2(prob)
        counter[symbol] += 1
    # Mild model cost for contexts actually used.
    model_bits = len(contexts) * math.log2(len(alphabet) + 1)
    return bits + model_bits


def transition_metrics(seq: list[str]) -> dict:
    transitions = list(zip(seq, seq[1:]))
    edges = Counter(transitions)
    out_degree = defaultdict(set)
    in_degree = defaultdict(set)
    for left, right in transitions:
        out_degree[left].add(right)
        in_degree[right].add(left)
    repeated_edges = sum(count - 1 for count in edges.values() if count > 1)
    deterministic_steps = sum(1 for left, right in transitions if len(out_degree[left]) == 1)
    return {
        "unique_edges": len(edges),
        "repeated_edge_excess": repeated_edges,
        "mean_out_degree": sum(len(values) for values in out_degree.values()) / len(out_degree),
        "mean_in_degree": sum(len(values) for values in in_degree.values()) / len(in_degree),
        "deterministic_step_fraction": deterministic_steps / len(transitions),
    }


def best_mod_automaton(seq: list[str], max_k: int = 28) -> dict:
    best = None
    for k in range(1, min(max_k, len(seq)) + 1):
        by_state = defaultdict(Counter)
        for idx, symbol in enumerate(seq):
            by_state[idx % k][symbol] += 1
        pred = {state: counter.most_common(1)[0][0] for state, counter in by_state.items()}
        ok = sum(pred[idx % k] == symbol for idx, symbol in enumerate(seq))
        accuracy = ok / len(seq)
        model_bits = k * math.log2(len(set(seq)) + 1)
        exception_bits = (len(seq) - ok) * (math.log2(len(seq)) + math.log2(len(set(seq)) + 1))
        mdl_bits = model_bits + exception_bits
        row = {
            "k": k,
            "accuracy": accuracy,
            "correct": ok,
            "mdl_bits_est": mdl_bits,
            "pattern": "".join(pred[state] for state in range(k)),
        }
        if best is None or (row["accuracy"], -row["mdl_bits_est"], -row["k"]) > (
            best["accuracy"],
            -best["mdl_bits_est"],
            -best["k"],
        ):
            best = row
    return best


def seq_metrics(seq: list[str], alphabet: list[str]) -> dict:
    kt0 = kt_bits_for_order(seq, 0, alphabet)
    kt1 = kt_bits_for_order(seq, 1, alphabet)
    kt2 = kt_bits_for_order(seq, 2, alphabet)
    compressed = len(zlib.compress("".join(seq).encode("ascii"), level=9))
    trans = transition_metrics(seq)
    mod = best_mod_automaton(seq)
    return {
        "kt0_bits": kt0,
        "kt1_bits": kt1,
        "kt2_bits": kt2,
        "kt1_gain_vs_kt0": kt0 - kt1,
        "kt2_gain_vs_kt0": kt0 - kt2,
        "zlib_bytes": compressed,
        "transition": trans,
        "best_mod_automaton": mod,
    }


def summarize(values: list[float], observed: float, high_is_good: bool) -> dict:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5
    if high_is_good:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {"observed": observed, "mean": mean, "sd": sd, "z": z, "p": p, "min": min(values), "max": max(values)}


def analyze_order(seq: list[str], alphabet: list[str], rng: random.Random) -> dict:
    observed = seq_metrics(seq, alphabet)
    controls = {
        "kt1_gain_vs_kt0": [],
        "kt2_gain_vs_kt0": [],
        "zlib_bytes": [],
        "unique_edges": [],
        "repeated_edge_excess": [],
        "deterministic_step_fraction": [],
        "best_mod_accuracy": [],
    }
    shuffled = seq[:]
    for _trial in range(TRIALS):
        rng.shuffle(shuffled)
        current = seq_metrics(shuffled, alphabet)
        controls["kt1_gain_vs_kt0"].append(current["kt1_gain_vs_kt0"])
        controls["kt2_gain_vs_kt0"].append(current["kt2_gain_vs_kt0"])
        controls["zlib_bytes"].append(current["zlib_bytes"])
        controls["unique_edges"].append(current["transition"]["unique_edges"])
        controls["repeated_edge_excess"].append(current["transition"]["repeated_edge_excess"])
        controls["deterministic_step_fraction"].append(current["transition"]["deterministic_step_fraction"])
        controls["best_mod_accuracy"].append(current["best_mod_automaton"]["accuracy"])
    summary = {
        "kt1_gain_vs_kt0": summarize(controls["kt1_gain_vs_kt0"], observed["kt1_gain_vs_kt0"], True),
        "kt2_gain_vs_kt0": summarize(controls["kt2_gain_vs_kt0"], observed["kt2_gain_vs_kt0"], True),
        "zlib_bytes": summarize(controls["zlib_bytes"], observed["zlib_bytes"], False),
        "unique_edges": summarize(controls["unique_edges"], observed["transition"]["unique_edges"], False),
        "repeated_edge_excess": summarize(controls["repeated_edge_excess"], observed["transition"]["repeated_edge_excess"], True),
        "deterministic_step_fraction": summarize(
            controls["deterministic_step_fraction"],
            observed["transition"]["deterministic_step_fraction"],
            True,
        ),
        "best_mod_accuracy": summarize(
            controls["best_mod_accuracy"],
            observed["best_mod_automaton"]["accuracy"],
            True,
        ),
    }
    strongest = min(
        (
            {"metric": metric, **values}
            for metric, values in summary.items()
        ),
        key=lambda item: item["p"],
    )
    return {
        "sequence": "".join(seq),
        "observed": observed,
        "control_summary": summary,
        "strongest_metric": strongest,
    }


def main() -> int:
    formula = load_json(FORMULA_JSON)
    pair_table = formula["pair_table"]
    orders = pair_orders()
    alphabet = sorted({primary_pair_symbol(pair_table, pair) for pair in orders["upper_row"]})
    rng = random.Random(RANDOM_SEED)
    rows = []
    for order_name, pairs in orders.items():
        seq = [primary_pair_symbol(pair_table, pair) for pair in pairs]
        result = analyze_order(seq, alphabet, rng)
        rows.append({"order": order_name, **result})
    rows.sort(key=lambda row: row["strongest_metric"]["p"])
    best = rows[0]
    metric_count = 7
    search_family_count = len(rows) * metric_count
    best_corrected_p = min(1.0, best["strongest_metric"]["p"] * search_family_count)
    verdict = "rejected_control"
    output = {
        "schema": "pair_sequence_automaton_results.v1",
        "translation_delta": "NONE",
        "accepted_original_formula": None,
        "trials_per_order": TRIALS,
        "searched_orders": len(rows),
        "metrics_per_order": metric_count,
        "bonferroni_family_count": search_family_count,
        "rows": rows,
        "best": {
            "order": best["order"],
            "strongest_metric": best["strongest_metric"],
            "bonferroni_p": best_corrected_p,
            "sequence": best["sequence"],
        },
        "verdict": verdict,
    }
    write_json(OUT_JSON, output)

    lines = [
        "# Pair Sequence Automaton Search",
        "",
        "Generated by `pair_sequence_automaton_search.py`.",
        "",
        "This pass treats each traversal of the 55 pair cells as a symbol sequence",
        "and tests whether a short sequential generator is visible.",
        "",
        "## Best Signals by Traversal",
        "",
        "| Order | Strongest metric | Observed | Control mean | z | p | Corrected best p | Verdict |",
        "|---|---|---:|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        metric = row["strongest_metric"]
        corrected = min(1.0, metric["p"] * search_family_count)
        lines.append(
            f"| `{row['order']}` | `{metric['metric']}` | {metric['observed']:.3f} | {metric['mean']:.3f} | {metric['z']:.2f} | {metric['p']:.3f} | {corrected:.3f} | `{verdict}` |"
        )
    lines.extend(
        [
            "",
            "## Best Mod-k Automata",
            "",
            "| Order | k | Accuracy | Pattern |",
            "|---|---:|---:|---|",
        ]
    )
    for row in rows:
        mod = row["observed"]["best_mod_automaton"]
        lines.append(f"| `{row['order']}` | {mod['k']} | {mod['accuracy']:.3f} | `{mod['pattern']}` |")
    lines.extend(
        [
            "",
            "## Verdict",
            "",
            f"The strongest nominal signal is corrected over {search_family_count}",
            f"searched order/metric combinations; corrected p = {best_corrected_p:.3f}.",
            "No traversal exposes a sequential/automaton generator that survives",
            "multiset-preserving shuffled controls. The exact pair-cell placement",
            "remains unresolved.",
            "",
        ]
    )
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT_JSON.relative_to(HERE)}")
    print(f"wrote {OUT_MD.relative_to(HERE)}")
    print(
        "best_order={} metric={} p={:.3f}".format(
            best["order"],
            best["strongest_metric"]["metric"],
            best["strongest_metric"]["p"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
