#!/usr/bin/env python3
"""Quotient worksheet edit-log MDL search.

This pass tests an authorial-process hypothesis rather than another closed-form
cell formula: start with a simple quotient worksheet generated by quota/order
rules, then apply a small edit log (`swap`, `copy_neighbor`, `manual_label`) to
reach the observed 6<->9 quotient labels.

It reuses the candidate generator from `quotient_constructive_fill_search.py`
and charges every residual edit.  No plaintext, glossary, or semantic
translation is promoted.
"""

from __future__ import annotations

import importlib.util
import json
import math
import random
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
QCF_PATH = HERE / "quotient_constructive_fill_search.py"

OUT_JSON = HERE / "quotient_edit_log_mdl_results.json"
OUT_MD = HERE / "quotient_edit_log_mdl_report.md"

SIGMA = tuple("*ABCEFILNORSTV")
SYMBOL_BITS = math.log2(len(SIGMA))
RANDOM_SEED = 46920260619
CONTROL_TRIALS = 120
CONTROL_PREDICTION_LIMIT = 500


def load_qcf_module():
    spec = importlib.util.spec_from_file_location("quotient_constructive_fill_search", QCF_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {QCF_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def write_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def summarize(values: list[float], observed: float, higher_is_better: bool) -> dict[str, Any]:
    mean = sum(values) / len(values)
    sd = (sum((value - mean) ** 2 for value in values) / (len(values) - 1)) ** 0.5 if len(values) > 1 else 0.0
    if higher_is_better:
        p = (sum(value >= observed for value in values) + 1) / (len(values) + 1)
        z = (observed - mean) / sd if sd else 0.0
    else:
        p = (sum(value <= observed for value in values) + 1) / (len(values) + 1)
        z = (mean - observed) / sd if sd else 0.0
    return {
        "observed": observed,
        "mean": mean,
        "sd": sd,
        "min": min(values),
        "max": max(values),
        "p_good_direction": p,
        "z_good_direction": z,
    }


def coordinate(cell: dict[str, Any], qcf) -> tuple[int, int]:
    return (qcf.BASE_CLASS_RANK[cell["left"]], qcf.BASE_CLASS_RANK[cell["right"]])


def build_neighbors(cells: list[dict[str, Any]], qcf) -> list[list[int]]:
    by_coord: dict[tuple[int, int], list[int]] = {}
    for index, cell in enumerate(cells):
        by_coord.setdefault(coordinate(cell, qcf), []).append(index)
    out: list[list[int]] = []
    deltas = [(-1, 0), (1, 0), (0, -1), (0, 1), (-1, -1), (1, 1)]
    for index, cell in enumerate(cells):
        a, b = coordinate(cell, qcf)
        neighbors = set()
        for da, db in deltas:
            key = (a + da, b + db)
            for other in by_coord.get(key, []):
                if other != index:
                    neighbors.add(other)
        # Variant neighbors, especially QQ same/cross, share one coordinate.
        for other in by_coord.get((a, b), []):
            if other != index:
                neighbors.add(other)
        out.append(sorted(neighbors))
    return out


def edit_log_score(prediction: tuple[int, ...], target: tuple[int, ...], neighbors: list[list[int]], model_bits: float) -> dict[str, Any]:
    n = len(target)
    cell_bits = math.log2(n)
    pair_bits = math.log2(math.comb(n, 2))
    manual_cost = cell_bits + SYMBOL_BITS
    copy_cost = cell_bits + 2.0
    swap_cost = pair_bits + 2.5
    family_bits = math.log2(3)

    mismatches = {index for index, (pred, actual) in enumerate(zip(prediction, target)) if pred != actual}
    swaps = []
    used = set()
    reciprocal = []
    for left in sorted(mismatches):
        if left in used:
            continue
        for right in sorted(mismatches):
            if right <= left or right in used:
                continue
            if prediction[left] == target[right] and prediction[right] == target[left]:
                reciprocal.append((left, right))
                break
        if reciprocal and reciprocal[-1][0] == left:
            used.add(left)
            used.add(reciprocal[-1][1])
    for left, right in reciprocal:
        swaps.append({"left": left, "right": right})
    remaining = sorted(mismatches - used)
    copies = []
    manuals = []
    for index in remaining:
        if any(target[neighbor] == target[index] for neighbor in neighbors[index]):
            copies.append(index)
        else:
            manuals.append(index)
    edit_bits = family_bits + len(swaps) * swap_cost + len(copies) * copy_cost + len(manuals) * manual_cost
    total_bits = model_bits + edit_bits
    lookup_bits = n * SYMBOL_BITS
    return {
        "mismatch_count": len(mismatches),
        "swap_count": len(swaps),
        "copy_neighbor_count": len(copies),
        "manual_label_count": len(manuals),
        "model_bits": model_bits,
        "edit_bits": edit_bits,
        "total_bits": total_bits,
        "lookup_bits": lookup_bits,
        "gain_vs_lookup_bits": lookup_bits - total_bits,
        "lookup_ratio": total_bits / lookup_bits,
        "swaps": swaps[:20],
        "copies": copies[:20],
        "manuals": manuals[:20],
    }


def attach_edit_scores(rows: list[dict[str, Any]], target: tuple[int, ...], neighbors: list[list[int]]) -> list[dict[str, Any]]:
    out = []
    for row in rows:
        pred = tuple(row["_prediction"])
        score = edit_log_score(pred, target, neighbors, row["model_selection_bits"])
        clean = {key: value for key, value in row.items() if key != "_prediction"}
        clean["prediction_for_control"] = list(pred)
        clean["edit_log"] = score
        out.append(clean)
    out.sort(
        key=lambda row: (
            row["target_derived"],
            -row["edit_log"]["gain_vs_lookup_bits"],
            row["edit_log"]["manual_label_count"],
            row["edit_log"]["copy_neighbor_count"],
            row["inventory_id"],
            row["fill_order_id"],
            row["symbol_order_id"],
        )
    )
    return out


def controls(scored_rows: list[dict[str, Any]], target: tuple[int, ...], neighbors: list[list[int]]) -> dict[str, Any]:
    rng = random.Random(RANDOM_SEED)
    candidates = [row for row in scored_rows if not row["target_derived"]][:CONTROL_PREDICTION_LIMIT]
    predictions = [tuple(row["prediction_for_control"]) for row in candidates]
    model_bits = [row["model_selection_bits"] for row in candidates]
    best_gain = []
    best_total_bits = []
    best_manuals = []
    labels = list(target)
    for _ in range(CONTROL_TRIALS):
        shuffled = labels[:]
        rng.shuffle(shuffled)
        ctrl_target = tuple(shuffled)
        best = None
        for pred, bits in zip(predictions, model_bits):
            score = edit_log_score(pred, ctrl_target, neighbors, bits)
            if best is None or score["gain_vs_lookup_bits"] > best["gain_vs_lookup_bits"]:
                best = score
        assert best is not None
        best_gain.append(best["gain_vs_lookup_bits"])
        best_total_bits.append(best["total_bits"])
        best_manuals.append(best["manual_label_count"])
    observed = scored_rows[0]["edit_log"]
    return {
        "trials": CONTROL_TRIALS,
        "candidate_limit": len(candidates),
        "inventory_label_shuffle": {
            "best_gain_vs_lookup_bits": summarize(best_gain, observed["gain_vs_lookup_bits"], True),
            "best_total_bits": summarize(best_total_bits, observed["total_bits"], False),
            "best_manual_label_count": summarize(best_manuals, observed["manual_label_count"], False),
        },
    }


def verdict(best: dict[str, Any], ctrl: dict[str, Any]) -> str:
    gain = best["edit_log"]["gain_vs_lookup_bits"]
    p = ctrl["inventory_label_shuffle"]["best_gain_vs_lookup_bits"]["p_good_direction"]
    if gain > 0 and p <= 0.05 and best["edit_log"]["manual_label_count"] <= 5:
        return "candidate_quotient_edit_log_generator"
    if gain > 0 and p <= 0.05:
        return "weak_edit_log_compression_many_manuals"
    if gain > 0:
        return "edit_log_positive_control_sensitive"
    return "edit_log_not_promoted"


def write_report(result: dict[str, Any]) -> None:
    best = result["best_non_leaky"]
    edit = best["edit_log"]
    ctrl = result["controls"]["inventory_label_shuffle"]
    lines = [
        "# Quotient Edit-Log MDL Search",
        "",
        "Generated by `quotient_edit_log_mdl_search.py`.",
        "",
        "This pass tests a human-workflow model: generate a quotient worksheet",
        "from quota/order rules, then pay for an explicit edit log to reach the",
        "target. It assigns no plaintext.",
        "",
        "## Best Non-Leaky Edit Log",
        "",
        "| Start model | Hits before edits | Swaps | Copy-neighbor | Manual labels | Total bits | Lookup ratio | Gain |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
        f"| `{best['inventory_id']} / {best['fill_order_id']} / {best['symbol_order_id']}` | {best['exact_hits']}/46 | {edit['swap_count']} | {edit['copy_neighbor_count']} | {edit['manual_label_count']} | {edit['total_bits']:.2f} | {edit['lookup_ratio']:.3f} | {edit['gain_vs_lookup_bits']:.2f} |",
        "",
        "## Controls",
        "",
        "| Metric | Observed | Mean | Max/Min | p(good) |",
        "|---|---:|---:|---:|---:|",
        f"| best gain vs lookup | {ctrl['best_gain_vs_lookup_bits']['observed']:.2f} | {ctrl['best_gain_vs_lookup_bits']['mean']:.2f} | {ctrl['best_gain_vs_lookup_bits']['max']:.2f} | {ctrl['best_gain_vs_lookup_bits']['p_good_direction']:.5f} |",
        f"| best total bits | {ctrl['best_total_bits']['observed']:.2f} | {ctrl['best_total_bits']['mean']:.2f} | {ctrl['best_total_bits']['min']:.2f} | {ctrl['best_total_bits']['p_good_direction']:.5f} |",
        f"| manual labels | {ctrl['best_manual_label_count']['observed']:.0f} | {ctrl['best_manual_label_count']['mean']:.2f} | {ctrl['best_manual_label_count']['min']:.0f} | {ctrl['best_manual_label_count']['p_good_direction']:.5f} |",
        "",
        "## Interpretation",
        "",
        "The edit log can always rescue a weak worksheet if manual labels are cheap",
        "enough. Here the best non-leaky row still needs many explicit edits, and",
        "the charged edit log is compared against the same search on shuffled",
        "targets. This distinguishes a plausible worksheet story from a compressed",
        "lookup table.",
        "",
        f"Verdict: `{result['verdict']}`.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    qcf = load_qcf_module()
    formula = qcf.load_json(qcf.FORMULA_JSON)
    quotient = qcf.load_json(qcf.QUOTIENT_JSON)
    line_order_result = qcf.maybe_load_json(qcf.LINE_ORDER_JSON)
    inventory_result = qcf.maybe_load_json(qcf.INVENTORY_JSON)
    cells, _by_id = qcf.build_quotient_cells(quotient, formula)
    inventories = qcf.build_inventory_models(formula, cells, inventory_result)
    fill_orders = qcf.build_fill_orders(cells, line_order_result)
    symbol_orders = qcf.build_symbol_orders(formula, cells)
    rows, _predictions = qcf.evaluate_candidates(cells, inventories, fill_orders, symbol_orders)
    target = tuple({symbol: index for index, symbol in enumerate(SIGMA)}[cell["label"]] for cell in cells)
    neighbors = build_neighbors(cells, qcf)
    scored = attach_edit_scores(rows, target, neighbors)
    top_non_leaky = [row for row in scored if not row["target_derived"]]
    best = top_non_leaky[0]
    ctrl = controls(scored, target, neighbors)
    # Remove bulky control-only predictions from the persisted top rows.
    persisted_top = []
    for row in top_non_leaky[:40]:
        clone = dict(row)
        clone.pop("prediction_for_control", None)
        persisted_top.append(clone)
    result = {
        "schema": "quotient_edit_log_mdl_results.v1",
        "translation_delta": "NONE",
        "search_parameters": {
            "candidate_rows": len(rows),
            "control_trials": CONTROL_TRIALS,
            "control_prediction_limit": CONTROL_PREDICTION_LIMIT,
        },
        "best_non_leaky": {key: value for key, value in best.items() if key != "prediction_for_control"},
        "top_non_leaky": persisted_top,
        "controls": ctrl,
    }
    result["verdict"] = verdict(best, ctrl)
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON.relative_to(HERE)}")
    print(f"wrote {OUT_MD.relative_to(HERE)}")
    print(
        "verdict={verdict} gain={gain:.2f} manual={manual}".format(
            verdict=result["verdict"],
            gain=best["edit_log"]["gain_vs_lookup_bits"],
            manual=best["edit_log"]["manual_label_count"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
