from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

LEDGER = TEST_RESULTS / "01_book_length_ledger.json"
GATE = TEST_RESULTS / "02_book_length_generation_gate.json"
OUT = REPORTS / "final_book_length_generation_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    ledger = load_json(LEDGER)
    gate = load_json(GATE)
    assert_boundary("book_length_ledger", ledger)
    assert_boundary("book_length_generation_gate", gate)
    ls = ledger["summary"]
    gs = gate["summary"]
    classification = (
        "BOOK_LENGTH_GENERATOR_PROMOTED"
        if gs["promotes_book_length_generator"]
        else "BOOK_LENGTH_GENERATOR_REJECTED"
    )
    lines = [
        "# Final Book Length Generation Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Are the 70 book lengths mechanically generated by source-free rules, or",
        "are they still declared as a residual ledger used by later parsers?",
        "",
        "## Ledger",
        "",
        f"- Book count: `{ls['book_count']}`.",
        f"- Length range: `{ls['length_min']}..{ls['length_max']}`.",
        f"- Unique lengths: `{ls['unique_lengths']}`.",
        f"- Raw gamma length bits: `{ls['raw_gamma_length_bits']}`.",
        f"- Active signed-Rice ledger: `anchor={ls['active_anchor']}`, `k={ls['active_k']}`, `{ls['active_signed_rice_length_bits']}` bits.",
        f"- Active gain vs raw gamma: `{ls['active_gain_vs_raw_gamma']}` bits.",
        "",
        "The active ledger is a real compression improvement over independent",
        "gamma-coded lengths, but it still declares residuals for the exact",
        "length sequence.",
        "",
        "## Generation Gate",
        "",
        f"- Policies tested: `{gs['policy_count']}`.",
        f"- Best full-fit policy: `{gs['best_full_policy']}`.",
        f"- Best full-fit exact lengths: `{gs['best_full_exact_lengths']}/{gs['book_count']}`.",
        f"- Best full-fit mean absolute error: `{gs['best_full_mean_abs_error']:.3f}`.",
        f"- Best lookup context: `{gs['best_lookup_context']}` with `{gs['best_lookup_exact_lengths']}/{gs['book_count']}` exact lengths.",
        f"- Lookup context count: `{gs['best_lookup_context_count']}` length-bearing contexts.",
        f"- Prefix/holdout cover-all cells: `{gs['prequential_cover_all_cells']}/{gs['prequential_cells']}`.",
        f"- Prefix/holdout any-exact cells: `{gs['prequential_any_exact_cells']}/{gs['prequential_cells']}`.",
        "",
        "The only exact full-corpus representation is a book-index lookup carrying",
        "length payloads. Simple source-free policies do not generate the exact",
        "lengths, and prefix/holdout never covers all future books.",
        "",
        "## Decision",
        "",
        "- No book-length generator is promoted.",
        "- Book lengths remain external declared residuals, even though the residual ledger is compact.",
        "- Gates that grant book length are still granting a real dependency.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Book length ledger](test_results/01_book_length_ledger.md)",
        "- [Book length generation gate](test_results/02_book_length_generation_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
