#!/usr/bin/env python3
"""Compile final report for the coarse control program audit."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
FRONT = ROOT / "analysis" / "coarse_control_program_audit_20260622"
TEST_RESULTS = FRONT / "reports" / "test_results"
RESULT_PATH = TEST_RESULTS / "01_coarse_control_program_gate.json"
OUT = FRONT / "reports" / "final_coarse_control_program_audit.md"


def bits(value: float) -> str:
    return f"{value:.3f}"


def main() -> None:
    result = json.loads(RESULT_PATH.read_text())
    if result.get("translation_delta") != "NONE":
        raise SystemExit("translation delta must remain NONE")
    if result.get("case_reopened") or result.get("plaintext_claim"):
        raise SystemExit("audit must not reopen case or make plaintext claims")

    best_name = result["decision"]["best_model"]
    best = result["models"][best_name]

    lines = [
        "# Final Coarse Control Program Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{result['classification']}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Case reopened: `False`",
        "",
        "## Question",
        "",
        "After exact `type:length` failed and length was factored into coarse bucket "
        "plus residual innovation, this audit tests whether the coarse "
        "`type:length_bucket` stream can be encoded or generated by a target-free "
        "sequential program. Per-book operation count is granted.",
        "",
        "This is not a book generator: exact within-bucket length residuals, literal "
        "payload, copy hints, seed books, and row0 remain external.",
        "",
        "## Result",
        "",
        f"- Vocabulary: `{len(result['inputs']['vocab'])}` coarse symbols.",
        f"- Best model: `{best_name}` with features `{'+'.join(best['features']) or 'global'}`.",
        f"- Best model bits over prefix/suffix cutoffs: `{bits(best['observed_model_bits'])}`.",
        f"- Saving vs uniform coarse control: `{bits(best['observed_saving_bits'])}` bits.",
        f"- Same-multiset shuffled p95 saving: `{bits(best['random_saving_p95'])}` bits.",
        f"- Top1 hits: `{best['observed_top1_hits']}/{best['observed_total_rows']}`.",
        f"- Promoted models: `{result['decision']['promoted_models']}`.",
        f"- Generator-promoted coarse models: `{result['decision']['generator_promoted']}`.",
        "",
        "The result survives same-multiset shuffled controls. This matters because the "
        "global marginal distribution alone is not promoted; the promoted models use "
        "operation count, operation position, remaining operations, or previous coarse "
        "symbol.",
        "",
        "## Generation Check",
        "",
        "| Cutoff | Test Books | Greedy Exact | Beam20 Exact | Beam20 Nontrivial | Greedy Prefix Ops |",
        "| ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in best["cutoff_rows"]:
        generation = row["generation"]
        lines.append(
            f"| `{row['cutoff']}` | `{generation['test_books']}` | `{generation['greedy_exact_books']}` | "
            f"`{generation['beam_exact_books']['20']}` | `{generation['beam_nontrivial_exact_books']['20']}` | "
            f"`{generation['greedy_prefix_ops']}` |"
        )

    lines.extend(
        [
            "",
            "Beam20 recovers nontrivial held-out coarse sequences in every cutoff for the "
            "best model. This promotes a coarse-control program candidate under the "
            "granted op-count condition, not a complete authorial generator.",
            "",
            "## Decision",
            "",
            "- `coarse_control_program_candidate`.",
            "- `type:length_bucket` is no longer only an undifferentiated atlas field; it "
            "has a prefix-generalizing coarse sequential controller candidate.",
            "- The candidate still grants per-book op count and does not produce exact "
            "length residuals.",
            "- `row0`, translation, plaintext, and the compression bound remain unchanged.",
            "",
            "## Remaining External Fields",
            "",
            "- per-book operation count",
            "- within-bucket length residual innovation tape",
            "- literal innovation tape payload and schedule",
            "- copy-hint rank stream",
            "- seed books `0..9`",
            "- `row0`",
            "",
            "## Reproducible Artifacts",
            "",
            "- [01_coarse_control_program_gate.py](../scripts/01_coarse_control_program_gate.py)",
            "- [01_coarse_control_program_gate.json](test_results/01_coarse_control_program_gate.json)",
            "- [01_coarse_control_program_gate.md](test_results/01_coarse_control_program_gate.md)",
            "- [02_compile_final_coarse_control_program_audit.py](../scripts/02_compile_final_coarse_control_program_audit.py)",
        ]
    )
    OUT.write_text("\n".join(lines) + "\n")
    print(
        json.dumps(
            {
                "best_model": best_name,
                "classification": result["classification"],
                "observed_saving": best["observed_saving_bits"],
                "promoted_models": result["decision"]["promoted_models"],
                "report": str(OUT.relative_to(ROOT)),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
