from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

LEDGER = TEST_RESULTS / "01_hard_boundary_ledger.json"
GRAMMAR = TEST_RESULTS / "02_source_free_skeleton_grammar_gate.json"
FINAL = REPORTS / "final_source_free_skeleton_generation_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") not in {
        None,
        "unchanged_exogenous",
        "exogenous_under_current_evidence",
    }:
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    ledger = load_json(LEDGER)
    grammar = load_json(GRAMMAR)
    assert_boundary("hard_boundary_ledger", ledger)
    assert_boundary("source_free_skeleton_grammar_gate", grammar)
    ls = ledger["summary"]
    gs = grammar["summary"]
    lines = [
        "# Final Source-Free Skeleton Generation Audit",
        "",
        "Status: `analysis_only`",
        "Classification: `SKELETON_ATLAS_RETAINED_GENERATOR_NOT_PROMOTED`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Can the exact source-free skeleton (`261` ops, `208` copies, `53`",
        "literal runs) be generated by a compact source-free grammar rather",
        "than retained as a materialized atlas?",
        "",
        "## Hard Boundary",
        "",
        f"- Skeleton atlas records: `{ls['skeleton_atlas_records']}`.",
        f"- Copy-source fields still external: `{ls['copy_source_fields']}`.",
        f"- Literal payload chunks/digits still external: `{ls['literal_payload_chunks']}` / `{ls['literal_payload_digits']}`.",
        f"- External dependency fields after skeleton: `{ls['external_dependency_fields_after_skeleton']}`.",
        f"- Total materialized records after skeleton: `{ls['total_materialized_records_after_skeleton']}`.",
        "",
        "The main blocker is therefore the skeleton atlas itself. Source choice",
        "and literal payload remain real, but they are secondary to deriving the",
        "operation sequence.",
        "",
        "## Grammar Gate",
        "",
        "| Diagnostic | Value |",
        "|---|---:|",
        f"| Context families | `{gs['context_family_count']}` |",
        f"| Distinct op labels | `{gs['label_count']}` |",
        f"| Best context | `{gs['best_context']}` |",
        f"| Best exact books | `{gs['best_exact_books']}/{gs['best_total_books']}` |",
        f"| Best op hits | `{gs['best_op_hits']}/{gs['best_op_total']}` |",
        f"| Best net vs atlas label bits | `{gs['best_net_vs_atlas_label_bits']:.3f}` bits |",
        f"| Prefix/holdout cover-all-test-books cells | `{gs['prequential_cover_all_test_books_cells']}/{gs['prequential_cells']}` |",
        "",
        "The tested source-free grammar families are rejected. Even granting",
        "book lengths, the best full-fit context explains only `3/60` books",
        "and `14/261` operation positions, is `+660.028` bits worse than a",
        "label-atlas lower bound after corrections, and has `0/5` holdout",
        "cells that generate all test books.",
        "",
        "## Decision",
        "",
        "- No source-free skeleton generator is promoted.",
        "- The exact skeleton remains a materialized atlas, not a derivation.",
        "- This falsifies simple grammars over operation index, prior operation,",
        "  book length, remaining length, phase, and book-mod/order features.",
        "- Copy-source selection should remain secondary until the skeleton is",
        "  generated or a stronger target-stream account appears.",
        "- Literal payload remains external and should be audited separately.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Hard boundary ledger](test_results/01_hard_boundary_ledger.md)",
        "- [Source-free skeleton grammar gate](test_results/02_source_free_skeleton_grammar_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    FINAL.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(FINAL)


if __name__ == "__main__":
    main()
