#!/usr/bin/env python3
"""Test prefix-generalized stateful control programs for exact type:length actions.

The unified control ledger showed that target starts are downstream of the
length stream, while type:length, literal payload, and copy hints remain
external. This gate asks whether the exact type:length action stream can be
encoded or generated by a small target-free state program instead of declared
as an atlas.
"""

from __future__ import annotations

import json
import math
import random
from collections import Counter, defaultdict
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[3]
FRONT = ROOT / "analysis" / "stateful_control_program_audit_20260622"
TEST_RESULTS = FRONT / "reports" / "test_results"
LEDGER_PATH = (
    ROOT
    / "analysis"
    / "unified_control_program_audit_20260622"
    / "reports"
    / "test_results"
    / "01_unified_residual_control_ledger.json"
)
JSON_OUT = TEST_RESULTS / "01_stateful_control_program_gate.json"
MD_OUT = TEST_RESULTS / "01_stateful_control_program_gate.md"

CUTOFFS = [20, 30, 40, 50, 60]
MODEL_RANDOM_TRIALS = 200
GENERATION_WIDTHS = [1, 5, 20]
TOP_CANDIDATES_PER_STATE = 12
ALPHA = 0.5
ESCAPE = 0.5
MIN_PROMOTION_SAVING_BITS = 25.0


MODEL_FEATURES: dict[str, tuple[str, ...]] = {
    "global": tuple(),
    "prev_bucket": ("prev_bucket",),
    "prev_action": ("prev_action",),
    "remaining_bucket": ("remaining_bucket",),
    "remaining_prev_bucket": ("remaining_bucket", "prev_bucket"),
    "remaining_prev_action": ("remaining_bucket", "prev_action"),
    "phase_remaining_prev_bucket": ("book_phase", "remaining_bucket", "prev_bucket"),
    "phase_remaining_prev_action": ("book_phase", "remaining_bucket", "prev_action"),
}


def log2(x: float) -> float:
    return math.log2(x)


def length_bucket(length: int) -> str:
    if length <= 8:
        return "len_0008"
    if length <= 16:
        return "len_0016"
    if length <= 32:
        return "len_0032"
    if length <= 64:
        return "len_0064"
    if length <= 128:
        return "len_0128"
    return "len_0256p"


def remaining_bucket(remaining: int) -> str:
    if remaining <= 8:
        return "rem_0008"
    if remaining <= 16:
        return "rem_0016"
    if remaining <= 32:
        return "rem_0032"
    if remaining <= 64:
        return "rem_0064"
    if remaining <= 128:
        return "rem_0128"
    if remaining <= 256:
        return "rem_0256"
    return "rem_0512p"


def book_phase(book: int) -> str:
    if book < 20:
        return "phase_10_19"
    if book < 35:
        return "phase_20_34"
    if book < 50:
        return "phase_35_49"
    if book < 60:
        return "phase_50_59"
    return "phase_60_69"


def online_op_bucket(op_index: int) -> str:
    if op_index == 0:
        return "first"
    if op_index <= 2:
        return "early"
    return "middle"


@lru_cache(maxsize=None)
def parse_action(action: str) -> tuple[str, int]:
    op_type, raw_length = action.split(":", 1)
    return op_type, int(raw_length)


def make_action(op_type: str, length: int) -> str:
    return f"{op_type}:{length}"


def context_key(record: dict, features: tuple[str, ...]) -> tuple[str, ...]:
    return tuple(str(record.get(feature, "<NA>")) for feature in features)


def baseline_action_bits(record: dict, action: str | None = None) -> float:
    if action is None:
        length = int(record["length"])
    else:
        _, length = parse_action(action)
    remaining = max(1, int(record["remaining_before_op"]))
    # One bit for literal/copy and a uniform exact length among still possible
    # positions. Invalid shuffled lengths keep the same baseline denominator so
    # controls preserve the row-feature surface rather than becoming a decoder.
    return 1.0 + log2(remaining)


@dataclass
class TrainedModel:
    name: str
    features: tuple[str, ...]
    context_counts: dict[tuple[str, ...], Counter]
    global_counts: Counter
    train_actions: set[str]


def load_records() -> list[dict]:
    data = json.loads(LEDGER_PATH.read_text())
    rows = sorted(data["ledger_rows"], key=lambda r: (r["book"], r["op_index"]))
    by_book: dict[int, list[dict]] = defaultdict(list)
    for row in rows:
        by_book[int(row["book"])].append(row)

    records: list[dict] = []
    for book in sorted(by_book):
        prev_action = "<BOS>"
        prev_bucket = "<BOS>"
        for row in by_book[book]:
            record = dict(row)
            action = make_action(row["op_type"], int(row["length"]))
            record["action"] = action
            record["prev_action"] = prev_action
            record["prev_bucket"] = prev_bucket
            record["remaining_bucket"] = remaining_bucket(int(row["remaining_before_op"]))
            record["online_op_bucket"] = online_op_bucket(int(row["op_index"]))
            record["book_phase"] = book_phase(int(row["book"]))
            record["exact_type_length_external"] = True
            records.append(record)
            prev_action = action
            prev_bucket = row["type_length_symbol"]
    return records


def train_model(name: str, train_rows: list[dict]) -> TrainedModel:
    features = MODEL_FEATURES[name]
    context_counts: dict[tuple[str, ...], Counter] = defaultdict(Counter)
    global_counts: Counter = Counter()
    for row in train_rows:
        action = row["action"]
        global_counts[action] += 1
        context_counts[context_key(row, features)][action] += 1
    return TrainedModel(
        name=name,
        features=features,
        context_counts=dict(context_counts),
        global_counts=global_counts,
        train_actions=set(global_counts),
    )


def action_probability(model: TrainedModel, record: dict, action: str) -> float:
    counts = model.context_counts.get(context_key(record, model.features))
    if not counts:
        counts = model.global_counts

    total = sum(counts.values())
    vocab = max(1, len(model.train_actions))
    denom = total + ALPHA * vocab + ESCAPE
    if action in model.train_actions:
        return (counts.get(action, 0) + ALPHA) / denom

    remaining = max(1, int(record["remaining_before_op"]))
    return (ESCAPE / denom) * (1.0 / (2.0 * remaining))


def action_bits(model: TrainedModel, record: dict, action: str | None = None) -> float:
    actual_action = record["action"] if action is None else action
    return -log2(max(action_probability(model, record, actual_action), 1e-300))


def score_model(model: TrainedModel, rows: list[dict], action_override: list[str] | None = None) -> dict:
    model_bits = 0.0
    baseline_bits = 0.0
    fallback_rows = 0
    for idx, row in enumerate(rows):
        action = row["action"] if action_override is None else action_override[idx]
        model_bits += action_bits(model, row, action)
        baseline_bits += baseline_action_bits(row, action)
        counts = model.context_counts.get(context_key(row, model.features))
        if not counts or action not in counts:
            fallback_rows += 1
    return {
        "baseline_bits": baseline_bits,
        "model_bits": model_bits,
        "saving_bits": baseline_bits - model_bits,
        "fallback_rows": fallback_rows,
    }


def state_record(
    *,
    book: int,
    book_length: int,
    remaining: int,
    op_index: int,
    prev_action: str,
    prev_bucket: str,
) -> dict:
    return {
        "book": book,
        "book_length": book_length,
        "book_phase": book_phase(book),
        "remaining_before_op": remaining,
        "remaining_bucket": remaining_bucket(remaining),
        "op_index": op_index,
        "online_op_bucket": online_op_bucket(op_index),
        "prev_action": prev_action,
        "prev_bucket": prev_bucket,
        "length": 1,
        "action": "copy:1",
    }


def candidate_actions(model: TrainedModel, remaining: int) -> list[str]:
    candidates = set()
    for action in model.train_actions:
        _, length = parse_action(action)
        if 1 <= length <= remaining:
            candidates.add(action)
    # Allow terminal fallback actions so a generated program can close a book
    # without needing the exact terminal length in the prefix inventory.
    candidates.add(make_action("copy", remaining))
    candidates.add(make_action("literal", remaining))
    return sorted(candidates)


def top_action(model: TrainedModel, record: dict, remaining: int) -> tuple[str, float]:
    ranked = ranked_candidate_actions(model, record, remaining, TOP_CANDIDATES_PER_STATE)
    return ranked[0][1], ranked[0][0]


def ranked_candidate_actions(
    model: TrainedModel,
    record: dict,
    remaining: int,
    limit: int,
) -> list[tuple[float, str]]:
    ranked = []
    for action in candidate_actions(model, remaining):
        prob = action_probability(model, record, action)
        ranked.append((-log2(max(prob, 1e-300)), action))
    ranked.sort(key=lambda item: (item[0], item[1]))
    return ranked[:limit]


def generate_greedy(model: TrainedModel, book: int, book_length: int, max_steps: int = 40) -> list[str]:
    remaining = book_length
    prev_action = "<BOS>"
    prev_bucket = "<BOS>"
    seq: list[str] = []
    for op_index in range(max_steps):
        if remaining <= 0:
            break
        rec = state_record(
            book=book,
            book_length=book_length,
            remaining=remaining,
            op_index=op_index,
            prev_action=prev_action,
            prev_bucket=prev_bucket,
        )
        action, _ = top_action(model, rec, remaining)
        _, length = parse_action(action)
        if length <= 0 or length > remaining:
            break
        seq.append(action)
        remaining -= length
        prev_action = action
        prev_bucket = f"{parse_action(action)[0]}:{length_bucket(length)}"
    return seq if remaining == 0 else seq + ["<FAILED_TO_CLOSE>"]


def generate_beam(
    model: TrainedModel,
    book: int,
    book_length: int,
    width: int,
    max_steps: int = 40,
) -> list[tuple[float, list[str]]]:
    beam = [(0.0, book_length, "<BOS>", "<BOS>", [])]
    complete: list[tuple[float, list[str]]] = []
    for op_index in range(max_steps):
        next_beam = []
        for cost, remaining, prev_action, prev_bucket, seq in beam:
            if remaining == 0:
                complete.append((cost, seq))
                continue
            rec = state_record(
                book=book,
                book_length=book_length,
                remaining=remaining,
                op_index=op_index,
                prev_action=prev_action,
                prev_bucket=prev_bucket,
            )
            for action_cost, action in ranked_candidate_actions(
                model, rec, remaining, TOP_CANDIDATES_PER_STATE
            ):
                op_type, length = parse_action(action)
                if length <= 0 or length > remaining:
                    continue
                next_beam.append(
                    (
                        cost + action_cost,
                        remaining - length,
                        action,
                        f"{op_type}:{length_bucket(length)}",
                        seq + [action],
                    )
                )
        if not next_beam:
            break
        next_beam.sort(key=lambda item: (item[0], item[4]))
        beam = next_beam[:width]
    complete.extend((cost, seq) for cost, remaining, _, _, seq in beam if remaining == 0)
    complete.sort(key=lambda item: (item[0], item[1]))
    return complete[:width]


def common_prefix_len(left: list[str], right: list[str]) -> int:
    total = 0
    for a, b in zip(left, right):
        if a != b:
            break
        total += 1
    return total


def generation_eval(model: TrainedModel, test_books: dict[int, list[dict]]) -> dict:
    greedy_exact_books = 0
    greedy_prefix_ops = 0
    greedy_position_hits = 0
    greedy_total_positions = 0
    beam_exact_by_width = {str(width): 0 for width in GENERATION_WIDTHS}
    beam_exact_nontrivial_by_width = {str(width): 0 for width in GENERATION_WIDTHS}
    beam_exact_books_by_width = {str(width): [] for width in GENERATION_WIDTHS}
    beam_prefix_by_width = {str(width): 0 for width in GENERATION_WIDTHS}
    examples = []

    for book, rows in sorted(test_books.items()):
        true_seq = [row["action"] for row in rows]
        book_length = int(rows[0]["book_length"])
        greedy = generate_greedy(model, book, book_length)
        if greedy == true_seq:
            greedy_exact_books += 1
        prefix_len = common_prefix_len(greedy, true_seq)
        greedy_prefix_ops += prefix_len
        greedy_position_hits += sum(1 for a, b in zip(greedy, true_seq) if a == b)
        greedy_total_positions += len(true_seq)
        if len(examples) < 8 and greedy != true_seq:
            examples.append(
                {
                    "book": book,
                    "true": true_seq,
                    "greedy": greedy[: len(true_seq) + 3],
                    "prefix_ops": prefix_len,
                }
            )
        for width in GENERATION_WIDTHS:
            completed = generate_beam(model, book, book_length, width)
            completed_seqs = [seq for _, seq in completed]
            if true_seq in completed_seqs:
                beam_exact_by_width[str(width)] += 1
                beam_exact_books_by_width[str(width)].append(book)
                if len(true_seq) > 1:
                    beam_exact_nontrivial_by_width[str(width)] += 1
            best_prefix = max((common_prefix_len(seq, true_seq) for seq in completed_seqs), default=0)
            beam_prefix_by_width[str(width)] += best_prefix

    return {
        "beam_exact_books_by_width": beam_exact_by_width,
        "beam_exact_book_ids_by_width": beam_exact_books_by_width,
        "beam_exact_nontrivial_books_by_width": beam_exact_nontrivial_by_width,
        "beam_prefix_ops_by_width": beam_prefix_by_width,
        "examples": examples,
        "greedy_exact_books": greedy_exact_books,
        "greedy_position_hits": greedy_position_hits,
        "greedy_prefix_ops": greedy_prefix_ops,
        "greedy_total_positions": greedy_total_positions,
        "test_books": len(test_books),
    }


def group_books(rows: Iterable[dict]) -> dict[int, list[dict]]:
    grouped: dict[int, list[dict]] = defaultdict(list)
    for row in rows:
        grouped[int(row["book"])].append(row)
    return {book: sorted(items, key=lambda r: r["op_index"]) for book, items in grouped.items()}


def run_gate() -> dict:
    records = load_records()
    rng = random.Random(469)
    models: dict[str, dict] = {}

    for model_name in MODEL_FEATURES:
        cutoff_rows = []
        observed_total_saving = 0.0
        observed_total_model_bits = 0.0
        observed_total_baseline_bits = 0.0
        observed_total_fallback_rows = 0
        random_total_savings = [0.0 for _ in range(MODEL_RANDOM_TRIALS)]

        for cutoff in CUTOFFS:
            train_rows = [row for row in records if int(row["book"]) < cutoff]
            test_rows = [row for row in records if int(row["book"]) >= cutoff]
            model = train_model(model_name, train_rows)
            score = score_model(model, test_rows)
            observed_total_saving += score["saving_bits"]
            observed_total_model_bits += score["model_bits"]
            observed_total_baseline_bits += score["baseline_bits"]
            observed_total_fallback_rows += score["fallback_rows"]

            actions = [row["action"] for row in test_rows]
            for trial_idx in range(MODEL_RANDOM_TRIALS):
                shuffled = list(actions)
                rng.shuffle(shuffled)
                random_total_savings[trial_idx] += score_model(model, test_rows, shuffled)["saving_bits"]

            cutoff_rows.append(
                {
                    "cutoff": cutoff,
                    "train_ops": len(train_rows),
                    "test_ops": len(test_rows),
                    "train_books": len(set(row["book"] for row in train_rows)),
                    "test_books": len(set(row["book"] for row in test_rows)),
                    **score,
                    "greedy_exact_books": None,
                    "beam20_exact_books": None,
                    "greedy_prefix_ops": None,
                }
            )

        random_sorted = sorted(random_total_savings)
        random_p95 = random_sorted[int(0.95 * (len(random_sorted) - 1))]
        random_p05 = random_sorted[int(0.05 * (len(random_sorted) - 1))]
        beats_random = observed_total_saving > random_p95
        meaningful_saving = observed_total_saving > MIN_PROMOTION_SAVING_BITS

        models[model_name] = {
            "beats_random_p95": beats_random,
            "cutoff_rows": cutoff_rows,
            "features": MODEL_FEATURES[model_name],
            "generation_by_cutoff": {},
            "meaningful_saving": meaningful_saving,
            "observed_total_baseline_bits": observed_total_baseline_bits,
            "observed_total_fallback_rows": observed_total_fallback_rows,
            "observed_total_model_bits": observed_total_model_bits,
            "observed_total_saving_bits": observed_total_saving,
            "random_saving_p05": random_p05,
            "random_saving_p95": random_p95,
            "status": "PENDING_GENERATION_CHECK",
        }

    best_by_bits = min(models.items(), key=lambda item: item[1]["observed_total_model_bits"])
    best_by_saving = max(models.items(), key=lambda item: item[1]["observed_total_saving_bits"])
    generation_candidates = {
        best_by_bits[0],
        best_by_saving[0],
        *[
            name
            for name, result in models.items()
            if result["beats_random_p95"] and result["meaningful_saving"]
        ],
    }

    for model_name in generation_candidates:
        generation_by_cutoff = {}
        for cutoff in CUTOFFS:
            train_rows = [row for row in records if int(row["book"]) < cutoff]
            test_rows = [row for row in records if int(row["book"]) >= cutoff]
            model = train_model(model_name, train_rows)
            generation = generation_eval(model, group_books(test_rows))
            generation_by_cutoff[str(cutoff)] = generation
            for cutoff_row in models[model_name]["cutoff_rows"]:
                if cutoff_row["cutoff"] == cutoff:
                    cutoff_row["greedy_exact_books"] = generation["greedy_exact_books"]
                    cutoff_row["beam20_exact_books"] = generation["beam_exact_books_by_width"]["20"]
                    cutoff_row["beam20_nontrivial_exact_books"] = generation[
                        "beam_exact_nontrivial_books_by_width"
                    ]["20"]
                    cutoff_row["greedy_prefix_ops"] = generation["greedy_prefix_ops"]
                    break
        models[model_name]["generation_by_cutoff"] = generation_by_cutoff

    for model_name, result in models.items():
        any_exact_generation = any(
            generation["beam_exact_nontrivial_books_by_width"]["20"] > 0
            for generation in result["generation_by_cutoff"].values()
        )
        if result["beats_random_p95"] and result["meaningful_saving"] and any_exact_generation:
            status = "PROMOTED_CONTROL_PROGRAM_CANDIDATE"
        elif result["beats_random_p95"] and result["meaningful_saving"]:
            status = "PROMOTED_CONTROL_CODEC_CLUE_NOT_GENERATOR"
        elif result["beats_random_p95"]:
            status = "WEAK_CONTROL_CODEC_CLUE"
        else:
            status = "REJECTED_CONTROL_PROGRAM"
        result["status"] = status

    promoted = [
        name
        for name, result in models.items()
        if result["status"] in {"PROMOTED_CONTROL_PROGRAM_CANDIDATE", "PROMOTED_CONTROL_CODEC_CLUE_NOT_GENERATOR"}
    ]
    generator_promoted = [
        name for name, result in models.items() if result["status"] == "PROMOTED_CONTROL_PROGRAM_CANDIDATE"
    ]

    if generator_promoted:
        classification = "stateful_control_program_candidate"
    elif promoted:
        classification = "stateful_control_codec_clue_not_generator"
    else:
        classification = "stateful_control_program_not_promoted"

    return {
        "case_reopened": False,
        "classification": classification,
        "compression_bound_status": "unchanged",
        "decision": {
            "best_by_bits": best_by_bits[0],
            "best_by_saving": best_by_saving[0],
            "generator_promoted": generator_promoted,
            "promoted_models": promoted,
            "row0_status": "unchanged_exogenous",
        },
        "inputs": {
            "ledger": str(LEDGER_PATH.relative_to(ROOT)),
            "cutoffs": CUTOFFS,
            "models": MODEL_FEATURES,
            "random_trials": MODEL_RANDOM_TRIALS,
        },
        "models": models,
        "plaintext_claim": False,
        "scope": "analysis_only_target_free_exact_type_length_control_stream",
        "translation_delta": "NONE",
    }


def write_markdown(result: dict) -> None:
    lines = [
        "# Stateful Control Program Gate",
        "",
        f"Classification: `{result['classification']}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Case reopened: `False`",
        "",
        "## Purpose",
        "",
        "This gate tests whether the residual exact `type:length` control stream can be "
        "coded or generated by a target-free stateful program trained on prefix books. "
        "The decoder is granted book id, book length, previous emitted control state, "
        "and remaining length. It is not granted target text, row0 origin, plaintext, "
        "copy source, or the true skeleton.",
        "",
        "## Model Summary",
        "",
        "| Model | Features | Bits | Saving | Random p95 | Fallback Rows | Status |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- |",
    ]

    for name, model in sorted(result["models"].items()):
        lines.append(
            f"| `{name}` | `{'+'.join(model['features']) or 'global'}` | "
            f"`{model['observed_total_model_bits']:.3f}` | "
            f"`{model['observed_total_saving_bits']:.3f}` | "
            f"`{model['random_saving_p95']:.3f}` | "
            f"`{model['observed_total_fallback_rows']}` | `{model['status']}` |"
        )

    decision = result["decision"]
    best_model = result["models"][decision["best_by_bits"]]
    lines.extend(
        [
            "",
            "## Best Model",
            "",
            f"- Best by bits: `{decision['best_by_bits']}`.",
            f"- Best by saving: `{decision['best_by_saving']}`.",
            f"- Promoted models: `{decision['promoted_models']}`.",
            f"- Generator-promoted models: `{decision['generator_promoted']}`.",
            f"- Best model total bits over cutoffs: `{best_model['observed_total_model_bits']:.3f}`.",
            f"- Best model total saving vs independent exact type+length: `{best_model['observed_total_saving_bits']:.3f}`.",
            f"- Best model shuffled p95 saving: `{best_model['random_saving_p95']:.3f}`.",
            "",
            "## Generation Check",
            "",
            "| Cutoff | Test Books | Greedy Exact | Beam20 Exact | Beam20 Nontrivial | Greedy Prefix Ops |",
            "| ---: | ---: | ---: | ---: | ---: | ---: |",
        ]
    )

    for row in best_model["cutoff_rows"]:
        lines.append(
            f"| `{row['cutoff']}` | `{row['test_books']}` | `{row['greedy_exact_books']}` | "
            f"`{row['beam20_exact_books']}` | `{row['beam20_nontrivial_exact_books']}` | "
            f"`{row['greedy_prefix_ops']}` |"
        )

    lines.extend(
        [
            "",
            "## Decision",
            "",
        ]
    )
    if result["classification"] == "stateful_control_program_candidate":
        lines.append(
            "A stateful control program candidate is promoted because it beats shuffled "
            "controls and generates at least one held-out book's exact control sequence "
            "inside the beam."
        )
    elif result["classification"] == "stateful_control_codec_clue_not_generator":
        lines.append(
            "A predictive control-codec clue is promoted, but not a generator. The model "
            "reduces exact type:length declaration cost under prefix/holdout and beats "
            "shuffled controls, yet it does not generate held-out books without residual "
            "corrections."
        )
    else:
        lines.append(
            "No stateful control program is promoted. The exact-action codec is worse "
            "than independent type+length declaration and worse than shuffled-control "
            "p95; any beam exact hits are therefore not usable generation evidence."
        )

    lines.extend(
        [
            "",
            "`row0` remains exogenous. Translation/plaintext remain unchanged. The "
            "`compression_bound` is unchanged because this gate only tests residual "
            "control-stream generation.",
            "",
            "## Remaining External Fields",
            "",
            "- exact `type:length` control sequence, unless covered by a promoted codec clue",
            "- literal innovation tape payload and schedule",
            "- copy-hint rank stream",
            "- seed books `0..9`",
            "- `row0`",
        ]
    )
    MD_OUT.write_text("\n".join(lines) + "\n")


def main() -> None:
    TEST_RESULTS.mkdir(parents=True, exist_ok=True)
    result = run_gate()
    JSON_OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    write_markdown(result)
    print(
        json.dumps(
            {
                "classification": result["classification"],
                "best_by_bits": result["decision"]["best_by_bits"],
                "best_by_saving": result["decision"]["best_by_saving"],
                "promoted_models": result["decision"]["promoted_models"],
                "generator_promoted": result["decision"]["generator_promoted"],
                "report": str(MD_OUT.relative_to(ROOT)),
            },
            indent=2,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
