from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

GATE = TEST_RESULTS / "01_operation_cutpoint_scaling_gate.json"
OUT = REPORTS / "final_operation_cutpoint_scaling_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    gate = load_json(GATE)
    assert_boundary("operation_cutpoint_scaling_gate", gate)
    s = gate["summary"]
    classification = (
        "OPERATION_CUTPOINT_SCALING_GENERATOR_PROMOTED"
        if s["promotes_cutpoint_scaling_generator"]
        else "OPERATION_CUTPOINT_SCALING_GENERATOR_REJECTED"
    )
    lines = [
        "# Final Operation Cutpoint Scaling Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Can operation lengths be generated by normalized cutpoint templates",
        "scaled to the granted book length?",
        "",
        "## Result",
        "",
        f"- Books/operations: `{s['book_count']}` / `{s['operation_count']}`.",
        f"- Key families tested: `{s['key_family_count']}`.",
        f"- Best key: `{s['best_key']}`.",
        f"- Best templates/payload records: `{s['best_template_count']}` / `{s['best_template_payload_records']}`.",
        f"- Best exact books: `{s['best_exact_books']}/{s['book_count']}`.",
        f"- Best row hits: `{s['best_row_hits']}/{s['best_truth_ops']}`.",
        f"- Best delta vs exact atlas records: `{s['best_delta_vs_exact_atlas_records']:+d}`.",
        f"- Prefix/holdout cover-all cells: `{s['prequential_cover_all_cells']}/{s['prequential_cells']}`.",
        f"- Prefix/holdout positive-delta cells: `{s['prequential_positive_delta_cells']}/{s['prequential_cells']}`.",
        "",
        "The best full-fit template family approximates many books, but it",
        "pays too much template payload and correction cost. Prefix/holdout",
        "is negative in every split.",
        "",
        "## Decision",
        "",
        "- No cutpoint-scaling generator is promoted.",
        "- Proportional cutpoint templates are descriptive, not a replacement for the operation-length atlas.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Operation cutpoint scaling gate](test_results/01_operation_cutpoint_scaling_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
