from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

GATE = TEST_RESULTS / "01_operation_type_weighted_length_gate.json"
OUT = REPORTS / "final_operation_type_weighted_length_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    gate = load_json(GATE)
    assert_boundary("operation_type_weighted_length_gate", gate)
    s = gate["summary"]
    classification = (
        "OPERATION_TYPE_WEIGHTED_LENGTH_GENERATOR_PROMOTED"
        if s["promotes_type_weighted_length_generator"]
        else "OPERATION_TYPE_WEIGHTED_LENGTH_GENERATOR_REJECTED"
    )
    lines = [
        "# Final Operation Type-Weighted Length Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Can the `261` operation lengths be generated by simple",
        "source-free weighted allocation once book length and literal/copy",
        "sequence are granted?",
        "",
        "## Result",
        "",
        f"- Books/operations: `{s['book_count']}` / `{s['operation_count']}`.",
        f"- Models tested: `{s['model_count']}`.",
        f"- Best model: `{s['best_model']}`.",
        f"- Best model kind: `{s['best_kind']}`.",
        f"- Best exact books: `{s['best_exact_books']}/{s['book_count']}`.",
        f"- Best row hits: `{s['best_row_hits']}/{s['operation_count']}`.",
        f"- Best row errors: `{s['best_row_errors']}`.",
        f"- Best absolute error: `{s['best_absolute_error']}`.",
        f"- Best paid records: `{s['best_paid_records']}` vs exact length fields `{s['exact_length_field_records']}`.",
        f"- Paid-record delta vs exact length fields: `{s['paid_record_delta_vs_exact_length_fields']:+d}`.",
        f"- Prefix/holdout cover-all cells: `{s['prequential_cover_all_cells']}/{s['prequential_cells']}`.",
        "",
        "The best full-corpus model is `learned_by_shape_x_type_x_position`,",
        "but it still reproduces only `14/60` books and pays more than the",
        "exact length-field atlas after corrections. Prefix/holdout has no",
        "cover-all cell.",
        "",
        "## Decision",
        "",
        "- No operation-length generator is promoted.",
        "- Type-weighted source-free allocation is rejected as a structural generator.",
        "- Operation lengths remain retained unless a later joint parser derives them with copy availability/source state.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Operation type-weighted length gate](test_results/01_operation_type_weighted_length_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
