#!/usr/bin/env python3
"""5 eyes x 2 states arity probe for the 469 pair table.

Hypothesis: the 10 digits may correspond to five eye channels with two
states/phases each. This is compared as a control against the K5 eye-pair
model.

Mechanical only. No plaintext or glossary is promoted.
"""

from __future__ import annotations

import math

from eye_model_common import HERE, evaluate_family, load_pair_labels, state_5x2_feature_rows, write_json


OUT_JSON = HERE / "eye_state_5x2_model_results.json"
OUT_MD = HERE / "eye_state_5x2_model_report.md"


def write_report(result: dict) -> None:
    best_label = result["best_label_rule"]
    best_e = result["best_e_rule"]
    controls = result["controls"]
    lines = [
        "# Eye-State 5x2 Model Search",
        "",
        "Generated by `eye_state_5x2_model_search.py`.",
        "",
        "Scope: mechanical origin only. This tests whether `5 eyes x 2 states`",
        "compresses or predicts the existing 55-cell row0 pair table.",
        "",
        "## Setup",
        "",
        f"- Distinct eye/state feature mappings tested: `{result['feature_rows']}`.",
        f"- Mapping/search cost charged: `{result['mapping_bits_charged']:.2f}` bits.",
        f"- Label/E controls: `{controls['trials']}` inventory-preserving shuffles.",
        f"- Control mode: `{controls['mode']}` with `{controls['feature_rows_per_trial']}` feature rows per trial.",
        "- Features: `same_token`, `same_eye_opposite_state`, `same_state_different_eye`, `different_eye_different_state`.",
        "",
        "## Best Full-Label Rule",
        "",
        "| Hits | Accuracy | MDL bits | Gain vs lookup | Control p | 6/9 relation | Verdict |",
        "|---:|---:|---:|---:|---:|---|---|",
        (
            f"| {best_label['hits']}/55 | {best_label['accuracy']:.3f} | "
            f"{best_label['mdl']['total_bits']:.1f} | {best_label['mdl']['gain_vs_lookup']:.1f} | "
            f"{controls['label_gain_p']:.5f} | `{best_label['relation_6_9']}` | "
            "`reject_as_pair_matrix_formula` |"
        ),
        "",
        "## Best E-Layer Rule",
        "",
        "| Selected feature values | TP | FP | FN | F1 | MDL gain vs binary lookup | Control p(F1) | Control p(MDL) | Verdict |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|",
        (
            f"| `{', '.join(best_e['selected_feature_values'])}` | {best_e['tp']} | {best_e['fp']} | {best_e['fn']} | "
            f"{best_e['f1']:.3f} | {best_e['mdl']['gain_vs_lookup']:.1f} | "
            f"{controls['e_f1_p']:.5f} | {controls['e_gain_p']:.5f} | `weak_descriptive_only` |"
        ),
        "",
        "## Anomaly Snapshot",
        "",
        "| Cell | 5x2 relation in best label mapping |",
        "|---|---|",
    ]
    for cell, relation in best_label["anomaly_relations"].items():
        lines.append(f"| `{cell}` | `{relation}` |")
    lines += [
        "",
        "## Interpretation",
        "",
        "The 5x2 model is a useful control because it also creates 10 digit tokens",
        "from eye lore, but it does not recover the pair-table labels below lookup",
        "cost. Treat it as a rejected origin formula unless future external evidence",
        "adds a specific eye/state mapping.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    labels = load_pair_labels()
    rows = state_5x2_feature_rows()
    # Unordered eye pairs and per-eye state flips are redundant for this feature
    # family; charge the distinct assignment count represented by the rows.
    result = evaluate_family(labels, rows, mapping_bits=math.log2(max(2, len(rows))), family_name="eye_state_5x2")
    result["schema"] = "eye_state_5x2_model_results.v1"
    result["translation_delta"] = "NONE"
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
