#!/usr/bin/env python3
"""K5 eye-pair arity probe for the 469 pair table.

Hypothesis: if a relevant Bonelord has five eyes, the 10 digits may correspond
to the 10 unordered eye pairs in K5. Then row0 cells are pairs of K5 edges.

This is mechanism-origin testing only. It does not decode plaintext.
"""

from __future__ import annotations

import math

from eye_model_common import HERE, evaluate_family, k5_feature_rows, load_pair_labels, write_json


OUT_JSON = HERE / "k5_eye_pair_model_results.json"
OUT_MD = HERE / "k5_eye_pair_model_report.md"


def write_report(result: dict) -> None:
    best_label = result["best_label_rule"]
    best_e = result["best_e_rule"]
    controls = result["controls"]
    lines = [
        "# K5 Eye-Pair Model Search",
        "",
        "Generated by `k5_eye_pair_model_search.py`.",
        "",
        "Scope: mechanical origin only. This tests whether `5 eyes -> C(5,2)=10`",
        "compresses or predicts the existing 55-cell row0 pair table. It does not",
        "assign meanings, plaintext, or a glossary.",
        "",
        "## Setup",
        "",
        f"- Distinct K5 edge-adjacency mappings tested: `{result['feature_rows']}`.",
        f"- Mapping/search cost charged: `{result['mapping_bits_charged']:.2f}` bits (`log2(10!/5!)`).",
        f"- Label/E controls: `{controls['trials']}` inventory-preserving shuffles.",
        f"- Control mode: `{controls['mode']}` with `{controls['feature_rows_per_trial']}` feature rows per trial.",
        "- Features: `same_edge`, `adjacent_edges`, `disjoint_edges`.",
        "",
        "## Best Full-Label Rule",
        "",
        "| Hits | Accuracy | MDL bits | Gain vs lookup | Control p | 6/9 relation | Verdict |",
        "|---:|---:|---:|---:|---:|---|---|",
        (
            f"| {best_label['hits']}/55 | {best_label['accuracy']:.3f} | "
            f"{best_label['mdl']['total_bits']:.1f} | {best_label['mdl']['gain_vs_lookup']:.1f} | "
            f"{controls['label_gain_p']:.5f} | `{best_label['relation_6_9']}` | "
            "`reject_as_pair_matrix_formula` |"
        ),
        "",
        "Best feature majority labels:",
        "",
        "| Feature | Majority label |",
        "|---|---|",
    ]
    for feature, label in sorted(best_label["feature_majority_labels"].items()):
        lines.append(f"| `{feature}` | `{label}` |")
    lines += [
        "",
        "## Best E-Layer Rule",
        "",
        "| Selected K5 feature values | TP | FP | FN | F1 | MDL gain vs binary lookup | Control p(F1) | Control p(MDL) | Verdict |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---|",
        (
            f"| `{', '.join(best_e['selected_feature_values'])}` | {best_e['tp']} | {best_e['fp']} | {best_e['fn']} | "
            f"{best_e['f1']:.3f} | {best_e['mdl']['gain_vs_lookup']:.1f} | "
            f"{controls['e_f1_p']:.5f} | {controls['e_gain_p']:.5f} | `weak_descriptive_only` |"
        ),
        "",
        "## Anomaly Snapshot",
        "",
        "| Cell | K5 relation in best label mapping |",
        "|---|---|",
    ]
    for cell, relation in best_label["anomaly_relations"].items():
        lines.append(f"| `{cell}` | `{relation}` |")
    lines += [
        "",
        "## Interpretation",
        "",
        "The combinatorial match `5 eyes -> 10 edge-pairs -> 55 unordered cell pairs`",
        "is structurally elegant, but the tested K5 relation layer does not recover",
        "the pair-table labels below lookup cost. Its E-layer fit is at most a",
        "descriptive weak clue and must not be promoted as the origin formula.",
        "",
        "Translation delta: `NONE`.",
        "",
    ]
    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    labels = load_pair_labels()
    rows = k5_feature_rows()
    # K5 vertex automorphisms do not change edge adjacency, so charge the
    # non-isomorphic digit-to-edge search width rather than the full 10!.
    result = evaluate_family(labels, rows, mapping_bits=math.log2(math.factorial(10) / math.factorial(5)), family_name="k5_eye_pair")
    result["schema"] = "k5_eye_pair_model_results.v1"
    result["translation_delta"] = "NONE"
    write_json(OUT_JSON, result)
    write_report(result)
    print(f"wrote {OUT_JSON}")
    print(f"wrote {OUT_MD}")


if __name__ == "__main__":
    main()
