from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parents[1]
REPORTS = HERE / "reports"
TEST_RESULTS = REPORTS / "test_results"

GATE = TEST_RESULTS / "01_target_digit_process_gate.json"
OUT = REPORTS / "final_target_digit_process_audit.md"


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def assert_boundary(name: str, data: dict[str, Any]) -> None:
    if data.get("translation_delta") != "NONE":
        raise RuntimeError(f"{name} changed translation boundary")
    if data.get("case_reopened", False) is not False:
        raise RuntimeError(f"{name} reopened case")
    if data.get("plaintext_claim", False) is not False:
        raise RuntimeError(f"{name} introduced plaintext")
    decision = data.get("decision", {})
    if decision.get("row0_origin_status") != "unchanged_exogenous":
        raise RuntimeError(f"{name} changed row0 origin")
    if decision.get("translation_or_plaintext_status", "NONE") != "NONE":
        raise RuntimeError(f"{name} introduced translation/plaintext")


def main() -> None:
    gate = load_json(GATE)
    assert_boundary("target_digit_process_gate", gate)
    s = gate["summary"]
    classification = "TARGET_DIGIT_MARKOV_CLUE_PROMOTED_NOT_GENERATOR"
    lines = [
        "# Final Target Digit Process Audit",
        "",
        "Status: `analysis_only`",
        f"Classification: `{classification}`",
        "Translation delta: `NONE`",
        "Plaintext claim: `False`",
        "Row0 origin: `unchanged_exogenous`",
        "Compression bound: `unchanged_8154_676268`",
        "",
        "## Question",
        "",
        "Can the target digit stream that downstream copy-source collapse needs",
        "be generated by a simple source-free digit process, rather than being",
        "declared as payload?",
        "",
        "## Result",
        "",
        f"- All-book digits tested: `{s['all70_digit_count']}`.",
        f"- All70 aggregate validation test digits: `{s['all70_aggregate_test_digit_count']}`.",
        f"- Derived-book digits tested: `{s['derived60_digit_count']}`.",
        f"- Derived60 aggregate validation test digits: `{s['derived60_aggregate_test_digit_count']}`.",
        f"- Best all70 model: `{s['all70_best_model']}` at `{s['all70_best_test_bpd']:.6f}` bits/digit, `{s['all70_best_gain_vs_uniform_bits']:.3f}` aggregate bits vs uniform.",
        f"- All70 beats shuffled best p95: `{s['all70_beats_shuffled_best_p95']}`.",
        f"- Best derived60 model: `{s['derived60_best_model']}` at `{s['derived60_best_test_bpd']:.6f}` bits/digit, `{s['derived60_best_gain_vs_uniform_bits']:.3f}` aggregate bits vs uniform.",
        f"- Derived60 beats shuffled best p95: `{s['derived60_beats_shuffled_best_p95']}`.",
        f"- Target digit Markov clue promoted: `{s['target_digit_markov_clue']}`.",
        "",
        "The result promotes a narrow mechanical clue: a second-order digit",
        "process (`prev2_digits`) is strongly predictive under prefix/suffix",
        "validation and beats same-book-histogram shuffled controls in both",
        "scopes. This is not a complete generator. The model still emits the",
        "books only by paying residual arithmetic bits and does not explain",
        "operation chunk endpoints or exact copied payload choices.",
        "",
        "## Decision",
        "",
        "- A target-digit Markov clue is promoted.",
        "- No source-free target digit process generator is promoted.",
        "- The target-stream blocker remains open.",
        "- This does not change the compression bound.",
        "- Row0 remains exogenous and unchanged.",
        "- No plaintext, translation, semantic reading, or case reopening is introduced.",
        "",
        "## Sources",
        "",
        "- [Target digit process gate](test_results/01_target_digit_process_gate.md)",
    ]
    REPORTS.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(json.dumps({"classification": classification, "output": str(OUT.relative_to(ROOT))}, indent=2))


if __name__ == "__main__":
    main()
