#!/usr/bin/env python3
"""Validate and summarize the 2026-06-18 lore-source registry.

The registry is stored as JSON-compatible YAML so this script can stay
dependency-free. It does not test new decipherment claims; it only checks that
every lore front is classified, gated, and explicit about translation value.
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path


HERE = Path(__file__).resolve().parent
REGISTRY_PATH = HERE / "00_source_registry.yaml"
INVENTORY_JSON = HERE / "source_inventory.json"
INVENTORY_TABLE = HERE / "source_inventory_table.md"

REQUIRED_ENTRY_FIELDS = {
    "id",
    "rank",
    "title",
    "evidence_class",
    "priority",
    "source_type",
    "source_confidence",
    "sources",
    "text_keys",
    "numbers",
    "status",
    "translation_value",
    "mechanism_value",
    "required_gate",
    "tests",
}


def load_registry() -> dict:
    with REGISTRY_PATH.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def validate_registry(registry: dict) -> list[str]:
    errors: list[str] = []
    entries = registry.get("entries")
    if not isinstance(entries, list) or not entries:
        return ["registry.entries must be a non-empty list"]

    seen_ids: set[str] = set()
    allowed_classes = set(registry.get("classes", []))

    for index, entry in enumerate(entries, start=1):
        entry_id = entry.get("id", f"<entry {index}>")
        missing = sorted(REQUIRED_ENTRY_FIELDS - entry.keys())
        if missing:
            errors.append(f"{entry_id}: missing fields {', '.join(missing)}")
        if entry_id in seen_ids:
            errors.append(f"{entry_id}: duplicate id")
        seen_ids.add(entry_id)
        evidence_class = entry.get("evidence_class")
        if evidence_class not in allowed_classes:
            errors.append(f"{entry_id}: unknown evidence_class {evidence_class!r}")
        if entry.get("translation_value") != "NONE":
            errors.append(f"{entry_id}: translation_value must remain NONE")
        for field in ("sources", "text_keys", "numbers", "tests"):
            if not isinstance(entry.get(field), list):
                errors.append(f"{entry_id}: {field} must be a list")
    return errors


def build_inventory(registry: dict) -> dict:
    entries = registry["entries"]
    class_counts = Counter(entry["evidence_class"] for entry in entries)
    status_counts = Counter(entry["status"] for entry in entries)
    priority_counts = Counter(entry["priority"] for entry in entries)

    return {
        "schema": "lore_source_inventory.v1",
        "created_from": REGISTRY_PATH.name,
        "entry_count": len(entries),
        "translation_delta": registry["global_verdict"]["translation_delta"],
        "new_cipsoft_ground_truth": registry["global_verdict"]["new_cipsoft_ground_truth"],
        "new_number_plaintext_pair": registry["global_verdict"]["new_number_plaintext_pair"],
        "class_counts": dict(sorted(class_counts.items())),
        "status_counts": dict(sorted(status_counts.items())),
        "priority_counts": dict(sorted(priority_counts.items())),
        "entries": [
            {
                "rank": entry["rank"],
                "id": entry["id"],
                "title": entry["title"],
                "evidence_class": entry["evidence_class"],
                "priority": entry["priority"],
                "status": entry["status"],
                "translation_value": entry["translation_value"],
                "numbers": entry["numbers"],
                "tests": entry["tests"],
            }
            for entry in sorted(entries, key=lambda item: item["rank"])
        ],
    }


def table_escape(value: object) -> str:
    text = ", ".join(map(str, value)) if isinstance(value, list) else str(value)
    return text.replace("|", "\\|")


def write_markdown_table(inventory: dict) -> None:
    lines = [
        "# Lore source inventory (2026-06-18)",
        "",
        "Generated by `01_source_inventory.py` from `00_source_registry.yaml`.",
        "",
        f"- Entries: {inventory['entry_count']}",
        f"- Translation delta: `{inventory['translation_delta']}`",
        f"- New CipSoft ground truth: `{inventory['new_cipsoft_ground_truth']}`",
        f"- New number<->plaintext pair: `{inventory['new_number_plaintext_pair']}`",
        "",
        "| Rank | ID | Class | Priority | Status | Translation value | Numbers |",
        "|---:|---|---|---|---|---|---|",
    ]

    for entry in inventory["entries"]:
        lines.append(
            "| {rank} | `{id}` | {evidence_class} | {priority} | `{status}` | "
            "`{translation_value}` | {numbers} |".format(
                rank=entry["rank"],
                id=entry["id"],
                evidence_class=entry["evidence_class"],
                priority=entry["priority"],
                status=entry["status"],
                translation_value=entry["translation_value"],
                numbers=table_escape(entry["numbers"]),
            )
        )
    lines.append("")
    INVENTORY_TABLE.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    registry = load_registry()
    errors = validate_registry(registry)
    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    inventory = build_inventory(registry)
    INVENTORY_JSON.write_text(
        json.dumps(inventory, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    write_markdown_table(inventory)

    print(f"validated {inventory['entry_count']} lore fronts")
    print(f"wrote {INVENTORY_JSON.relative_to(HERE)}")
    print(f"wrote {INVENTORY_TABLE.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
